### ISSUE TITLE
Integrate Jackson Module Kogera

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#1007]
There's an experimental jackson kotlin module that uses the lightweight `kotlinx-metadata-jvm` reflective backend.  If we wanted to integrate it, would we do it with a new module?  Or simply as a cookbook article?

https://github.com/ProjectMapK/jackson-module-kogera

**Comment by daviddenton** [comment]
this might be interesting in the longer term, but since it's currently hosted only on jitpack and not maven central it's going to be a bit of a blocker to us making it first class.

Obviously feel free to write and host an adapter - or is it a drop in replacement for KotlinModule?

**Comment by oharaandrew314** [comment]
Yes, it's a drop-in replacement for the `KotlinModule`.  Maybe it just needs a cookbook guide then 🤷

**Comment by daviddenton** [comment]
👍 . I think this and Kotshi and the moshi-lightweight items can be put into their own page: "making JSON betterer" or something 🙃

**Comment by oharaandrew314** [comment]
Agreed.

**Comment by oharaandrew314** [comment]
I would include this in the new guide I've added, but if the example code requires we add jitpack to the gradle build, then let's just forget about it.
