### ISSUE TITLE
Documentation error? - Lambda version

### ISSUE THREAD

**Issue by OliverCole** [http4k/http4k#1019]
https://github.com/http4k/http4k/blob/ca200a9acdcb426d856f4e312d70f87cdcb5fdbd/src/docs/guide/tutorials/serverless_http4k_with_aws_lambda/index.md?plain=1#L26

> For this example we're going to use ApiGateway HTTP Version 1

`ApiGatewayV2LambdaFunction` - `This is the main entry point for lambda invocations using the V2 payload format.`

This seems wrong to me?

**Comment by daviddenton** [comment]
Good spot! We updated the code recently but missed the docs. Fixed in 77afc8d81407750a8ff68568f86f3418a696fd43 😄

**Comment by OliverCole** [comment]
👏
