### ISSUE TITLE
RealWorld example app

### ISSUE THREAD

**Issue by elifarley** [http4k/http4k#102]
It would be nice to have an example app with Http4k listed at https://github.com/gothinkster/realworld

**Comment by daviddenton** [comment]
We're already working well in the real world (http4k drives a top-1000 global site) , but will definitely give this a look. :)

**Comment by alisabzevari** [comment]
I am working on the real world example app. The repository sits [here](https://github.com/alisabzevari/kotlin-http4k-realworld-example-app). It would be great if you take a look and make sure it matches the http4k idioms and best practices.

**Comment by daviddenton** [comment]
Cool! Do you want manual comments or should I clone it and PR?

**Comment by alisabzevari** [comment]
PRs from David Denton would be cool in my repository ;)

**Comment by daviddenton** [comment]
Am closing this issue here, as it's in hand. Requests for the RW app can be raised on that repo.

Thanks! :)
