### ISSUE TITLE
Client code works with OkHttp, fails with Java HTTP

### ISSUE THREAD

**Issue by OliverCole** [http4k/http4k#1029]
Not sure if this is even considered a bug given the underlying libraries are different, and it's dependent on an origin server I don't have the code for, but...

```
    val request = Request(Method.POST, "https://...")
        .headers(listOf(
            Pair("Content-MD5",...),
            Pair("Date",...),
            Pair("Authorization",...),
            Pair("Content-Type", "application/json;charset=UTF-8")))
        .body(...);
    val client: HttpHandler = JavaHttpClient(); // OR OkHttp()
    DebuggingFilters.PrintRequestAndResponse().then(client).invoke(request);
```

`JavaHttpClient` will return 403:
`{"timestamp":1704832761110,"status":403,"error":"Forbidden","message":"Date can not be empty","path":"/..."}`

`OkHttp` will return 200 and a useful body.

The `PrintRequestAndResponse` output is identical. So is `println(request.toCurl())`.

**Comment by daviddenton** [comment]
this isn't a bug really, just that the underlying http client libraries setting or not setting the date header automatically on the outbound request. There are variations like this between the various modules - some of which are controllable via config - and we don't intend to try and reach parity between them in this way.

Closing, but thanks for reporting for clarity anyway! 🙃
