### ISSUE TITLE
Add BiDiLensSpec defaulted with factory method

### ISSUE THREAD

**Issue by krissrex** [http4k/http4k#1053]
I would appreciate a `defaulted` which is re-evaluated every time, so I can use e.g. `Instant.now()`, `LocalDate.now()` etc.

I currently do this:

```kotlin
val datetime = Query.localDate(DateTimeFormatter.ISO_LOCAL_DATE)
        .optional(
            "date",
            description = "A date for something"
        )

// Usage
val foo = datetime(req) ?: LocalDate.now(DEFAULT_ZONE)
```

And would appreciate if I could do this:
```kotlin
val datetime = Query.localDate(DateTimeFormatter.ISO_LOCAL_DATE)
        .defaulted(
            "date",
            { LocalDate.now(DEFAULT_ZONE) },
            description = "A date for something"
        )

// Usage
val foo = datetime(req)
```

The name does not need to be `defaulted`, if this collides with existing signatures. Other names could be: ~~`defaultedLazy`~~ (I don't want it lazy, it's active/recompute every time), `defaultFactory`, `defaultedWithFactory`, `defaultedComputed`, `computeDefault`, etc..

---

I tried adding the functionality in my own codebase, but I failed because `paramMeta` was private, and `get` and `set` as well, so extension functions on BiDiLensSpec or inheritance of BiDiLens didn't quickly solve my problem.

**Comment by krissrex** [comment]
Label: feature request

**Comment by dzappold** [comment]
Have you tried to use a `Lens` as second parameter? 
I guess it could look similar to `Lens(myMeta) { _ -> LocalTime.now() }`

**Comment by krissrex** [comment]
> Have you tried to use a `Lens` as second parameter? I guess it could look similar to `Lens(myMeta) { _ -> LocalTime.now() }`

Yes, but I might have done it wrong. I struggled with the constructor, because I couldn't create a `Meta` object.
I looked at the official `defaulted`, which did:

```kotlin
        defaulted(name, Lens(Meta(false, location, paramMeta, name, description)) { default }, description)
```
, but I dont have access to `location` and `paramMeta` when I want to create `myMeta`.

```kotlin
  Query.instant().defaulted("start", Lens(meta = ???, { _ -> Instant.now() }))
```

The source code isn't obvious either, so I have no clue what location and meta are, and if I can construct them myself easily, or what data should even go into them. If you have any advice, I would appreciate it.

**Comment by daviddenton** [comment]
I've made the defaulted mechanism take a LensExtractor `(Request) -> T` and made it a fun interface, so you can now do: ```
    Query.int().defaulted("foo", { 123 })
```

Will be out in the next version
