### ISSUE TITLE
Support gzip on clients by default / clearly describe that it's missing and include in examples

### ISSUE THREAD

**Issue by nikclayton** [http4k/http4k#1068]
I've been experimenting with http4k, and was quite surprised to discover that clients (at least JavaHttpClient) don't support Gzip decoding out of the box.

I understand why that's a reasonable design decision, but given that the docs are described as "based on real, runnable examples that you can just use to get started." (https://www.http4k.org/) I'm surprised that none of them mention that this is omitted by default, or provide an example of how to attach the relevant client filter.

Given the pervasiveness of server-compressed responses please consider either adding Gzip support on clients by default, or amending the basic client as a function doc (https://www.http4k.org/guide/howto/client_as_a_function/) to include examples of enabling common client filters.

Thanks.

**Comment by dzappold** [comment]
Are you looking for an example like that? 
```
     val server = ServerFilters.GZip()
            .then { _ -> Response(OK).body("Hello world") }
            .asServer(Undertow(0))
            .start()

        val client = ClientFilters.SetHostFrom(Uri.of("http://localhost:${server.port()}"))
            .then(ClientFilters.AcceptGZip())
            .then(DebuggingFilters.PrintResponse())
            .then(JavaHttpClient())

        println(client(Request(GET, "localhost")))
```
Using `ClientFilters.AcceptGZip()` is independent of concrete client. Does this solve your question=?

**Comment by nikclayton** [comment]
Something like that in the docs (https://www.http4k.org/guide/reference/clients/ would be another good place to include it) would be great, yes. It would also be helpful if the documentation comments (at least for the `ClientFilters` object) included examples.

In the specific case of Gzip I do think it's worth calling out somewhere that that needs to be explicitly added, as I did find that very surprising.

---

[ This section is feedback about the current API design that I hope is helpful ]

Looking at the example code you provided there (and the code that I wrote) I wonder if the `ClientFilters` terminology is problematic.

When I see "filter" I think "Something that is going to reduce or limit what the code can do", and none of those examples do that. So when I was looking in to how to do this it took a little while to figure that `ClientFilter` was the part of the API surface I needed to look at.

Would the client example be more readable if the API used "builder" and "transform", something like:

```kotlin
val client = ClientBuilder().
    .transformWith(Filters.SetHostFrom(Uri.of("http://localhost:${server.port()}")))
    .transformWith(ClientTransformers.AcceptGZip())
    .transformWith(DebuggingTransformers.PrintResponse())
    .client(JavaHttpClient())
    .build()
```

?

**Comment by dzappold** [comment]
I see, you find some information [here](https://www.http4k.org/guide/reference/core/#filters). 
Using `Filter` (which is `(HttpHandler) -> HttpHandler`) you can use that kind of concerns on each single `HttpHandler` even for in-memory implementations. 
Basically we have there several groups of `Filter`s and to be symmetric for client and server there are `ClientFilters` and `ServerFilters` as some kind of container to easily spot them in the IDE. There are even more specific for requests, responses, logging, monitoring and more.

My example from above as a pure in-memory version could look like this
```
    val httpHandler: HttpHandler = { Response(OK).body("Hello World") }

    val server: HttpHandler = ServerFilters.GZip().then(DebuggingFilters.PrintRequest()).then(httpHandler)

    val client: HttpHandler = DebuggingFilters.PrintResponse(debugStream = true).then(ClientFilters.AcceptGZip()).then(server)

    client(Request(GET, ""))
```

This allows you easily to use same test implementation with different clients or server - so either in-memory or using network.
