### ISSUE TITLE
Route name without a beginning / works for everything except static resources

### ISSUE THREAD

**Issue by ArthurS1** [http4k/http4k#1084]
# Behavior : 

```kotlin
"/static" bind static(Classpath("static"))
```
Responds as expected when requesting "/static/somefile.css", however : 

```kotlin
"static" bind static(Classpath("static"))
```
Responds with a 404

# Expected behavior

I would have expected any route with no beginning `/` to be valid, since the following responds as expected.

```kotlin
"ping" bind Method.GET to InitialiseRequestContext(contexts)
    .then(BearerAuth(credentials, ::checkCredentials))
    .then { Response(Status.OK).body("pong") },
```

http4k version 5.13.8.0

Am I missing something ?

**Comment by s4nchez** [comment]
Hi @ArthurS1 thank you for reporting this. I've had a look and can reproduce it. We'll look for a fix soon, unless you'd like to have a try and submit a PR for it.

**Comment by ArthurS1** [comment]
Hey, I will take care of it if you have not started already.

**Comment by daviddenton** [comment]
Go for it! 🙃

**Comment by daviddenton** [comment]
Fixed in next version :)
