### ISSUE TITLE
http error 431 request header fields too large

### ISSUE THREAD

**Issue by kingsleyh** [http4k/http4k#1114]
Hi

my http4k endpoint is receiving a header with an id token from keycloak which is bigger than the default max http requests size. 

I'm using Jetty.

I believe the default size for Jetty is 8kB 

is there an easy way to increase the size when configuring Jetty as the server?

**Comment by kingsleyh** [comment]
It's intermittent so I think perhaps some issue with keycloak

**Comment by daviddenton** [comment]
You can do this, but not in http4k code - you're going to have to provide your own ServerConfig object with the correct settings for your jetty instance.

We purposefully don't do any custom options for server backends, so am afraid this is a won't fix. 🙃
