### ISSUE TITLE
using apache client GET request fails against F5 due to 'Transfer-Encoding' header specified on request

### ISSUE THREAD

**Issue by simojenki** [http4k/http4k#112]
Sample app demonstrating issue;
https://github.com/simojenki/http4k/blob/apacheclientfix/http4k-client-apache/src/test/kotlin/ApacheFundInfoApp.kt

Basically it comes down to the body mode used in ApacheClient.  When set to 'Memory' GET works, when set to 'Stream' GET fails.  

This is because the apache http client is setting the 'Transfer-Encoding' header when it see's a content length of -1.  http4k specified a content-lenghth of -1 when using the Stream body mode.

Stream -> InputStreamEntity(request.body.stream, request.header("content-length")?.toLong() ?: -1)

The apache class that is causing this is RequestContent, specifically lines 107->115 (httpcore/4.4.7).  It's likely however that the entire if statement lines 88->126 of RequestContent should not be executed at all when performing DELETE, HEAD, GET, OPTIONS, TRACE as the associated apache request classes do not implement HttpEntityEnclosingRequest.

**Comment by daviddenton** [comment]
Fixed in #3.22.0. Thanks @simojenki ! :)
