### ISSUE TITLE
Consider Adopting Adapter for Jakarta Servlet

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#1120]
Http4k has the `HttpHandlerServlet`, which allows an http4k application to become a Java EE 8 `Servlet`, allowing it to be plugged into an existing framework, like Spring.  Java EE 8 is very old, and is not even present in later Java versions.  It was replaced by Jakarta EE `Servlet`, maintained by the Eclipse foundation, and requires a 3rd party library.

Not that I ever make use of this adapter, but is there interest in keeping up-to-date with the latest servlet spec?  Considering how this requires a 3rd party jakarta dependency, this would probably require a new module.

**Comment by daviddenton** [comment]
This already exists in the core 🙃, and Jakarta is brought in as a "provided" dependency. TBH we could probably move the servlets to a custom server module as I doubt most people are actually using it at all.

https://github.com/http4k/http4k/tree/master/http4k-core/src/main/kotlin/org/http4k/servlet/jakarta

**Comment by s4nchez** [comment]
If nothing else, that adapter is super handy if people want to incrementally migrate from Spring to http4k 😉

**Comment by oharaandrew314** [comment]
Ah, I missed that we already have a `Http4kJakartaServletAdapter`!
