### ISSUE TITLE
Incorrect lambda request context 

### ISSUE THREAD

**Issue by SebRamsland** [http4k/http4k#1130]
Hi and thanks for this amazing toolkit! 👏 

I am working on migrating my lambda functions over to use http4k with the `serverless-lambda` module. But I am struggling to retrieve the origin lambda request context. I am currently using a custom lambda authorizer in my HTTP API and I need to be able to retrieve the context/result from the authorizer.

Based on a similar issue (https://github.com/http4k/http4k/issues/832) I tried to retrieve the lambda request context with the `LAMBDA_REQUEST_KEY`. However, the object returned from the context is an instance of `MemoryRequest`, and not the raw/original lambda event as I would expect.

The object returned from `Store<RequestContext>` is identical to the incoming http4k request, except that it also contains header `x-http4k-context-lambda`.

**Version:**
5.24.0.0

**Example:**
```
inline fun <reified T> Store<RequestContext>.lambdaRequestContext(request: Request): T? =
    get(request).get<T>(LAMBDA_REQUEST_KEY)
        ?.also {
            logger.info { "Class: ${it::class}" }
            logger.info { "Request: $request" }
            logger.info { "Lambda request context: $it" }
        }
```
        
**Log output:**
```
INFO: Class: class org.http4k.core.MemoryRequest (Kotlin reflection is not available)
INFO: Request: POST /test-http4k HTTP/1.1
accept: application/json
accept-encoding: gzip
accept-encoding:  deflate
accept-encoding:  br
cache-control: no-cache
content-length: 184
content-type: application/json
host: ***
via: 1.1 ***.cloudfront.net (CloudFront)
x-amz-cf-id: ***
x-amzn-trace-id: ***
x-forwarded-for: ***
x-forwarded-for:  ***
x-forwarded-port: 443
x-forwarded-proto: https

{
   "test": true
}
INFO: Lambda request context: POST /test-http4k HTTP/1.1
accept: application/json
accept-encoding: gzip
accept-encoding:  deflate
accept-encoding:  br
cache-control: no-cache
content-length: 184
content-type: application/json
host: ***
via: 1.1 ***.cloudfront.net (CloudFront)
x-amz-cf-id: ***
x-amzn-trace-id: ***
x-forwarded-for: ***
x-forwarded-for:  ***
x-forwarded-port: 443
x-forwarded-proto: https
x-http4k-context-lambda: a244bc35-6385-469f-ac55-6d967ff270e6

{
   "test": true
}

```

In ApiGatewayFnLoader, the context provided to `AddLambdaContextAndRequest` is a Request object returned from a AwsHttpAdapter. But I would expect the raw content of the InputStream to be provided instead.

<img width="827" alt="http4k-api-gateway-fn-loader" src="https://github.com/http4k/http4k/assets/5295222/4917737d-879c-45d2-8b11-4652943b16b3">

**Comment by daviddenton** [comment]
You need to use LAMBDA_CONTEXT_KEY instead 🙃.

**Comment by SebRamsland** [comment]
LAMBDA_CONTEXT_KEY provides the Lambda context, which does not provide integration specific information, such as the authorizer context from API Gateway.

I need a way to retrieve the raw lambda event/request payload. Essentially the same payload that http4k uses to construct its own Request object.

**Comment by daviddenton** [comment]
hmm - yes - on closer inspection it does seem that we are passing the wrong thing here. Feel free to PR in a fix, although we can't pass in the input stream from the request because that will already have been read by the Moshi unmarshalling into the Map<String, Any> (which then goes into the adapter). It looks like the map would be the best thing to pass in on this occasion.
