### ISSUE TITLE
How to get more specific LensFailure messages?

### ISSUE THREAD

**Issue by elifarley** [http4k/http4k#116]
Situation: I get a `HTTP/1.1 400 body 'body' must be object` response with an empty body after sending a JSON string to an HttpHandler. I think this message is too generic. Ideally, it should be more specific (give more contextual information).
I had to debug to find out the cause of this exception, which was:
```
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "abc"
```

**Comment by daviddenton** [comment]
@elifarley This is a matter for if we want to expose implementation to the outside world - which is why the CatchLensFailure is written the way it is - to not show the stack. We could add an "includeStackTrace" option into the CatchLensFailure, but in the meantime you can implement your own version - or modify it as you'd like and PR it and we'll take a look.

**Comment by elifarley** [comment]
Thanks for the immediate response!
I'm finishing a PR that adds the exception's `simpleName` and `message` attributes.

**Comment by daviddenton** [comment]
@elifarley I've got an even better idea - let's make it function which will create the response body based on the LensFailure. Then people will be able to use it as they see fit. Thoughts?

**Comment by elifarley** [comment]
My first idea (before opening the issue) was to change the `LensFailure` class, as I tried changing the `CatchLensFailure` class but I found out this class receives an instance of `LensFailure` that contains null in its `target` and `cause` fields, instead of the original LensFailure instance.

Which class/classes would you change in your idea ?

**Comment by elifarley** [comment]
The build has finished with an error: `JettyWebsocketTest.errors are propagated to the "on error" handler`:
```
java.lang.AssertionError: expected: a value that is equal to [WsMessage(body=websocket 'message' must be object)]
but was: [WsMessage(body=websocket 'message' must be object (NumberFormatException: For input string: "hello"))]
```

I'll fix this test and send the PR

**Comment by elifarley** [comment]
Hi Dave,

It looks like we have to act earlier in the creation of the LensFailure. Your change doesn't seem to work as I expected, as it simply doesn't have the necessary information (the cause of the exception).

Take a look at this screenshot:
![image](https://user-images.githubusercontent.com/519940/38714914-d23d44f2-3eae-11e8-8bef-899721fe24c4.png)

As you may have alerady noticed, my PR acts at the very beginning of the chain of events of a LensFailure, capturing the originating exception close to where it's thrown.

Let me know what you think.
