### ISSUE TITLE
OpenAPI 3 server schema is incorrect for URL field

### ISSUE THREAD

**Issue by torfinnberset** [http4k/http4k#1167]
Hello, 

thanks for making the http4k project, we are just getting started, but we are appreciating the server-as-a-function design.

There's seemingly an incorrect OpenAPI 3 specification generated for the `servers` field. This is what I am currently getting from http4k-contract:

```json
    "servers": [
        {
            "url": {
                "scheme": "",
                "userInfo": "",
                "host": "",
                "path": "/",
                "query": "",
                "fragment": "",
                "authority": ""
            }
        }
    ],

```

Invoked via 

```kotlin
val renderer = OpenApi3(
            apiInfo = ApiInfo(
                title = "My API",
                version = "version",
                description = "description",
            ),
            json = Jackson
        )
```

This causes the [OpenAPI validator](https://editor.swagger.io) to fail: 

```
Structural error at servers.0.url
should be string
Jump to line <N>
```

If you look to the OpenAPI spec at https://swagger.io/docs/specification/api-host-and-base-path, the url field should be a string, not an object. There is templating available in the spec, but I am not sure if it was the intention to use these features from http4k.

**Comment by daviddenton** [comment]
That looks like the URL is getting serialised incorrectly. The tests in http4k show that it does work ok. Are you using your own instance of the Jackson? If so you should add withStandardMappings() to the kotlin module, as below ``` KotlinModule.Builder().build()
    .asConfigurable()
    .withStandardMappings()
    .let(configFn)
    .done()
    .deactivateDefaultTyping()
    .configure(FAIL_ON_NULL_FOR_PRIMITIVES, true)
    .configure(FAIL_ON_UNKNOWN_PROPERTIES, false)
    .configure(FAIL_ON_IGNORED_PROPERTIES, false)
    .configure(USE_BIG_DECIMAL_FOR_FLOATS, true)
    .configure(USE_BIG_INTEGER_FOR_INTS, true)```

**Comment by torfinnberset** [comment]
Sorry indeed I had my own instance of Jackson. The default module seems to work for the server field, however, the reason I changed it was because it causes a lot of issues with the OpenAPI validator, as every field that is `null` gets explicitly encoded as such, when the spec seems to want to rather omit the field.

This was the serializer I used to remove the `null` warnings, but which caused the problems with the URL:

```kotlin
object OpenApiJsonConfiguration : ConfigurableJackson(
    jacksonObjectMapper().apply {
        setSerializationInclusion(JsonInclude.Include.NON_NULL)
    }
)
```

Here's an example of the errors that occur by not removing the nulls:

<img width="751" alt="image" src="https://github.com/user-attachments/assets/2cf037f7-7e1f-4059-921e-4ea9162a3613">

**Comment by daviddenton** [comment]
That's very strange. The OpenApiJackson instance (which should be the default used has nulls explicitly removed as you've configured it above. 

See the [source](https://github.com/http4k/http4k/blob/ca0d32550caa7bfbbf4d7f305c6c38bd022e2f9c/http4k-contract/openapi/src/main/kotlin/org/http4k/contract/openapi/OpenAPIJackson.kt#L24)

**Comment by torfinnberset** [comment]
Oh indeed it does, I had mistakingly passed `Jackson` as the renderer instead of `OpenAPIJackson`. 

I'm sorry to have bothered you with this, but I really appreciate the quick response and resolution.
