### ISSUE TITLE
MultiPartFormBody reads body into memory even when stream is available

### ISSUE THREAD

**Issue by eriklumme1** [http4k/http4k#1188]
The `MultiPartFormBody.kt` determines the input stream to read as follows:

```
val inputStream = httpMessage.body.run { if (stream.available() > 0) stream else ByteArrayInputStream(payload.array()) }
```

The issue with this line is that `InputStream#available` may be 0 even if the stream has not been read: 

> Returns an estimate of the number of bytes that can be read (or skipped over) from this input stream without blocking, which may be 0, or 0 when end of stream is detected.

At least in the case of the `org.eclipse.jetty.io.content.ContentSourceInputStream`, the method returns 0 also when no chunk of the stream has yet been read into memory.

In this case, because `available()` returns 0, the `MultiPartFormBody` falls back to the `payload` field, which in the case of a `StreamBody` is a lazily initialized field that causes the whole stream to be read into memory.

I am not sure what the correct solution is, in our case calling `request.body.stream.read(ByteArray(0))` worked, drastically reducing the memory requirements of the application.

**Comment by daviddenton** [comment]
We've worked around this with the following function:

```kotlin
fun Body.hasContentToRead() = stream.read(ByteArray(0)) > -1
```

The fix will go into the next release (should be 5.33.0.1).

Thanks for the report. 😄

**Comment by eriklumme1** [comment]
Thank you, much appreciated! 🙂
