### ISSUE TITLE
No equivalent to `ServletRequest.getRemoteAddr()`

### ISSUE THREAD

**Issue by xenomachina** [http4k/http4k#120]
There currently isn't any way to get the "remote address", a la  `ServletRequest.getRemoteAddr()`.

As @daviddenton mentioned on slack, "you need to be a bit generally wary of outside reported IPs as they can get modified by every proxy server that they go through (and not always in a correct way!)". However, they are sometimes useful for debugging.

For example, I was trying to make an http4k `Filter` equivalent to [`AWSXRayServletFilter`](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/javax/servlet/AWSXRayServletFilter.java), and it stores the remote address in the trace segments.

I investigated the existing server implementations, and found that they all have a way of getting this information. I've recorded what I found below, but keep in mind that none of these code snippets are actually tested.

    // Undertow
    InetAddress addr = httpServerExchange.getSourceAddress();

    // Apache
    HttpInetConnection connection =
        (HttpInetConnection) httpContext.getAttribute(ExecutionContext.HTTP_CONNECTION);
    InetAddress addr = connection.getRemoteAddress();

    // Jetty
    InetAddress addr = InetAddress.getByName(httpServletRequest.getRemoteAddr());

    // Netty
    InetAddress addr =
        ((InetSocketAddress) (channelHandlerContext.channel().remoteAddress())).getAddress();

**Comment by kam1sh** [comment]
Hello!

I'm facing the same issue: I have to implement filter that stores source IP address from request and checks it later for login attempts from this IP.

I'll try to file PR soon. I think I can handle that...

**Comment by s4nchez** [comment]
Keeping this open until we have a concrete API in place.
