### ISSUE TITLE
Missing dev.forkhandles:parser4k dependency in http4k-connect-amazon-dynamodb-fake:5.35.0.0

### ISSUE THREAD

**Issue by obecker** [http4k/http4k#1212]
Sorry for spoiling the mood, but the issue https://github.com/http4k/http4k-connect/issues/484 is still (or again?) present when having only `http4k-bom:5.35.0.0` in the project.

Using `http4k-connect-bom:5.26.0.2` works fine.

**Comment by daviddenton** [comment]
lol. how annoying. turns out things are still a little busted.. 🙄

**Comment by daviddenton** [comment]
OK - we've lost some changes that we previously made. Am reapplying them and will release again soon.. Sorry for the hassle
