### ISSUE TITLE
Potential vulnerability report

### ISSUE THREAD

**Issue by JAckLosingHeart** [http4k/http4k#1237]
Hi team, I found a potential high risk vulnerability, could you please open the private vulnerability reporting feature and then I'm able to report it

**Comment by daviddenton** [comment]
Done. Thanks :)

**Comment by JAckLosingHeart** [comment]
Thank you :} report submitted

**Comment by daviddenton** [comment]
Received. We are validating the problem now and will continue through the GitHub security process.

Thank you very much for reporting @JAckLosingHeart  😄

**Comment by daviddenton** [comment]
Closing as tracking through the GitHub  security process

**Comment by daviddenton** [comment]
@JAckLosingHeart We've just released the fixed version of http4k. We're really appreciative of the report and would like to send you a small bounty and award for helping us with our very first CVE! 🙃 

Not having direct access to you, e think the easiest way for us to organise this would be for you to send an email to security@http4k.org . We'll then send you a code to put onto this issue to prove it's really you and then we can organise offline?

**Comment by JAckLosingHeart** [comment]
Hi David @daviddenton, never expected a bounty which's much a surprise for me! I have sent the email and please have a look, Thanks!

**Comment by JAckLosingHeart** [comment]
@daviddenton  c83e507
