### ISSUE TITLE
Headers in Websocket Upgrade request incorrect

### ISSUE THREAD

**Issue by kkopper** [http4k/http4k#124]
For the creation of the upgrade request, the extension function [`Headers.combineToMap()`](https://github.com/http4k/http4k/blob/6a84b41d8cab531e5588b4edb481925cf7fefd9d/http4k-client-websocket/src/main/kotlin/org/http4k/client/WebsocketClient.kt#L104) is created:

````kotlin
private fun Headers.combineToMap() = this.groupBy { it.first }.mapValues { it.value.joinToString(", ") }
````

Since `Headers` is a typealias for a list of pairs of strings, I would expect that the resulting map takes the header fields as keys and maps them to the headers value.

If I create a `Headers` list using the following code snippet
````kotlin
val headers: Headers = listOf(
                "Accept" to "text/html",
                "Origin" to "https://mywebpage.com"
        )
````

the map produced from the above method looks like this:
<img width="570" alt="debugger_map_is" src="https://user-images.githubusercontent.com/18163911/39258917-6c380ece-48b5-11e8-8350-b821fcd72a8d.png">

This is not what I expected. I would expect:
<img width="514" alt="debugger_map_expected" src="https://user-images.githubusercontent.com/18163911/39258985-a1be003a-48b5-11e8-97e6-fd3ba16225d9.png">

The problem in the current implementation seems to be that `it.value` in the `mapValues` block is a list of pairs of strings and not a list of strings.

**Comment by daviddenton** [comment]
Fixed in 3.26.1
