### ISSUE TITLE
Request.form(name) reparses body every invocation?

### ISSUE THREAD

**Issue by dmcg** [http4k/http4k#143]
I've just been reviewing some of my code

```kotlin
Request.toUnsavedCustomer(): Result<UnsavedCegidCustomer> = resultOf {
    UnsavedCegidCustomer(
        salesPersonId = requiredForm("associateId"), // See *
        id = null,
        titleId = form("title").validatedAsTitle(),
        firstName = requiredForm("firstName"),
        lastName = requiredForm("lastName"),
        dateOfBirth = form("dateOfBirth").nullIfBlank().toLocalDate(),
        email = form("email").nullIfBlank(),
        phone = form("phone").nullIfBlank(),
        mobilePhone = form("mobilePhone").nullIfBlank(),
        wechatId = form("wechatId").nullIfBlank(),
        nationalityIso3 = form("nationalityISO3").nullIfBlank(),
        addressLine1 = form("addressLine1").nullIfBlank(),
        addressLine2 = form("addressLine2").nullIfBlank(),
        addressLine3 = form("addressLine3").nullIfBlank(),
        city = form("city").nullIfBlank(),
        regionId = form("regionId").nullIfBlank(),
        countryIso3 = form("countryIso3").nullIfBlank(),
        zipCode = form("zipCode").nullIfBlank(),
        postOptIn = form("postConsent").isChecked(),
        emailOptIn = form("emailConsent").isChecked(),
        phoneOptIn = form("phoneConsent").isChecked(),
        appsOptIn = form("appsConsent").isChecked()
    )

private fun Request.requiredForm(name: String) = form(name).let {
    when {
        it != null && it.isNotBlank() -> it
        else -> error("Missing $name")
    }
}
```

and realise that every one of those Request.form(name) invocations is reparsing the body?

I don't expect HTTP4K to cache the parsed form, but it does seem that the API is encouraging me to do a nasty thing

**Comment by daviddenton** [comment]
Well TBH it's a balance between convenience and simplicity. If you want to avoid the lenses style, in this case you can call request.form() to get a list of parsed fields and then go from there.

We could add a note to the doc (PR it?) - don't really want to deprecate.

Thoughts ?

**Comment by dmcg** [comment]
It's made more difficult by Parameters.findSingle being internal, and as I look at it, every find is a find over a list rather than a map. Does the lenses do a more efficient job?

**Comment by dmcg** [comment]
Thanks Ivan - not a bad compromise I think

**Comment by daviddenton** [comment]
@dcmg Yes - the lenses parse the entire body just once. In addition you get:

-  the further typesafety of being able to map them into domain objects
- automatic 400 generation on non-compliant bodies and content types
- the strict/non-strict validator (with a list of errors generated)

Basically, they're ace.
