### ISSUE TITLE
Some packages on Mavencentral are outdated.

### ISSUE THREAD

**Issue by alisabzevari** [http4k/http4k#146]
Some packages like:
* `http4k-server-jetty`
* `http4k-server-netty`
* `http4k-server-undertow`
* `http4k-server-apache`

obviously are not published in mavenCentral.

All of them are versioned as [3.33](https://www.http4k.org/guide/modules/servers/) but in maven central the versions are [3.32.1](https://search.maven.org/#search%7Cga%7C2%7Chttp4k).

**Comment by daviddenton** [comment]
We're aware of the problems with maven central (which is incredibly slow to sync to and patchy in revealing new versions) - unfortunately it's out of our control.to fix 😞

To mitigate this, we tend to tell people to use jcenter as a repo target as this is much more stable.

We'll.set off another sync, but in the meantime, 3.32.1 is absolutely fine to use... And who knows when 3.33 will make it to published status anyway! 🙃

Thanks for reporting!

**Comment by s4nchez** [comment]
Hi Ali,

Thank you for spotting this.

The jcenter to maven central sync tends to be flaky. I’ll sync them again
tonight (UK time).

Latest packages are always available on jcenter first, so we recommend you
to use that repo if you can.
