### ISSUE TITLE
Maven sync is too flaky. Looking for better solutions to get versions published

### ISSUE THREAD

**Issue by s4nchez** [http4k/http4k#147]
I'll maintain this issue with the various errors we've been getting while trying to publish all modules into maven central.

Here's the latest one (non-recoverable):

`Failed: {"status":"Validation Failed","messages":"[Failed to validate the pgp signature of '/org/http4k/http4k-server-netty/3.33.0/http4k-server-netty-3.33.0-javadoc.jar', check the logs., Failed to validate the pgp signature of '/org/http4k/http4k-server-netty/3.33.0/http4k-server-netty-3.33.0.jar', check the logs., Dropping existing partial staging repository.]"}`

If anyone has a better solution than bintray -> jcenter -> maven (sonatype) publishing, I'm all ears.

**Comment by daviddenton** [comment]
This seems to be much less flaky now, we can reopen if required later.
