### ISSUE TITLE
Documentation Issue: Missing Comma in routes()

### ISSUE THREAD

**Issue by commonsguy** [http4k/http4k#148]
https://www.http4k.org/guide/modules/core/

In the section on routers, you have:

```kotlin
routes(
    "/static" bind static(Classpath("/org/http4k/some/package/name"))
    "/hotreload" bind static(Directory("path/to/static/dir/goes/here"))
)
```

`routes()` takes a `vararg`, so this code is missing a comma between the two parameter values.

**Comment by s4nchez** [comment]
@commonsguy good catch!

It should be fixed now. Thank you!
