### ISSUE TITLE
How to define lenses for serializing to json for response

### ISSUE THREAD

**Issue by alisabzevari** [http4k/http4k#149]
I read the documentation related to [JSON messaging](https://www.http4k.org/cookbook/using_json/) but I couldn't understand how to define a typesafe lens for creating the response. This is what I've expected and tried:

``` kotlin
    val app = routes(
        "/api" bind Method.GET to { _ ->
            val result = LoggedinUserInfo(
                Email("email"),
                Token("token"),
                Username("username"),
                Bio("bio-1"),
                Image("image-1")
            )
            Response(OK).with(
                Body.json().toLens() of result 
            )
        }
    )
```

Apparently, `of` expects a `JsonNode`. Do I have to convert my `result` to a `JsonNode`?

**Comment by daviddenton** [comment]
If you follow the auto marshalling example here it will work as you expect - no need to get a JSONnode involved at all. :)

Let us know if you need more help: https://www.http4k.org/guide/modules/message_formats/

**Comment by alisabzevari** [comment]
Thank you for your instant reply. To document the exact answer, here is how I implemented it using message formats:
``` kotlin
val resLens = Body.auto<LoggedInUserInfo>().toLens()

val app = routes(
    "/api" bind Method.GET to { _ ->
        val result = LoggedInUserInfo(
            Email("email"),
            Token("token"),
            Username("username"),
            Bio("bio-1"),
            Image("image-1")
        )
        resLens.inject(result, Response(OK))
    }
)
```
