### ISSUE TITLE
Stackoverflow http4k tag

### ISSUE THREAD

**Issue by alisabzevari** [http4k/http4k#153]
I've created the http4k tag in stackoverflow.
It would be great if you could review the [definition](https://stackoverflow.com/tags/http4s/info) I've written for it (mostly copying from project documentation) and watch the questions related to it.

**Comment by daviddenton** [comment]
I think you’ve accidentally addressed this to http4k- your link goes to a http4s definition!

**Comment by alisabzevari** [comment]
Sorry! Fixed the link in the issue description.

**Comment by daviddenton** [comment]
There still doesn’t seem to be any description behind that link - which is why I closed this.
