### ISSUE TITLE
Support Applying Lenses to Strings to Build Paths/URLs for Headers

### ISSUE THREAD

**Issue by commonsguy** [http4k/http4k#173]
It's possible that this feature already exists and I am missing it in the docs, but I suspect that it's not there.

We can use lenses to build a URL as part of a `Request`, using `with()`. However, sometimes we need a URL in other places, such as for a `Location` header on a `Response`. It would be nice if we could use lenses to build those as well, for `Path` and `Query` lenses at least.

Possibilities include:
- A `location(url: String, vararg lenses: Lens)` method on `Response` to set the `Location` header
- Adding `vararg lenses: Lens` to `header()`, with the lenses applied to the `value`
- A `withLenses(vararg lenses: Lens)` extension function on `String`

Anyway, just a thought. Thanks for considering this!

**Comment by commonsguy** [comment]
> you're looking to be able to inject path and query values into a Uri?

`header()` on `Response` takes a `String?` value, so I was focusing on the type that I need to pass into that for `Location`. But `Uri` as an intermediate value is fine.

> Something like this (not sure about clashes with the other "with" method

That works. You then wind up with syntax like:

```kotlin
    val uri = Uri.of("/app/public/index").with(userIdQuery of userId, emailQuery of email)

    return Response(Status.FOUND)
        .header("Location", uri.toString())
        .noCache()
```

**Comment by daviddenton** [comment]
Also just noticed that we already have a LOCATION header lens which takes a Uri already!

You can use it with:
```kotlin
Response(TEMPORARY_REDIRECT).with(Header.Common.LOCATION of Uri.of("http://bob.com"))
```

And if you need to add other header types, you can add them as extensions to the Header. Here's an example:
```kotlin
val Header.Common.LOCATION
    get() = Header.map({ of(it) }, Uri::toString).required("location")```


Also please PR them if you think it would make sense. :)

Closing this now as it seems to be resolved.
