### ISSUE TITLE
In-memory request context store should be thread-safe?

### ISSUE THREAD

**Issue by zvozin** [http4k/http4k#177]
https://github.com/http4k/http4k/blob/3170cc58d0bd50e777cb21a101639e678ca300a1/http4k-core/src/main/kotlin/org/http4k/core/RequestContexts.kt#L11 - that's a `LinkedHashMap<A, B>` in what appears to be a multi-thread-access situation. Would a `ConcurrentHashMap<A, B>` be more suitable?

Asking cause https://github.com/http4k/http4k/blob/3170cc58d0bd50e777cb21a101639e678ca300a1/http4k-core/src/main/kotlin/org/http4k/core/RequestContext.kt#L9 makes `id` internal, which makes rolling your own impossible.

**Comment by daviddenton** [comment]
Sounds reasonable - if you want to fix and PR those 2 changes then that's be great! Definitely want people to be able to implement their own store.

**Comment by zvozin** [comment]
https://github.com/http4k/http4k/pull/178

**Comment by daviddenton** [comment]
Fixed by #178
