### ISSUE TITLE
How do I register additional Jackson modules?

### ISSUE THREAD

**Issue by dkowis** [http4k/http4k#183]
Specifically, I'd like to register the [Java8 DateTime](https://github.com/FasterXML/jackson-modules-java8) module so that it will understand the date format that doesn't match the one in the custom section :(

I'm operating in the client, when making a request using http4k.

**Comment by daviddenton** [comment]
You want to create your own custom Jackson object by extending Configurable Jackson. 

Take a look at: https://github.com/http4k/http4k/blob/master/http4k-format-jackson/src/main/kotlin/org/http4k/format/Jackson.kt

🙃

**Comment by dkowis** [comment]
If I just do an override object (Can I even do that?) then it'll work just fine? How do I make sure that http4k picks up the `MyExtendedConfigurableJackson` class and uses that?

**Comment by daviddenton** [comment]
One more thing. When you have created that module, you'll need to import the correct Extension functions from your new object when creating your JSON objects and lenses, instead of just the standard Jackson entries.

**Comment by daviddenton** [comment]
You won't be able to override the values in the original Jackson instance - it will still be on the classpath. But creating a new one will also allow IDEA to see the extension functions as well
