### ISSUE TITLE
Kotlin Native Support

### ISSUE THREAD

**Issue by napperley** [http4k/http4k#186]
Have the Http4k team considered providing a Kotlin Native port of Http4k (the "**server**" part)? Would make sense to do this since not all devices have ample resources (eg Raspberry Pi). Using a VM would be prohibitive from a performance point of view in a typical IoT device, which could be a show stopper in using Kotlin to handle a specialised back-end in a IoT device (very likely to be ARM CPU based; Kotlin Native already supports some of the ARM CPU architectures, and is known to work on a Raspberry Pi 2/Beaglebone Black). IoT development is a emerging area for [Kotlin adoption](https://www.jetbrains.com/research/devecosystem-2018/kotlin/) at 22% (in behind Machine Learning at 25%).

Already there are plans by some competitors to provide a [Kotlin Native version](https://blog.jetbrains.com/kotlin/2018/07/kotlinnative-v0-8-released/#comment-45780) of their server-side lib/framework. If Http4k were to be ported to Kotlin Native then one of the following approaches could be taken:

- Use [microhttpd](https://www.gnu.org/software/libmicrohttpd/) as a web server; The Kotlin Conf app has its own [Server](https://github.com/JetBrains/kotlinconf-spinner/blob/master/kotlin-native/samples/fullstack/httpserver/src/main/kotlin/server/HttpServer.kt) which uses microhttpd
- Directly use the POSIX APIs via sockets, and utilise Kotlin Coroutines for concurrency; See the Kotlin Native Non Blocking Echo [Server sample](https://github.com/JetBrains/kotlin-native/blob/master/samples/nonBlockingEchoServer/src/main/kotlin/EchoServer.kt)
- Develop a [module](http://httpd.apache.org/docs/2.4/developer/modguide.html) that uses the Apache Web Server as a base

**Comment by s4nchez** [comment]
Hi @napperley ,

Yes, we have considered, but it turns out it's not just a case of integrating with a new server library, I'm afraid.

There are a few bits that would need rework to break the dependency into JDK-specific classes (eg. `InputStream` and `LocalDateTime`). That means redesigning `Body`, for instance.

Having said that, we're happy to take contributions on that area. This issue is a great start because it touches on some things to consider in order to get this done.

I'm also curious: do you have a specific use case for this capability?

**Comment by daviddenton** [comment]
At KC18, we did bring this up with the JB crew. There were some noises made with regards to providing a standardised IO wrapper API for Kotlin which would help massively. Date and times though are another mountain range entirely.. 😀

**Comment by napperley** [comment]
@s4nchez - I don't have a specific use case in mind, apart from having a light weight alternative of the current implementation for resource constrained devices as mentioned in the first comment.

Dates and times are a area of software development which is nearly as difficult to get right as concurrency. Would make sense to have a official Kotlin multi-platform date/time lib provided by JB rather than having multiple libs provided by the Kotlin community.

**Comment by s4nchez** [comment]
I’m closing this for now. Happy to revisit once the native libraries get a bit more mature, or we find a compelling case to add more 3rd party dependencies

**Comment by martinbonnin** [comment]
Would be nice for serverless use cases where starting native binaries is typically faster than starting a JVM. These days, both [Okio](https://github.com/square/okio) and [kotlinx.datetime](https://github.com/Kotlin/kotlinx-datetime) are multiplatform so maybe it'd be doable?

**Comment by daviddenton** [comment]
If you're looking for native serverless, http4k already supports GraalVM compilation out of the box. You can find a guide on how to make this work for a simple lambda [here](https://www.http4k.org/guide/tutorials/going_native_with_graal_on_aws_lambda/)
