### ISSUE TITLE
Form parameters not generating correct swagger.json

### ISSUE THREAD

**Issue by reik-wargaming** [http4k/http4k#197]
When using a form parameter as in [ContractRendererContract.kt](https://github.com/http4k/http4k/blob/master/http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt) the generated swagger.json contains the following element:

          {
            "in": "form",
            "name": "form",
            "required": true,
            "type": "integer",
            "description": "description of the form"
          }

The OpenApi 2.0 spec however, [defines form parameters](https://swagger.io/docs/specification/2-0/describing-parameters/#form-parameters) with `"in": "formData"`. 

The issue I am seeing, in the UI the form elements are not properly posted when hitting the `Try it Out` button.

**Comment by daviddenton** [comment]
Fixed in 3.102.1
