### ISSUE TITLE
`org.http4k.core.Body.length` is not nullable

### ISSUE THREAD

**Issue by zvozin** [http4k/http4k#201]
Is there a good reason I can't see that %subj% does the unKotlin thing where it throws for `StreamBody` rather than be nullable? If not, I have a PR for y'all to look at.

**Comment by daviddenton** [comment]
It's a good question! It it a breaking change, so we'll have to be careful with it (and think about why that might be a bad idea), but please send it over and we'll take a look. 

But not today. 😉

**Comment by zvozin** [comment]
https://github.com/http4k/http4k/pull/202. Take your time :).

**Comment by s4nchez** [comment]
Fixed by #202
