### ISSUE TITLE
Field constraints / OpenAPI

### ISSUE THREAD

**Issue by tobad357** [http4k/http4k#210]
I’m wondering if there currently is a way to add constraints to fields via Lenses or another recommended way. 

Example
Field1  is int with max value 100 and min value 10

It would be great if this was reflected in the Generated openapi as well

**Comment by daviddenton** [comment]
Closing for now unless there's reason to keep it open. For future reference, there is good level of support available on the Kotlin-lang slack #http4k channel.  :)
