### ISSUE TITLE
Include Request in LensFailure

### ISSUE THREAD

**Issue by commonsguy** [http4k/http4k#215]
I am using the `failResponseFn` for `CatchLensFailure` to log lens failures and redirect to a page with a custom error message.

I would like to be able to include more details in my logs about the request that failed, such as the URL and its query parameters. However, `LensFailure` does not seem to have the `Request` object that triggered the failure, and I don't see anything else in `LensFailure` that would contain that sort of information.

It would be cool if you could consider tucking the `Request` into the `LensFailure` or otherwise supplying it to the `failResponseFn`.

Thanks for considering this!

**Comment by daviddenton** [comment]
There is already a field "target" which contains a reference to the request. 

🙃

**Comment by commonsguy** [comment]
The value of `target` is `null`. I have:

```kotlin
    val catchLens = ServerFilters.CatchLensFailure {
        logger.error { "LENS-FAILURE ${it.failures.joinToString(";")} ${it.target} ${it.cause}" }
        // other stuff here that returns a Response
    }
```

and I get:

```
LENS-FAILURE query 'search' is required null null
```

**Comment by daviddenton** [comment]
Looks like we don't always set the target when we throw a lensfailure. Reopening. :)

**Comment by daviddenton** [comment]
will be released in 3.113.0

**Comment by daviddenton** [comment]
@commonsguy we've not released this if you want to try it. :)

**Comment by commonsguy** [comment]
It works! Many thanks!
