### ISSUE TITLE
Routes catchall option

### ISSUE THREAD

**Issue by godspeed20** [http4k/http4k#223]
In trying to add a catch all using the http4k routing but am struggling. From what I can see, aggregate routing http handler had the catch all already, in the form of the not found handler Param, but the ability to set that is not exposed (at least from what I can see, maybe I'm missing a component). Is there any chance of adding an additional method to routing.kt to pass in my own not found catch all handler please?

**Comment by godspeed20** [comment]
Thanks Denton. I'll have a play in the meantime but I think the catchall via the routes will be a lot cleaner, at least for what I'm after

**Comment by daviddenton** [comment]
with the updated routing API this is now trivial: 

```kotlin
fun main() {
    val app = routes(
        "/hello" bind GET to { req: Request -> Response(Status.OK) },
        { r: Request -> true }.asRouter() bind { req: Request -> Response(Status.OK).body("foobar") },
//        Fallback bind { req: Request -> Response(Status.OK).body("foobar") } <-- will be in next release
    )
    println(app(Request(GET, "/hello")))
    println(app(Request(GET, "/")))
}

```

Closing this now - I've added the Fallback above to the next release.
