### ISSUE TITLE
Support additionalProperties (map types) in `http4k-contract`

### ISSUE THREAD

**Issue by noahbetzen-wk** [http4k/http4k#228]
Currently when the contract/OpenAPI/Swagger renderer finds a type of `Map<String, T>` it produces the Swagger JSON below:

<img width="1074" alt="Screen Shot 2019-04-24 at 7 24 47 PM" src="https://user-images.githubusercontent.com/31736963/56701947-2104d280-66c7-11e9-8944-6c8cfe6cad51.png">

Both Swagger 2 and OpenAPI 3 support the concept of `additionalProperties`, as documented here: https://swagger.io/docs/specification/data-models/dictionaries/

For any type definition of the form `Map<String, T>` where T is a primitive type, Swagger supports something like

```
schema:
    type: "object"
    additionalProperties:
        type: "string"
```

In the above case, this object schema would represent a `Map<String, String>` object (the key being of type `String` is forced by the specification).

Example from the Swagger petstore in the Swagger editor: https://editor.swagger.io/

<img width="1117" alt="Screen Shot 2019-04-24 at 7 07 06 PM" src="https://user-images.githubusercontent.com/31736963/56702081-d20b6d00-66c7-11e9-9e95-c02c0bd5aa67.png">

This entire issue is partially invalidated by the fact that not even `swagger-ui` has the ability to render these properly, which you can read more about in https://github.com/swagger-api/swagger-ui/issues/1248.

<img width="971" alt="Screen Shot 2019-04-24 at 7 40 16 PM" src="https://user-images.githubusercontent.com/31736963/56702285-d1270b00-66c8-11e9-8e68-881a371eaecd.png">

Nevertheless, the ability to have `http4k-contract` generate valid `Map<String, T>` types in Swagger JSON would be extremely useful.

**Comment by daviddenton** [comment]
Fixed (at least partially) in 3.146.0
