### ISSUE TITLE
Reuse RequestContextKey Lens with other types of Store

### ISSUE THREAD

**Issue by amcghie** [http4k/http4k#241]
`http4k` currently supports rolling-you-own `Store` implementation, however the functions in the `RequestContextKey` lens are tightly coupled to the `RequestContexts` implementation.  Perhaps it would be more flexible if they accepted `Store<RequestContext>` as a parameter?

**Comment by daviddenton** [comment]
Good spot! We'll change that now.

**Comment by daviddenton** [comment]
Until this is released, you can use a custom extension method which does take the store (use the current version of the RequestContextKey code for reference) :)

**Comment by amcghie** [comment]
Thanks for the quick merge!  That's what I'd originally done - then thought why not just contribute a fix!

**Comment by daviddenton** [comment]
Fixed in 3.143.1
