### ISSUE TITLE
Documentation: Move examples from dependencies { compile } to dependencies { implementation }?

### ISSUE THREAD

**Issue by ivoanjo** [http4k/http4k#250]
Hello there, and a big thanks for http4k!

I was bootstrapping a new project, and saw that the project documentation still recommends using `dependencies { compile ... }` to import http4k as a dependency, whereas the [gradle documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) now mentions that

> The `compile` configuration still exists but should not be used as it will not offer the guarantees that the `api` and `implementation` configurations provide.

[This](https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle) stackoverflow link is also relevant.

Would you accept a PR to update the documentation to use `implementation` instead? I don't mind tackling it, but wanted to know if there may be a reason for still wanting to have the old syntax :)

**Comment by s4nchez** [comment]
I’m not aware of any good reason to keep the old syntax. A PR to change would be welcome 🙂

**Comment by daviddenton** [comment]
@ivoanjo thanks very much for this - it's  great to stay on top of the tech, and just something that we haven't got some to.

One thing though - I think we should be consistent across the project, so we should also be looking at converting our project gradle files to the new format as well.

It doesn't have to be this PR or issue, so maybe let's raise another one to cover it?  (although if you wanted to do it as part of your PR then that'd be amazing 😉).

**Comment by ivoanjo** [comment]
@daviddenton sure, I can take a stab at it!

I usually favor smaller PRs, but I can add to that one if you prefer :)

**Comment by daviddenton** [comment]
Whichever you'd like to do would be absolutely brilliant. 🙃
