### ISSUE TITLE
Documentation: Unexpected behavior in "Hello World" example

### ISSUE THREAD

**Issue by ivoanjo** [http4k/http4k#251]
Hello 👋!

While experimenting with the path routing and the ["hello world" example](https://github.com/http4k/http4k/blob/master/src/docs/cookbook/readme/example.kt) that is shown on `www.http4k.org` I ran into a behavior that for me was unexpected.

Specifically, two endpoints are defined on that example:

```kotlin
    val app: HttpHandler = routes(
        "/ping" bind GET to { _: Request -> Response(OK).body("pong!") },
        "/greet/{name}" bind GET to { req: Request ->
            val path: String? = req.path("name")
            Response(OK).body("hello ${path ?: "anon!"}")
        }
    )
```

And upon seeing

```kotlin
            val path: String? = req.path("name")
            Response(OK).body("hello ${path ?: "anon!"}")
```

I expected that I could have

```
GET /greet/name -> hello name
GET /greet/ -> hello anon!
```

But there seems to be no way to actually get the `anon!` version.

Doing this does not work (gets 404):

```kotlin
    // call the handler in-memory without spinning up a server
    val inMemoryResponse: Response = app(Request(GET, "/greet/"))
    println(inMemoryResponse)

    // call the handler in-memory without spinning up a server
    val inMemoryResponse2: Response = app(Request(GET, "/greet"))
    println(inMemoryResponse2)
```

and also this does not work (again 404):

```kotlin
    val networkResponse: Response = client(Request(GET, "http://localhost:9000/greet/"))
    println(networkResponse)

    val networkResponse2: Response = client(Request(GET, "http://localhost:9000/greet"))
    println(networkResponse2)
```

Also neither `/greet?foo=bar` nor `/greet/?foo=bar` trigger it.

So my question is: Should the example be updated to something like

```kotlin
            val path: String = req.path("name")!!
            Response(OK).body("hello $path")
```

or am I missing some way of actually getting a `null` path parameter in the example?

Thanks in advance!

**Comment by s4nchez** [comment]
Hi @ivoanjo,

You're correct. That particular routing (`"/greet/{name}"`) will only match if a name is present. I've update the example following your suggestion.

The only way to get a `null' match on that case would be by declaring two routes:

```kotlin
    val greeting = { req: Request ->
        val path: String? = req.path("name")
        Response(OK).body("hello ${path ?: "anon!"}")
    }

    val app: HttpHandler = routes(
        "/greet/{name}" bind GET to greeting,
        "/greet" bind GET to greeting
    )

    val inMemoryResponse: Response = app(Request(GET, "/greet"))
    println(inMemoryResponse)
```

Thank you for such a well written report. I hope it clear things up, otherwise please feel free to reopen this.

**Comment by ivoanjo** [comment]
Awesome speedy fix, thanks! Have a great week!
