### ISSUE TITLE
Expose the AWS Lambda context to the handlers

### ISSUE THREAD

**Issue by lambrospetrou** [http4k/http4k#287]
Hello, I am trying to use the [Http4k serverless](https://www.http4k.org/guide/modules/serverless/) feature for some of my Lambda functions, but I need to get access to the [`AWS Lambda Java Context object`](https://docs.aws.amazon.com/lambda/latest/dg/java-context-object.html).

Based on the [Java Lambda function handler docs](https://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html) just having a second argument to the Lambda function entrypoint is enough to give you the context.

However, the [Lambda function `handle`](https://github.com/http4k/http4k/blob/master/http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/lambda/LambdaFunction.kt#L19) method does not receive the context so essentially it gets lost and I cannot access it from inside my handlers.

I thought of several approaches on getting access to the context so I would like to see if it's possible to get something that can be merged into the project so that others can use it as well, or at least you can tell me if I am missing something that would make it easier for me.

### Approach 1

Create a new `LambdaFunctionWithContext` class which is the entry point to my lambdas and it essentially looks something like:

```
import org.http4k.serverless.lambda.LambdaFunction

class LambdaFunctionLambdaFunctionWithContext(env: Map<String, String> = System.getenv()) {
    fun handle(request: ApiGatewayProxyRequest, context: com.amazonaws.services.lambda.runtime.Context) = {
        GlobalSingleton.set(context)
        LambdaFunction(env).handle(request)
    }
}
```

And from inside my handlers I can do `GlobalSingleton.get()` and retrieve the function context. However, I don't like having global state in my code so I would treat this as a last-way approach, but it is the easiest (and has no concurrency issues due to Lambda's execution model)!

### Approach 2

Fork the [`LambdaFunction`](https://github.com/http4k/http4k/blob/master/http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/lambda/LambdaFunction.kt) class into a `LambdaFunctionWithContext` and instead of creating a [`Request`](https://github.com/http4k/http4k/blob/5a3dcde40dec1e71ec583c8738532b2bdc9eb574/http4k-core/src/main/kotlin/org/http4k/core/http.kt#L209-L213) object it will create a class `RequestWithContext` that implements `Request` but also contains the AWS Lambda Context and allows the handlers to cast the received `Request` into `RequestWithContext` and extract the context they need.

The downside of this is that basically I stop using your `LambdaFunction` and any improvement you make on it won't be applicable to my lambda functions since I am using a fork copy of it.

### Approach 3

At first when I saw the [`Request Contexts`](https://www.http4k.org/cookbook/request_context/) I thought that it's something that each request handler could use to receive implicit context but it seems that it's not the case and the contexts need to be explicitly given to the handlers.

Is there any way that I missed where the `RequestContexts` can be used and make what I want to achieve above easier than the two approaches described?

If there is an approach that can be merged back into the package I am happy to contribute it, but I think deciding the best approach is the first step towards that.

Thanks a lot for any tips or hints.

**Comment by daviddenton** [comment]
The SDK context interface seem to be available through this maven repo:
https://mvnrepository.com/artifact/com.amazonaws/aws-lambda-java-core

Am happy to rely on this dependency for our lambda module as it's very light (7k) and has no deps of it's own.

For the interface, I think that the RequestContexts is probably the way to go for this - we'd need to modify the AppLoader interface to also take the RequestContexts, and also to define a RequestContextKey in the lambda module which is generified to the Context type - that will give us the most flexibility if we want to also support other runtimes (OpenFAAS etc).

Thoughts?

**Comment by lambrospetrou** [comment]
I believe I understand the approach you suggest and I don't see any potential problem, but I have some missing spots if you can enlighten me. Just to make sure we are on the same page.

## Changes needed

**AppLoader**

The [`AppLoader` interface](https://github.com/http4k/http4k/blob/master/http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/AppLoader.kt) will need to include `RequestContexts` as in:

```
interface AppLoader : (RequestContexts, Map<String, String>) -> HttpHandler
```

**BootstrapAppLoader**

The [`BootstrapAppLoader`](https://github.com/http4k/http4k/blob/master/http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/BootstrapAppLoader.kt) will need to now instantiate a `val contexts = RequestContexts()` and pass it down to the loaded `AppLoader`.

```
...
val contexts = RequestContexts()
(loadClass.getDeclaredField("INSTANCE").get(null) as AppLoader)(contexts, environment)
...
```

**AWSLambdaContext**

Inside the [serverless lambda package](https://github.com/http4k/http4k/tree/master/http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/lambda) we need to create a new class to be passed to `RequestContextsKey` lens, something like:

```
// Put the fields as defined by https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/Context.java
data class AwsLambdaContext(...)
```

**Lambda Function**

Update the [`LambdaFunction`](https://github.com/http4k/http4k/blob/master/http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/lambda/LambdaFunction.kt) to be something like:

```
class LambdaFunction(env: Map<String, String> = System.getenv()) {
    private val app = BootstrapAppLoader(env)

    fun handle(request: ApiGatewayProxyRequest, context: com.amazonaws.services.lambda.runtime.Context) = {

        // Now we need to update `contexts` with an instantiation of the `AWSLambdaContext` data class by transforming the input `context` into that.
       // ??? How do we update the `contexts` here? 

        // The app now receives the `contexts` as well
        app(request.asHttp4k()).asApiGateway()
    }
}
```

**User defined handlers**

Now the user will be able to get the contexts from inside the handlers with something like:

```
class PostXHandler(getContext: RequestContextsKey) {
     invoke(request: Request): Response = {
         val lambdaContext = getContext(request)

         // EXECUTE MY HANDLER CODE
     }
}

class MainHandler(
    contexts: RequestsContexts
) : HttpHandler {
    private val app: HttpHandler
    privtae val getContext: RequestContextKey

    init {
       // 
       getContext = RequestContextKey.required<AwsLambdaContext>(contexts)
        // Handlers
        val postXHandler = PostXHandler(contexts)

        val router = routes(
            "/some/path-to-my-api" bind POST to postXHandler
        )

        app = DefaultFilterStack.forLambdaService().then(router)
    }

    override fun invoke(request: Request): Response = app.invoke(request)
}

object LambdaService : AppLoader {
    override fun invoke(contexts: RequestContexts, env: Map<String, String>): HttpHandler = MainHandler(contexts)
}
```

Did I miss something?
