### ISSUE TITLE
WebDriver does not send textarea values on submit

### ISSUE THREAD

**Issue by quii** [http4k/http4k#29]
When you try and test a form with textarea elements the values are not sent through. 

From https://github.com/http4k/http4k/blob/master/http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt#L45

` val textareas = it.findElements(By.tagName("input"))`

This looks naughty

**Comment by daviddenton** [comment]
Fixed in 2.19.0
