### ISSUE TITLE
Provide structured logging format for DebuggingFilters.*

### ISSUE THREAD

**Issue by KushalP** [http4k/http4k#292]
Structured logging is useful for a [number of reasons](https://stackify.com/what-is-structured-logging-and-why-developers-need-it/). It makes it easier to parse logs using a tool that understands either `key=value` or `json` structures.

Allow configuring the output format for easier integration with tools like [Stackdriver](https://cloud.google.com/logging/docs/structured-logging).

**Comment by daviddenton** [comment]
This is the kind of thing I was going for. Basically we introduce an `EventsFilter` which will allow you to add metadata to an `Event` and finally log it in structured format using an implementation of `Events` which converts the class structure to JSON and dumps it to std out.

Check it out and let me know if you think it would work for you..
https://github.com/http4k/http4k/tree/events

**Comment by KushalP** [comment]
This looks like a good start. It might be useful to understand how you would pass this single (or multiple?) events around as it's hitting different filters and the route in question. Would you `+` multiple events together?

At what point would you serialise them with `slf4j` ?

**Comment by daviddenton** [comment]
Generally, each events instance represents a single "Sink", so for example you'd have one for StandardOut, one for NewRelic, and one for Prometheus metrics, then you can `+` them together into a single "stream" and then use programmatic Filters on each one to determine if you want to consume each Event.

We don't really have much use for logging frameworks like SL4J - most of our stuff fits into the buckets above - in K8S the StandardOut stuff just uses `::println` which is then picked up by FluentD and sent to an aggregator (ELK or Splunk). Of course, there's nothing to stop you implementing one but TBH we find that the very presence of a Logging framework makes people want to vomit random strings instead of structured events. :)

**Comment by KushalP** [comment]
That's interesting because I had issues using http4k by itself without adding slf4j as a dependency. I think I used one of the contract API examples.

This was a grade build error that would appear. I'll try to reproduce it tomorrow when I'm back in the office.

**Comment by daviddenton** [comment]
The main for library doesn't have any dependencies other than kotlin. There may be a transitive dependency on sl4j from some of the modules (you can see it moaning about not being able to find a logger implementation in the travis output from the build) but it shouldn't stop anything building.

**Comment by daviddenton** [comment]
So definitely let us know if you're having trouble. 🙃

**Comment by KushalP** [comment]
I've just checked and the slf4j issue I'm seeing is related to Spek. It has nothing to do with http4k 🤦‍♂ 

My apologies!

**Comment by daviddenton** [comment]
NP. See - this is why we stay away from logging frameworks 😉 

Anyway - I've now merged these event change branch into master and am releasing as a part of 3.181.0

**Comment by KushalP** [comment]
Excellent. Thank you. It would be useful to document the expected usage of the `EventsFilter` stuff you've written as well.

**Comment by daviddenton** [comment]
I'll get around to documenting it soon. I'll keep this issue open as a reminder.

**Comment by daviddenton** [comment]
It's not required. In the EventsFilter you can just attach more and more metadata to the event (using `Event + Pair<String, Any>` and then this all gets collated and dumped out as one. Check out the EventFilter implementations for an example before I add the docs.

**Comment by KushalP** [comment]
Maybe I'm misunderstanding how this would be wired up? A standard handler takes the form of `HttpHandler = (Request) -> Response`, and a `Filter` conforms to this interface with `interface Filter : (HttpHandler) -> HttpHandler`. So I'm not sure how an `EventsFilter` would work when it has `EventsFilter : (Events) -> Events`.

In my head when I think of "wiring" I mean the following:

```kotlin
ServerFilters.InitialiseRequestContext(contexts)
            .then(MetricFilters.Server.RequestCounter(registry))
            .then(MetricFilters.Server.RequestTimer(registry))
            .then(ServerFilters.CatchLensFailure())
            .then(ServerFilters.GZip())
            .then(myCustomerOpenApiRoutesHere)
```

**Comment by daviddenton** [comment]
They are entirely different stacks. Have a look at this Gist which shows the 2 things being used together: https://gist.github.com/daviddenton/2c09ecf11fce518083da3667dd1ab0cb

**Comment by daviddenton** [comment]
Finally gotten around to documenting the Events stuff in a cookbook page [here](https://www.http4k.org/cookbook/structured_logging_with_events/), so am going to close this.
