### ISSUE TITLE
Question regarding conditional filters

### ISSUE THREAD

**Issue by elizabetht** [http4k/http4k#295]
I am new to using http4k, so correct me if my understanding is wrong. I am seeing samples on how to use two filters one after another from the tests. 
Is there a way a filter can be used within another filter? Say for example, I want to use BasicAuth filter only for a particular uri path. From what I tried, once I am in the closure of applying conditions on my request within my filter, I can no longer call another filter within my filter object. Is my understanding correct?

**Comment by s4nchez** [comment]
Hi @elizabetht ,

Filters are normally independent, and composable using `.then()` function. Here's an example of how to add BasicAuth only for a particular uri path:

```kotlin
import org.http4k.core.Method.GET
import org.http4k.filter.ServerFilters
import org.http4k.routing.bind
import org.http4k.routing.routes

val myHandler: HttpHandler = { request -> Response(Status.OK).body(request.uri.toString()) }
val app = routes(
    "/public" bind GET to myHandler,
    "/private" bind GET to ServerFilters.BasicAuth("app", "user", "password")
        .then(myHandler)
)
```

As you can see, the `Filter` has no knowledge about the path, as it shouldn't be its concern in this case.

I hope that helps. If you rather try a different approach, please post an example and we'll try our best to assist.

Also, if you post questions to the #http4k channel on the [Kotlin slack](http://slack.kotlinlang.org/), you'll probably get a quicker response and the help from more people from the community :)

**Comment by elizabetht** [comment]
Makes very much sense @s4nchez. Thank you very much for the quick response.
