### ISSUE TITLE
Feature request: provide ability to change response status

### ISSUE THREAD

**Issue by brandon-atkinson** [http4k/http4k#300]
I'm using http4k to write an http proxy, and I have a use case where I need to modify a downstream response status before handing it up to the original requestor. I have implemented this in my application, but the thought occurred to me that might be valuable in the framework. 

`fun Response.status(code: Int): Response`

Is this something the maintainers feel like considering? If so, I could submit a PR with my implementation.

**Comment by daviddenton** [comment]
Happy to add this if our users would find it useful! Looks like it would be a 2 line fix + test, so feel free to PR it if we can pick it up.

**Comment by daviddenton** [comment]
Have made these changes and added them to the 3.190.0 release. Thanks for the suggestion @brandon-atkinson  😄
