### ISSUE TITLE
ApacheClient cannot close SSL/TLS checking

### ISSUE THREAD

**Issue by fgoinai** [http4k/http4k#33]
For ApacheClient, I cannot find a position that I can override the cert checking method or even just simply stop checking.

Is OkHttp Client can achieve this?

**Comment by daviddenton** [comment]
For both Apache and OkHttp clients, you can just pass a (Native lib) client to the constructor, configured as you wish- by default it uses a preconfigured default. See: https://github.com/http4k/http4k/blob/master/http4k-client-apache/src/main/kotlin/org/http4k/client/ApacheClient.kt

**Comment by fgoinai** [comment]
Thx a lot! The problem solved now!

**Comment by daviddenton** [comment]
@fgoinaiif you've got any API queries, you can try the gitter http4k channel :)
