### ISSUE TITLE
Access AuthedUser in Request

### ISSUE THREAD

**Issue by Ray-Eldath** [http4k/http4k#342]
The tutorial I can find told me that define `security` property for `contract`, you can enable `BearerAuthorization` for your endpoint: 
```kotlin
val http: HttpHandler = contract {
    renderer = OpenApi3(ApiInfo("my secure api", "v1.0", "API description"), Jackson)
    descriptionPath = "/api/swagger.json"
    routes += basicRoute
    security = BearerAuthSecurity({ bearer: String -> bearer.startsWith("123") })
}
```
but I find that `BearerAuthSecurity` accept a `String -> Boolean`, and so the authorization is only rely on the truth of the boolean. Seems there's no way, like use a `bearer: String -> E?` or `bearer: String -> Either[E, FailedOperation]` to determine the authorization and *let user access the `E` while defining `HttpHandler`* (by `it.authedUser: E?`...? I'm not quite sure about the best design from your perspective). I think it's a very useful feature because the authorization of `http4s` and `Ktor` seems done so.

---

BTW if the feature have been implemented in `http4k`, please ignore this... And if not, I think I can help implement this after the design is confirmed.

**Comment by daviddenton** [comment]
You'd do this with a request context. There is an example of using one at https://www.http4k.org/cookbook/principal_lookup/

It's not directly using the contract module, but the idea is the same. This will allow you to access the user further into the stack.

Closing this off, but please reopen/comment if you still have trouble.. :)

**Comment by Ray-Eldath** [comment]
**Thanks a lot! This definitely helps!**

But then I met another problem... how to combine a non-secured route and a secured together? I tried this:

```kotlin
val globalRenderer = OpenApi3(ApiInfo("my secure api", "v1.0", "API description"), Jackson)
val descPath = "/swagger.json"

val http: HttpHandler =
    "/api/v1" bind routes(
        contract {
            renderer = globalRenderer
            descriptionPath = descPath
            routes += openRoute
        },
        contract {
            renderer = globalRenderer
            descriptionPath = descPath
            routes += authedRoute
            security = object : Security {
                override val filter: Filter = security
            }
        }
    )
```
It works fine. The route could work under the authorization config accordingly. But the problem is the OpenAPI document is incomplete, seems only the first `contract` will be contained in `/api/v1/swagger.json`

Sorry for the question again, I googled but no result. And I'm just the only one who are using http4k among the people I know...

Many thanks.

**Comment by daviddenton** [comment]
You should use a single contract, but can then set the security up on a route by route basis (there is an option in the DSL for it)

**Comment by Ray-Eldath** [comment]
Uh... where is the API...? I'm confused... sorry.

Currently I'm using `http4k-contract 3.217.0`.

**Comment by daviddenton** [comment]
Np :)

You can set the security instance onto each individual endpoint or the API as a whole. Like so...

```
routes += "/ping" meta {
            summary = "add"
            description = "Adds 2 numbers together"
            returning(OK to "The result")
        } bindContract GET to { Response(OK).body("pong") }
```

Setting the security on an individual endpoint also overrides the "contract level" security, so if you just want an open endpoint you can use an instance of `NoSecurity` to achieve this.

**Comment by Ray-Eldath** [comment]
Thanks!!!!!!! Works now.

So kind of you for the fast reply as well as the detailed explanation! Thanks again!
