### ISSUE TITLE
Streamed Gzip handler fails in cases where the reader produces larger compressed output than the input

### ISSUE THREAD

**Issue by jshiell** [http4k/http4k#344]
There's a bug in the GZippingInputstream where data is lost in cases where the deflated data waiting to be written is greater than the request's read buffer - once the buffer is full then we lose the extra data. This causes corrupt output, obviously.

I'm working on this, again mostly to avoid people hitting the same issue. This has taken me most of the day to find, mind, so the fix won't land until tomorrow.

**Comment by daviddenton** [comment]
Thanks for letting us know. 🙃
