### ISSUE TITLE
okhttp client tags and interceptors

### ISSUE THREAD

**Issue by dtanner** [http4k/http4k#348]
First time using the client library...I'm planning on using okhttp as the client engine. I have some existing okhttp interceptors that rely on [tags](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-request/-builder/tag/) to pass around the metadata. 

I don't see a way to get a Tag into an okhttp request though...**is that currently feasible?**  

The alternative seems to be to rewrite my okhttp interceptors as http4k filters, using RequestContexts to pass around metadata to filters.  Thoughts? Thanks.

**Comment by daviddenton** [comment]
Yep - we don't expose the underlying client APIs through the main HttpHandler interface, so your thoughts on attaching metadata is correct - using RequestContexts would be appropriate here, then just inject the request context keys into the stack which builds your underlying client. :)
