### ISSUE TITLE
Cannot globally turn off Moshi's failOnUnknown

### ISSUE THREAD

**Issue by cnusp** [http4k/http4k#353]
There are several JSON objects with superfluous fields I parse using `Body.auto`, but I cannot turn off `failOnUnknown` globally because it is set by the private function `ConfigurableMoshi.adapterFor` which I cannot override.

Version: 3.219.0

**Comment by daviddenton** [comment]
Hmm - that shouldn't be on by default. We want the default behaviour to be non-strict.

We'll fix the strictness for the default immediatey and also look at making it configurable next.

**Comment by daviddenton** [comment]
Fixed in 3.220.0
