### ISSUE TITLE
Jackson wrapper produces strange JSON string when handling Exception

### ISSUE THREAD

**Issue by Ray-Eldath** [http4k/http4k#361]
MRE:
```kotlin
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import org.http4k.format.Jackson

class ApiException(override val message: String) : Exception(message)

val obj = ApiException("123")

val jacksonWrapper: String = Jackson.asJsonString(obj)
println(jacksonWrapper)

val jackson: String = jacksonObjectMapper().writeValueAsString(obj)
println(jackson)
```
will produce:

![Snipaste_2020-01-27_15-03-03](https://user-images.githubusercontent.com/7938763/73155595-24c1fb80-4116-11ea-8aff-20a4263d3f20.jpg)

in which the `wrapper` produces just a JSON string, in an application connects to the API and assume all reply are JSON object may causes problem. the `jacksonObjectMapper` from package `com.fasterxml.jackson.module.kotlin.jacksonObjectMapper` will produce the well-organized JSON object string.

this will affect `Body.auto<...>(...) of obj` as well.

**Comment by fintara** [comment]
This seems to be connected with [BiDiMapping.kt#L88](https://github.com/http4k/http4k/blob/ce39c0d9a21cfa425380017b86fd3e3e6988dc1b/http4k-core/src/main/kotlin/org/http4k/lens/BiDiMapping.kt#L88) and [AutoMappingConfiguration.kt#L83](https://github.com/http4k/http4k/blob/ce39c0d9a21cfa425380017b86fd3e3e6988dc1b/http4k-core/src/main/kotlin/org/http4k/format/AutoMappingConfiguration.kt#L83)

**Comment by daviddenton** [comment]
Yes. It's totally to do with that line of code. The thing is that the AutoMappingConfiguration is for when we are treating various types as primitives - so just as a bare number or boolean isn't JSON, throwable also is treated in the same way - ie. we would never expect for these to be top level JSON structures but to be handled as fields.

**Comment by Ray-Eldath** [comment]
yeah, after talking to david d in slack channel i do understand the reason why it's designed to work in this way. i checked the code seems no workaround here.

well, maybe at least this should be documented somewhere... top level exception should be serialize through native jackson api instead of let http4k process it directly.

**Comment by daviddenton** [comment]
I've made a note in the docs for the suggested point about primitives, so I'm going to close this now. :)

https://www.http4k.org/cookbook/custom_json_marshallers/
