### ISSUE TITLE
Jetty, websockets and UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by fintara** [http4k/http4k#362]
In [this code](https://github.com/fintara/http4k-lateinit/blob/master/src/main/kotlin/Main.kt#L18) references to websocket connections are kept and all are informed when a new user joins (same as in [this example](https://github.com/daviddenton/http4k-demo-irc/blob/master/src/main/kotlin/org/http4k/demo/IrcApp.kt)).
When many connections are opened and closed in short time, at some point `Http4kWebSocketListener::onClose` and `::onError` are unable to use `websocket`:

```
2020-01-27 10:30:55.912:WARN:oejwc.WebSocketSession:qtp1761061602-46: Exception while notifying onClose
kotlin.UninitializedPropertyAccessException: lateinit property websocket has not been initialized
	at org.http4k.server.Http4kWebSocketListener.onWebSocketClose(Http4kWebSocketListener.kt:36)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onClose(JettyListenerEventDriver.java:119)
	at org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(WebSocketSession.java:389)
...
```
and similar for onError:
```
2020-01-27 10:40:50.079:WARN:oejwc.WebSocketSession:qtp1761061602-16: Exception while notifying onError
kotlin.UninitializedPropertyAccessException: lateinit property websocket has not been initialized
...
```

If I wrap this line in try/catch, there's exception from Jetty: `java.lang.IllegalStateException: Blocking message pending 10000 for BLOCKING`, but this is for another issue.

I believe this happens when a connection is dropped and the forEach loop is still running and/or exceptions are not handled properly.
You can run the code in this repo https://github.com/fintara/http4k-lateinit/ and simulate many connections with `npx artillery run load.yml` (or connect via javascript and hold Refresh).

Would a possible fix be to make `websocket` nullable instead of lateinit?

**Comment by daviddenton** [comment]
Thanks for raising this and investigating. Searching for the error "Blocking message pending 10000 for BLOCKING" seems to throw up several results for to Jetty, so I'm not sure if it's related (or even the best way to solve it if so). Am a bit concerned that making the field nullable would hide an error that we should be handling.

**Comment by fintara** [comment]
Here's another repro, where message is send from different threads:

```kotlin
val ws = "/ws" bind { ws: Websocket ->
    for (i in 1..2) {
        thread { ws.send(WsMessage(i.toString()) }
    }
}
ws.asServer(Jetty(8080)).start()
```

this fails with "Blocking message pending 10000 for BLOCKING", but if I change `sendString` to `sendStringByFuture` [here](https://github.com/http4k/http4k/blob/a6d72a3ddce6a788d22a885eeebf4fc7a90c0979/http4k-server-jetty/src/main/kotlin/org/http4k/server/Http4kWebSocketListener.kt#L44), it doesn't fail.

The test with many connections/disconnections however fails with:

```
2020-01-29 10:57:52.701:WARN:oejwcec.CompressExtension:qtp1509514333-16: 
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:109)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:582)
...
```
which is probably expected? It doesn't go through `onWebSocketError` though.

Anyway, with the original code, Jetty's `onWebSocketError` is called before `onWebSocketConnect` which looks like a problem with Jetty itself.

**Comment by daviddenton** [comment]
I've made the reference nullable and changed the code to use the future call (even though it calls .get() - which seems weirdly to consistently make the failures reduce in number). Will release in 3.230.1
