### ISSUE TITLE
gradlew -q clean build : 3 Unresolved reference: readAllBytes

### ISSUE THREAD

**Issue by GustaveNimant** [http4k/http4k#381]
I git clone  https://github.com/http4k/http4k.git
then i run : gradlew -q clean build 
this gives :

e: ~/http4k/http4k-testing-servirtium/src/test/kotlin/org/http4k/servirtium/FakeGitHub.kt: (27, 68): Unresolved reference: readAllBytes
e: ~/http4k/http4k-testing-servirtium/src/test/kotlin/org/http4k/traffic/TrafficExtensionTests.kt: (70, 84): Unresolved reference: readAllBytes
e: ~/http4k/http4k-testing-servirtium/src/test/kotlin/org/http4k/traffic/TrafficExtensionTests.kt: (88, 90): Unresolved reference: readAllBytes

I modified readAllBytes in readBytes then compilation went Ok.

**Comment by daviddenton** [comment]
That method was only introduced in Java 9. Were you running Java 8 on the command line purposefully?

**Comment by daviddenton** [comment]
... regardless, I've tweaked it to use `readBytes()` so we maintain compatibility there. If you pull in changes from upstream it should work now. :)
