### ISSUE TITLE
gradlew -q clean build :  Cannot access class 'org.apache.http.impl.client.CloseableHttpClient'

### ISSUE THREAD

**Issue by GustaveNimant** [http4k/http4k#383]
I git clone https://github.com/http4k/http4k.git
then i run : gradlew -q clean build
this gives :
e: ~/http4k/http4k-testing-servirtium/src/main/kotlin/org/http4k/servirtium/ServirtiumServer.kt: (56, 40): Cannot access class 'org.apache.http.impl.client.CloseableHttpClient'. Check your module classpath for missing or conflicting dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':http4k-testing-servirtium:compileKotlin'.
> Compilation error. See log for more details

**Comment by daviddenton** [comment]
From that error, looks like your gradle has not downloaded the Apache client dependency which servirtium is (now) reliant on. 

Is there another gradle installation on your classpath? You should be running `./gradlew -q clean check` to pick up the gradle version which ships with the library. The travis and shippable CI builds both run this on a clean checkout so we can be assured that it works ok (as well as locally).

Some questions which might help you to diagnose why this is failing on your machine:
1. Which version of Java are you using? We build with Java 11. 
2. Which OS are you using? We build on OSX (Mojave) and the automated CI is Linux (Ubuntu 16.04.6 LTS)

**Comment by GustaveNimant** [comment]
I build Java with sdk 19.3.0.2.r8-grl 
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b07)
OpenJDK 64-Bit GraalVM CE 19.3.0.2 (build 25.232-b07-jvmci-19.3-b06, mixed mode)

My Os is Debian 9.12 
uname -a
Linux iabloko 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

I am not familiar with Java world. What sdk command should I run to get the correct Java version ?

**Comment by daviddenton** [comment]
as well as Java 8 being EOL for.commerical use (Dec for public), Graal now supports java 11, so you can upgrade your SDK to that version using whatever tooling is available.

I am not sure if this will fix your problem (as it seems to be gradle specific), but it will rule out one potential source of error.

**Comment by GustaveNimant** [comment]
I upgraded sdk 
Now I run 
Java  : AdoptOpenJDK 11.0.6.hs-adpt 
Gradle : 6.2.2 
Kotlin : 1.3.70
gradlew -q clean build gives a new error :
* Where:
Build file '/home/achadde/sources/http4k/build.gradle' line: 24

* What went wrong:
An exception occurred applying plugin request [id: 'net.saliman.cobertura', version: '3.0.0']
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task ':generateCoberturaReport'.
      > Could not create task of type 'GenerateReportTask'.
         > No signature of method: static org.gradle.util.DeprecationLogger.whileDisabled() is applicable for argument types: (net.saliman.gradle.plugin.cobertura.GenerateReportTask$1) values: [net.saliman.gradle.plugin.cobertura.GenerateReportTask$1@74c74a9e]

**Comment by daviddenton** [comment]
The cobetura plugin is not compatible with Gradle 6.2.2. We bundle 6.1.1 with the project.

As noted above you need to run the gradlew command with the leading ./ so it picks up the local version

**Comment by GustaveNimant** [comment]
I set gradle to 6.1.1 (sdk use gradle 6.1.1)
I set java to 11 (sdk use  java 11.0.6.hs-adpt)
I set kotlin to 1.3.70 
I run ./gradlew -q clean build which still gives :
FAILURE: Build failed with an exception.

* Where:
Build file '/home/achadde/sources/http4k/build.gradle' line: 24

* What went wrong:
An exception occurred applying plugin request [id: 'net.saliman.cobertura', version: '3.0.0']
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task ':generateCoberturaReport'.
      > Could not create task of type 'GenerateReportTask'.
         > No signature of method: static org.gradle.util.DeprecationLogger.whileDisabled() is applicable for argument types: (net.saliman.gradle.plugin.cobertura.GenerateReportTask$1) values: [net.saliman.gradle.plugin.cobertura.GenerateReportTask$1@356ea9a3]

What did I miss ?
