### ISSUE TITLE
 Unresolved reference: OkHttp

### ISSUE THREAD

**Issue by GustaveNimant** [http4k/http4k#384]
My setup 
gradle 6.1.1
kotlin 1.3.70
okhttpVersion 4.4.0
java 11.0.6.hs-adpt
http4kVersion 3.239.0

in build.gradle.kts 
implementation("com.squareup.okhttp3:okhttp:${extra["okhttpVersion"]}")
implementation("org.http4k:http4k-core:${extra["http4kVersion"]}")
implementation("org.http4k:http4k-server-jetty:${extra["http4kVersion"]}")
implementation("org.http4k:http4k-client-apache:${extra["http4kVersion"]}"

In the main I implemented the code from https://github.com/http4k/http4k/blob/master/src/docs/cookbook/readme/example.kt
./gradlew -q clean build  gives the error : Unresolved reference: OkHttp

What is wrong with my build.gradle.kts ?

**Comment by daviddenton-teal** [comment]
In order to make this work you need to import the `http4k-client-okhttp` module instead of the `http4k-client-apache` one. You can also drop this `implementation("com.squareup.okhttp3:okhttp:${extra["okhttpVersion"]}")`

**Comment by GustaveNimant** [comment]
Which version of http4k-client-okhttp ?

**Comment by daviddenton-teal** [comment]
http4kVersion

**Comment by daviddenton-teal** [comment]
@GustaveNimant for more immediate support - could you join the #http4k channel on the Kotlinlang slack? You can find the link on the website. :)

**Comment by GustaveNimant** [comment]
I am there
