### ISSUE TITLE
StringBiDiMapping for Enums

### ISSUE THREAD

**Issue by goodhoko** [http4k/http4k#392]
Hello,
in my app I was trying to define a lens that parses an Enum out of a request query but to my surprise I couldn't find a corresponding method on the `Query` object. Is there a canonical way to extract Enums out of Queries in Http4k?

In the ended I solved it by introducing an extension
```kotlin
// helper for deserialization of Enums
inline fun <reified T : Enum<T>> Query.enum() =
        map(BiDiMapping<String, T>(::enumValueOf, Enum<T>::name ))
```
which can be used as
```kotlin
val languageQuery = Query.enum<Language>().required("language", "two letter ISO 639-1 lower-case language code")
```

I'd be happy to submit a PR with similar extension but maybe with `<IN : Any> BiDiLensSpec<IN, String>` as a reciever instead of `Query`.

**Comment by daviddenton** [comment]
Good spot! Yes - it does look like we are missing that. If you raise that PR and also add the same case  to the Path (path.kt) mappings as well that would be great. :)
