### ISSUE TITLE
Running in Google Cloud Functions

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#396]
http4k is currently able to natively run in AWS Lambda as described here: https://www.http4k.org/guide/modules/serverless/

Google Cloudfunctions now support running Java (in beta):

https://github.com/GoogleCloudPlatform/kotlin-samples/tree/master/functions

This should allow us to run http4k there as well. As far as I can read the example, it probably won't be easy to fit the API with http4k:

https://github.com/GoogleCloudPlatform/kotlin-samples/blob/master/functions/src/main/kotlin/HttpExample.kt

Are you aware of these and are you planning to support GCF?

**Comment by daviddenton** [comment]
We already support the servlet API out of the box in the core module, so this should be trivial to add as a custom `Http4k-serverless-googlecloudfunctions` module. No plans as yet to add it ourselves,  but if you fancy adding the module and PRing it then that would be amazing! 🙃

**Comment by ssijak** [comment]
I have implemented an adapter for cloud functions here https://github.com/http4k/http4k/pull/429

**Comment by daviddenton** [comment]
Closing this as is now in the core app. Will be released in 3.249.0
