### ISSUE TITLE
`with` is incompatible between 3.235 and 3.245

### ISSUE THREAD

**Issue by dkandalov** [http4k/http4k#408]
In 3.235 the code was:
```
fun <T> T.with(vararg modifiers: (T) -> T): T = modifiers.fold(this) { memo, next -> next(memo) }
```
In 3.245 it changed to:
```
fun <T : HttpMessage> T.with(vararg modifiers: (T) -> T): T = modifiers.fold(this) { memo, next -> next(memo) }
fun WebForm.with(vararg modifiers: (WebForm) -> WebForm) = modifiers.fold(this) { memo, next -> next(memo) }
```

So it causes compilation errors for the code below:
```
OkHttp().with(SetBaseUriFrom(Uri.of("http://localhost:1234")))
handler.with(FollowRedirects())

Error: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun WebForm.with(vararg modifiers: (WebForm) -> WebForm): WebForm defined in org.http4k.core
```

**Comment by daviddenton** [comment]
This is expected. We removed the generic with method on purpose to avoid abuse of extending Any. Check the changelog: https://www.http4k.org/changelog/

:)

**Comment by dkandalov** [comment]
Ah, ok. Just didn't expect a compilation error from a "minor" version change (although I'm probably projecting the meaning of a version from somewhere else :))

**Comment by daviddenton** [comment]
That's a fair point - we do try to deprecate rather than remove on the whole. 

This did seem like a bit more of a niche break, which is why we were more comfortable to proceed with it.
