### ISSUE TITLE
Server with Ktor-CIO engine cannot be effectively closed

### ISSUE THREAD

**Issue by carranca** [http4k/http4k#410]
# Description
Calling `stop()` on a Ktor-CIO backed server does not close the server engine.
This seems to be because in https://github.com/http4k/http4k/blob/master/http4k-server-ktorcio/src/main/kotlin/org/http4k/server/KtorCIO.kt#L42-L44 we're calling [stopServerOnCancellation](https://api.ktor.io/1.3.0/io.ktor.server.engine/stop-server-on-cancellation.html), the Deferred returned by which according to the Ktor docs must be completed or cancelled.

# Scenario
```
val handler = { _: Request -> println("Hello!") }
val server = handler.asServer(KtorCIO(9000))

server.start()
// Sending a request to the server will print "Hello"
server.stop()
// Sending a request to the server will still print "Hello"
```

# Proposed solution
Replacing `stopServerOnCancellation()` with `stop(1, 1, TimeUnit.SECONDS)` or another reasonable or configurable timeout and grace period. Looking at #206 I noticed this exact solution was introduced in ef2620db6e93ec50ff335ae06e36112397fecd52 but removed in 7dc7198ef3ca288674090b3ce67ee635d4d89871

Happy to submit PR if maintainers agree with proposed solution. I've verified locally with my project that it works.

**Comment by daviddenton** [comment]
I've implemented this change. Releasing now in 3.245.1 :)
