### ISSUE TITLE
Default ServerConfig implementations do not shut down gracefully

### ISSUE THREAD

**Issue by daviddenton** [http4k/http4k#427]
At the moment, several of the server backends will terminate in-progress connections instead of shutting down gracefully. Wherever possible, we should make the default to do a graceful shutdown - this might not be available given the underlying server APIs available in each.

Need to write a test in `ServerContract` and handle each backend in turn to see if we can make it pass.

**Comment by nlochschmidt** [comment]
I think we are seeing this with the SunHttp server when using http4k with OpenFaaS. 

@daviddenton you seem to think that there are backends that already do graceful shutdown? Do you happen to know which ones?

**Comment by daviddenton** [comment]
undertow has a graceful shutdown handler that you can use. we should really put that into the default config.

also, beware startup time - sunhttp is especially good for this.

I'd also like to submit an official template for http4k on openfaas but haven't got around to it.

**Comment by daviddenton** [comment]
I was actually surprised that openfaas uses the sun server. it's not really meant for prod use AFAIK... we have had concurrency issues with it in the past. not sure what the openfaas lifecycle model.is or if it routes multiple requests to a single instance at once.

**Comment by nlochschmidt** [comment]
OpenFaaS is not using it, it's just that we are :wink:. We had an exchange around that on Twitter and @alexellis mentioned that he's using the same one for the Java templates

https://twitter.com/http4k/status/1161552909051604992?s=20

**Comment by nlochschmidt** [comment]
I don't want to take this off-topic so: 

As far as I understand it the Sun HttpServer allows us to specify a timeout on `stop` in seconds, however it is [currently hardcoded to `0`]( https://github.com/http4k/http4k/blob/master/http4k-core/src/main/kotlin/org/http4k/server/SunHttp.kt#L32). Would the idea be to have a new method e.g. `gracefulStop(timeout: Duration)` or just `stop(timeout: Duration)` and adapt that to each server implementation? Or would you rather see this as part of the server configuration?

**Comment by daviddenton** [comment]
I'd ideally like to see all of the server's do graceful shutdown by default (unless it makes them slow to stop if there are no requests). Each of the ServerConfigs should not take any extra config (to make things simple), but also be structured in a way that people can implement their own versions with minimum effort - eg. reusing the Servlet in the Jetty, or the handler in Undertow.

**Comment by nlochschmidt** [comment]
Ok so I looked a bit into this and would like to provide a PR. The main issue I am currently facing is that most of the implementations are using non-daemon threads and therefore even if `fun main()` completes, the JVM won't shutdown. A notable exception here is KtorCIO, while KtorNetty behaves like the rest. That is the reason why this actually work with all server implementations except KtorCIO.

```
fun main() {
    { request: Request -> Response(OK).body(request.body) }.asServer(SunHttp(8000)).start()
}
```

So I think it makes sense to make `stop()` always be graceful shutdown, but this will also requires to actually call stop() on Signal TERM and afaik the only way to do this to use a JVM shutdown hook.

Doing this externally means the example above becomes a bit more complicated and developers need to remember to do this for a graceful shutdown to actually occur.

```
fun main() {
    val app = { request: Request -> Response(OK).body(request.body) }
    val server = app.asServer(SunHttp(8000)).start()
    getRuntime().addShutdownHook(thread(start = false) { server.stop() }
}
```

The alternative to this is to register the shutdown hook in each of the servers `start()` methods making graceful shutdown a real. 

As a sidenote, just testing that `stop()` shuts down the server gracefully is quite easy to test and I have a version almost ready, however to test that the server behaves correctly on JVM shutdown would require spawning JVMs in the test for each server and sending a TERM signal to them, while requests are inflight. Definitely possible, but quite a bit more difficult to setup.

What do you think?

**Comment by nlochschmidt** [comment]
@daviddenton I've done a preliminary pull request to make `stop()` block until inflight requests are handled. I've chosen 10 seconds as the default graceful shutdown timeout, but the shutdown will occur as soon as the request is handled.
This works for small responses but I haven't checked for streaming and for really large responses where sending the response takes a long time.
