### ISSUE TITLE
Support OpenApi servers

### ISSUE THREAD

**Issue by goodhoko** [http4k/http4k#433]
The [OpenApi specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#openapi-object) allows top-level `servers` object to be specified:

> Field Name | Type | Description
> ---|:---:|---
> <a name="oasServers"></a>servers | [[Server Object](#serverObject)] | An array of Server Objects, which provide connectivity information to a target server. If the `servers` property is not provided, or is an empty array, the default value would be a [Server Object](#serverObject) with a [url](#serverUrl) value of `/`.

As far as I can see we currently cannot control it with http4k.

**Comment by goodhoko** [comment]
I can open a PR with a feature where user could supply the servers object when instantiating the contract. Something along the lines of:

```kotlin
contract {
        renderer = OpenApi3(ApiInfo("GoOut Locations API", "1.0"), Jackson)
        descriptionPath = "/swagger.json"
        servers += Server("dev.acme.com", "Development server")
        routes += ...
    }
```

Let me know if that's desired.

**Comment by daviddenton** [comment]
Yep - this is not currently cup porter s happy to take a PR to add it, but please make sure to add the default as in the spec if nothing is provided.

**Comment by s4nchez** [comment]
Closing this off as has been implemented in https://github.com/http4k/http4k/pull/674
