### ISSUE TITLE
kotlin linting

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#436]
Hi, when implementing https://github.com/http4k/http4k/pull/435 I noticed the codebase does not have a linter set up - e.g. some files end with new lines and some don't. 

I am not sure whether this is desired, I would be happy to participate if wanted.

**Comment by nlochschmidt** [comment]
I noticed this as well. At least there is an .editorconfig that can be used in IntelliJ to automatically add newlines on save. That said, [ktlint](https://ktlint.github.io/) is what I typically use in my projects and I have made mostly good experiences with it.

**Comment by daviddenton** [comment]
We've used ktlint before on projects. IMO, it's definitely more important on bigger projects where there is a lot of activity, but can get annoying if you've got "all warnings are errors" switched on (see below), which would seem to be the obvious mode.

In truth, we've just never got around to actually putting linting in. I'm happy enough to get it PR'd into the project  as long as it doesn't slow down the build a bunch and we can remove the "error on unused variable" warning - that setting is insanely annoying if you're in the middle of developing and want to run something with one arg unused for any reason. 😢

**Comment by goodhoko** [comment]
I guess this was resolved with https://github.com/http4k/http4k/pull/576. ,)

**Comment by daviddenton** [comment]
Agreed. We can reopen this if we need to! :)
