### ISSUE TITLE
Use different routes for different query parameters

### ISSUE THREAD

**Issue by mattbroekhuis** [http4k/http4k#438]
I am using the `http4k-contract` module. I would like to have routes like this that return two different responses based on a query parameter. I cannot seem to achieve it. Is there a way to do it?

```/api/v1/thing?view=list ```
```/api/v1/thing?view=detail ```

**Comment by daviddenton** [comment]
You can't do this with http4k - and besides it is not supported in OpenApi as endpoints are keys by the path and then by the method.

If you want to implement something like this, you can just provide a filter or an HttpHandler which splits the traffic and calls down into 2 separate HttpHandler implementations..
