### ISSUE TITLE
Documenting http post request body

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#455]
I am following this code:

https://github.com/http4k/http4k/blob/master/http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt

```kotlin
                receiving(Body.webForm(Strict,
                    FormField.boolean().required("b", "booleanField"),
                    FormField.int().optional("i", "intField"),
                    FormField.string().optional("s", "stringField"),
                    json.lens(FormField).required("j", "jsonField")
                ).toLens())
```

I would like to use this part to document form field of Apple login response:

```kotlin
                receiving(Body.webForm(Strict,
                    FormField.string().required("code", "stringField"),
                    FormField.string().required("user", "jsonField:" + AppleUserInfo(AppleUserInfoFirstAndLast("Jane", "Doe"), "jane@doe.net"))
                ).toLens())
```

This is not ideal as I pass the JSON example as String, without Lens support. However I couldn't figure out how to do this correctly.

**Comment by daviddenton** [comment]
The good news is that this is supported already. There is an extension function on `Json` that you will need to import (eg. `org.http4k.format.Jackson.json`) to give you typesafe access to the form field.

Closing this now, but please reopen if you still have trouble.

😄

**Comment by knyttl** [comment]
Thanks for quick reply – I think I got stuck with that already yesterday:

```kotlin
FormField.json().required("user")
```

I am still not sure how to pass the type parameter for the documentation.

**Comment by knyttl** [comment]
@daviddenton Unfortunately it seems I don't have a right to reopen the issue.

**Comment by daviddenton** [comment]
whilst the schema descriptions are supported by OA3 for all.types of parameter, unfortunately there currently isn't a way to add Json examples for non-body parameters . we only support the basic Json primitives (string/Boolean etc) for these parts (query/form.fields etc)

**Comment by knyttl** [comment]
Thanks. In such case we can close this.
