### ISSUE TITLE
OpenAPI requires fields to be not-nullable

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#458]
Consider a endpoint response data class with nullable boolean:

```kotlin
   data class A {
        val visible: Boolean? = null
   }
```

when OpenApi is generated for example with this field (eg. `A(null)`) set to be null, it throws this exception:

https://gist.github.com/knyttl/dc181d4a6789e63f34bee9f5df3af201

This seems to be caused by this:

```kotlin
interface FieldRetrieval : (Any, String) -> Field {
    companion object {
        fun compose(vararg retrieval: FieldRetrieval) = object : FieldRetrieval {
            override fun invoke(target: Any, name: String): Field =
                retrieval.asSequence().mapNotNull {
                    try {
                        it(target, name)
                    } catch (e: NoFieldFound) {
                        null
                    }
                }.firstOrNull() ?: throw NoFieldFound(name, target)
        }
    }
}
```

Mainly this field: `?: throw NoFieldFound(name, target)`

Is this desired or I am doing something wrong?

**Comment by daviddenton** [comment]
yep - that is by design. the reason that we require that is so that the full model can be generated from the example.

**Comment by knyttl** [comment]
But why would you forbid a null field? If a field is unknown, it is correct to return null value.

**Comment by daviddenton** [comment]
The intent of how the code is written is to provide a full schema model of the JSON messages. If there are null fields then this cannot be created. It is definitely a compromise that was made, and as the schema only supports a single version of each object then we don't really have a choice.

This limitation can be got around by providing using a different object for the various scenarios if you want, or you can compose your own set of `FieldRetrieval` objects to remove `SimpleLookup`. If you dig in, you'll see that the default set used is:

```
fun AutoJsonToJsonSchema(json: Jackson) = AutoJsonToJsonSchema(json, FieldRetrieval.compose(SimpleLookup(),
    FieldRetrieval.compose(JacksonJsonPropertyAnnotated, JacksonJsonNamingAnnotated(json))))
```

You will somehow have to still contend with the fact that the interface can't return a null `Field`.

**Comment by knyttl** [comment]
Thanks!
