### ISSUE TITLE
Improve the defaults of SunHttp server

### ISSUE THREAD

**Issue by nlochschmidt** [http4k/http4k#465]
While working on #462 I noticed that the SunHttp server has very naive settings. I do realize that you might not want developers to actually use that server in production and instead opt to keep it as it is, but maybe at least some of what I would propose still makes sense:

- Turn the private extension functions `HttpExchange.populate(...)` and `HttpExchange.toRequest()` into a public `SunHttpRequestHandler` to make them reusable for customised SunHttp instances
- Set a default backlog for the ServerSocket (e.g. `1000` as in ApacheServer, Undertow and Netty)
- Set an executor service to allow parallel request handling (e.g. based on available processors as in Undertow and Netty)

What do you think?

**Comment by daviddenton** [comment]
You're right - as per comments on #462, we want all of the servers to be user-configurable with the maximum amount of reuse available, so that people don't have to reinvent the wheel. Happy to take a PR on this, or to have it worked into #462. 😄

**Comment by nlochschmidt** [comment]
I think, this would be something nice to do first and then build #462 on top.
