### ISSUE TITLE
AWS Lambda Serverless throws httpMethod must not be null

### ISSUE THREAD

**Issue by kalaiselvan369** [http4k/http4k#468]
I followed this example:

```
object TweetEchoLambda : AppLoader {
    override fun invoke(env: Map<String, String>): HttpHandler = {
        Response(OK).body(it.bodyString().take(20))
    }
}

```
Only this code snippet I used, then uploaded as jar + update environment variables and org.http4k.serverless.LambdaFunction::handle in lambda console. I couldn't figure it out where is the issue.

```
{
  "errorMessage": "httpMethod must not be null",
  "errorType": "java.lang.IllegalStateException",
  "stackTrace": [
    "org.http4k.serverless.LambdaFunctionKt.asHttp4k(LambdaFunction.kt:43)",
    "org.http4k.serverless.LambdaFunction.handle(LambdaFunction.kt:32)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)"
  ]
}
```

**Comment by s4nchez** [comment]
@kalaiselvan369 how are you invoking the function?

**Comment by kalaiselvan369** [comment]
@s4nchez I upload as jar in AWS Lambda console and tried using Test lambda function available in the console and even with API Gateway. Both throws the same error.

**Comment by daviddenton** [comment]
How did you build your Jar file? did you use gradle to build.an uber/shadow jar? 

if there any way that you could share the codebase or or the Jar file?

**Comment by s4nchez** [comment]
@kalaiselvan369 may I suggest you try invoking the function directly in the command line or via Kotlin using the [`LambdaHttpClient` from http4k ](https://github.com/http4k/http4k/blob/3dd9907891cb1787a7c239bb99cbb8fc7e7f4557/http4k-serverless-lambda/integration-test/src/test/kotlin/org/http4k/serverless/lambda/client/LambdaHttpClientTest.kt#L18)?

I suspect that the console version is using an unsupported [version of the message payload](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html). Have you tried with both?

**Comment by kalaiselvan369** [comment]
@daviddenton Here is the repository https://github.com/kalaiselvan369/Http4kSamples I am using for testing.

**Comment by kalaiselvan369** [comment]
> @kalaiselvan369 may I suggest you try invoking the function directly in the command line or via Kotlin using the [`LambdaHttpClient` from http4k ](https://github.com/http4k/http4k/blob/3dd9907891cb1787a7c239bb99cbb8fc7e7f4557/http4k-serverless-lambda/integration-test/src/test/kotlin/org/http4k/serverless/lambda/client/LambdaHttpClientTest.kt#L18)?
> 
> I suspect that the console version is using an unsupported [version of the message payload](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html). Have you tried with both?

@s4nchez I haven't tried invoking function using LambdaHttpClient. How it would help me when I deploy it in AWS and test it? Could you please clarify?

**Comment by s4nchez** [comment]
> @s4nchez I haven't tried invoking function using LambdaHttpClient. How it would help me when I deploy it in AWS and test it? Could you please clarify?

It helps you validating if the lambda is configured correctly to bridge from `APIGatewayProxyRequestEvent` to the http4k's `HttpHandler`. 

We have an [integration test](https://github.com/http4k/http4k/tree/master/http4k-serverless-lambda/integration-test) deployed in AWS and it works via both LambdaHttpClient or using the AWS Console Test feature (by selecting the _Amazon API Gateway AWS Proxy_ as a template).

**Comment by kalaiselvan369** [comment]
@s4nchez  I will look into this https://github.com/http4k/http4k/tree/master/http4k-serverless-lambda/integration-test. Thank you.

**Comment by daviddenton** [comment]
Going to close this now as assume there isn't an issue with the lib. please reopen or reach out to us on slack if there are still problems. 🙃
