### ISSUE TITLE
Automarshalling with kotlinx serialization

### ISSUE THREAD

**Issue by carbotaniuman** [http4k/http4k#478]
Is this possible with KotlinX and just not implemented? Or is there some reason why it's impossible?

**Comment by daviddenton** [comment]
Not that we know of - we didn't do the implementation so maybe it would work out. Happy to take the PR if someone wants to do it.

One thing to note is that the KotlinX API has changed between 0.20.0 and 1.X. I've no idea if this will make it easier or harder to do, but it will require changes as we do the 1.4.0 upgrade (when everything is ready).
