### ISSUE TITLE
Regex input for allowing origins in CorsPolicy

### ISSUE THREAD

**Issue by kratostaine** [http4k/http4k#487]
The current logic for verification of the CORS policy only checks if the list of `origins` of `CorsPolicy` contains the origin of the request.
```
val allowedOrigin = when {
                    "*" in policy.origins -> "*"
                    origin != null && origin in policy.origins -> origin
                    else -> "null"
                }
```

Would it be okay to have a regex input for the `CorsPolicy` such that any origins matching the regex are allowed?

For eg, if I want domains like `aaa.company.com`, `bbb.company.com` and `ccc.company.com`, we could input a single regex to match all the 3, rather than have a list of those 3 domains in the CorsPolicy, which wouldn't scale when I have to add any more similar domains.

**Comment by daviddenton** [comment]
That sounds good. Feel free to PR it. 😄

**Comment by kratostaine** [comment]
@daviddenton sounds good! Can you please assign me this issue?
