### ISSUE TITLE
AccessTokenFetcher silently swallows BAD_REQUESTS

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#497]
When the response from the OAuth provider is invalid for some reason, the AccessTokenFetcher silently returns null:

```kotlin
fun fetch(code: String): AccessTokenDetails? = api(Request(POST, providerConfig.tokenPath)
        .with(CONTENT_TYPE of APPLICATION_FORM_URLENCODED)
        .form("grant_type", "authorization_code")
        .form("redirect_uri", callbackUri.toString())
        .form("client_id", providerConfig.credentials.user)
        .authenticate(accessTokenFetcherAuthenticator)
        .form("code", code))
        .let { if (it.status != OK) null else it }
        ?.let { msg ->
            CONTENT_TYPE(msg)?.takeIf { APPLICATION_JSON.equalsIgnoringDirectives(it) }
                ?.let {
                    with(accessTokenResponseBody(msg)) {
                        AccessTokenDetails(AccessToken(accessToken), idToken?.let(::IdToken))
                    }
                } ?: AccessTokenDetails(AccessToken(msg.bodyString()))
        }
```

The problem is on the line.

```kotlin
      .let { if (it.status != OK) null else it }
```

Ideally, we should at least log the message, eg.:

```
{"error":{"message":"Error validating client secret.","type":"OAuthException","code":1}}
```

Currently one need to step through the code to debug.

**Comment by daviddenton** [comment]
I think that the correct answer here is not to add logging but to decorate your `api: HttpHandler` with some type of auditing (maybe ReportHttpTransaction in coordination with RequestTracing if you need to link it all up). The actual OAuth code overall does do the right thing - it eventually does return the `oAuthPersistence.authFailureResponse()` in the OAuthCallback. For security we shouldn't be exposing the actual error to the client.
