### ISSUE TITLE
Matching URL with path parameter

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#501]
Consider a routing path:

`"/event/{id}/" meta { ... } bindContract POST to handler`

1. For some reason, when I curl `/event/123/` I am getting 404.
2. When I curl `/event/\{id\}/`, the request will pass and the `request.path("id")` will be null

Is there some specific which needs to be enabled to allow path parsing?

Is there a way to see parsed routes?

**Comment by daviddenton** [comment]
You're using the wrong type of routing for this. As per the docs, for contract routing you need to do something like this:

```
import org.http4k.contract.contract
import org.http4k.contract.div
import org.http4k.contract.meta
import org.http4k.core.Method
import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status
import org.http4k.lens.Path
import org.http4k.lens.int

fun main() {
    val app = contract {
        routes += "/event" / Path.int().of("id") meta {
        } bindContract Method.GET to { id ->
            { Response(Status.OK).body(id.toString()) }
        }
    }

    println(app(Request(Method.GET, "/event/123/")))
}

```

Docs [here](https://www.http4k.org/guide/modules/contracts/)

**Comment by knyttl** [comment]
Okay, thanks, I search desperately through

- https://www.http4k.org/cookbook/simple_routing/
- https://www.http4k.org/cookbook/nestable_routes/

THanks ocne more

**Comment by daviddenton** [comment]
np. I've added some links to the correct recipe to both of those pages. 😄
