### ISSUE TITLE
OPTIONS request for route with Header/Body fails with 400

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#502]
To properly provide for CORS, each endpoint must support `OPTIONS` method to prevent `CORS preflight channel did not succeed`.

This normally works for endpoints without required `Headers` or `Body`. `OPTIONS` of such endpoints with fail with: 

```
{"message":"Missing/invalid parameters","params":[
   {"name":"body","type":"body","datatype":"object","required":true,"reason":"Invalid"}
]}
```

I believe this is a bug as these parameters should not be required for `OPTIONS` method call.

**Comment by daviddenton** [comment]
Did you add can confirm that you've added a CORs filter, as per here?
https://github.com/http4k/http4k/blob/master/http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt

A small test to prove its failing would be really helpful. Thanks. 🙃

**Comment by knyttl** [comment]
Sorry, here:

```
import org.http4k.contract.contract
import org.http4k.contract.meta
import org.http4k.core.Body
import org.http4k.core.ContentType.Companion.TEXT_PLAIN
import org.http4k.core.Method
import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status
import org.http4k.format.Jackson.auto
import org.http4k.lens.string

data class TestObject(
    val string: String,
    val int: Int,
)

fun main() {
    val app = contract {
        routes += "/event1" meta { receiving(Body.string(TEXT_PLAIN).toLens()) } bindContract Method.POST to { Response(Status.OK).body("") }
        routes += "/event2" meta { receiving(Body.auto<TestObject>().toLens()) } bindContract Method.POST to { Response(Status.OK).body("") }
    }
    // 200
    println(app(Request(Method.OPTIONS, "/event1")))
    // 400, body missing
    println(app(Request(Method.OPTIONS, "/event2")))
}
```

this shouldn't require the body as it is only an `OPTIONS` call – note the endpoint is defined as `POST`

**Comment by daviddenton** [comment]
Does it work if you add a Cors Filter to the app?

**Comment by knyttl** [comment]
> Does it work if you add a Cors Filter to the app?

I am not sure how to add it, however this should not need the CORS as this is general HTTP spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by daviddenton** [comment]
You can add it by following the example above. 🙃

**Comment by knyttl** [comment]
> You can add it by following the example above. 🙃

See the edited comment.

**Comment by knyttl** [comment]
I tried with the CORS filter and I confirm it works. But as the HTTP spec defines, this should work without it.

**Comment by daviddenton** [comment]
Looks like the PreFlightExtractionFilter isn't ignoring the post requests. For the moment you can define your own one and add it at the contract level.

**Comment by knyttl** [comment]
superb!
