### ISSUE TITLE
Adding new line after the JSON output for readability after curl

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#505]
Is there a way to add new line to the JSON output for increased readability:

Current:
```
# curl /my-endpoint
{"status":"OK"} # cursor
```

Desired:
```
# curl /my-endpoint
{"status":"OK"} 
# cursor
```

Thanks

**Comment by daviddenton** [comment]
Without using a filter to explicitly do it, not that we know of. There may be an option to do it with Jackson configuration and then add it to your custom Jackson instance. Please feel free to add it as a comment here if you find a way, but it doesn't seem like it's something we'd add to the module.
