### ISSUE TITLE
Oauth flow with Google provider does not provide access to idToken

### ISSUE THREAD

**Issue by olimcc** [http4k/http4k#527]
I'm attempting to implement an Oauth flow following the [examples in the Developer Guide](https://www.http4k.org/guide/modules/oauth/) with Google as a provider, but am struggling to retrieve the idToken from the existing callback/storage implementation. [The docs](https://www.http4k.org/guide/modules/oauth/) say: _In order to remain provider-agnostic, the AccessToken object also contains the entirety of the (typically JSON) token response from the provider._

Debugging [the callback code](https://github.com/http4k/http4k/blob/master/http4k-security-oauth/src/main/kotlin/org/http4k/security/OAuthCallback.kt#L29) I can confirm that `tokenDetails` does contain both the `accessToken` and `idToken`, however, only `tokenDetails.accessToken` is persisted. Is this expected? Am I subsequently meant to use the accessToken to retrieve an idToken (again) myself, or am I missing some custom implementation I need to do?

Recreation:
- Version: `3.274.0` across the board
- Using [`OAuthProvider.google`](https://github.com/http4k/http4k/blob/master/http4k-security-oauth/src/main/kotlin/org/http4k/security/oauthProviders.kt#L43)
- I'll try to include a working demonstration, but right now my implementation is taken directly from the docs (`InsecureCookieBasedOAuthPersistence etc`) with specific credentials added.

**Comment by s4nchez** [comment]
Hi @olimcc,

Thank you for pointing that out. Persisting information from the id token during the authentication flow seems like a reasonable use case. We probably haven't seen that before because one can retrieve an id token and persist at a later stage.

Anyway, I'll extend the interface to expose the id token, which should make things easier for you.

**Comment by s4nchez** [comment]
This should be available in 3.278.0 (being released now)

**Comment by olimcc** [comment]
@s4nchez amazing, thank you. Understood regarding the possibility to fetch the idToken at a later stage. It's reasonably common to obtain and use the idToken information right at the end of this flow, so this makes sense to me.

Thanks again. I'm only a couple of weeks into http4k and enjoying it a lot!
