### ISSUE TITLE
Cookie.expires should use Instant to precisely represent point-in-time

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#546]
Consider running http4k on server with timezone GMT-1:

```kotlin
import org.http4k.core.cookie.Cookie
import org.junit.jupiter.api.Test
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.util.Calendar
import java.util.Locale
import java.util.TimeZone

class LocalDateTImeTest {
    @Test
    fun testLocalDateTime() {
        // running at local 20:00 GMT-1 which actually is 21:00 GMT
        // note LocalDateTime represents local time with no timezone information
        val localPlusHour = LocalDateTime.now().plusMinutes(10)
        val cookie = Cookie("key", "value", expires = localPlusHour)
        // returns 20:10 (with no timezone information)
        println("LocalDateTime plus hour: $localPlusHour")
        // here http4k attaches GMT timezone to 20:10 even though we are not in GMT
        val zonedDateTime = ZonedDateTime.of(cookie.expires, ZoneId.of("GMT")).format(DateTimeFormatter.ofPattern("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US))
        // returns 20:10 GMT, saying effectively the cookie already expired 50 minutes ago
        println(zonedDateTime)
    }
}

```

Using LocalDateTime does not define proper point in time, this should be represented with `ZonedDateTime` or even better with `Instant`.

**Comment by s4nchez** [comment]
Good spot, @knyttl. Thank you for raising it here. I vaguely remember someone else pointing it out before but never got around improving it.

Would you like to have a go changing it to Instant? I'd be happy to review it.

**Comment by knyttl** [comment]
Yes, I will.

**Comment by knyttl** [comment]
In face:

> The expires parameter was part of the original cookies baked up by Netscape. In HTTP version 1.1, expires was deprecated and replaced with the easier-to-use max-age—instead of having to specify a date, you can just say how long the cookie can live. 

What about removing it completely? :-)

**Comment by s4nchez** [comment]
That’s a good point. Feel free to just mark as deprecated or just close this and we’ll remove it as part of version 4 /cc @daviddenton

**Comment by knyttl** [comment]
Okay, closing.
