### ISSUE TITLE
ClientFilters.FollowRedirects doesn't work with in-memory RouterBasedHttpHandler

### ISSUE THREAD

**Issue by dkandalov** [http4k/http4k#554]
For example, the following test fails with `java.lang.IllegalStateException: Too many redirection` (maybe it should also be plural "redirections" 🤔):
```
    @Test
    fun `follow redirect with routes()`() {
        val server = routes(
            "/ok" bind GET to { Response(OK) },
            "/redirect" bind GET to { Response(SEE_OTHER).header("Location", "/ok") }
        )
        val client = FollowRedirects().then(server)
        assertThat(client(Request(GET, "/ok")).status, equalTo(OK))
        assertThat(client(Request(GET, "/redirect")).status, equalTo(OK))
    }
```

It must be related to the implementation of `fun Filter.then(routingHttpHandler: RoutingHttpHandler): RoutingHttpHandler = routingHttpHandler.withFilter(this)` because the test passes if `client` is initialised like this `FollowRedirects().then(server as HttpHandler)`.

**Comment by s4nchez** [comment]
Thank you for posting this @dkandalov. I've hit this behaviour myself in the past but never got around fixing it. I'll dig up further and update here then.
