### ISSUE TITLE
Servirtium lib - wildcards on Response.removeHeader( .. ) pls 

### ISSUE THREAD

**Issue by paul-hammant** [http4k/http4k#561]
It'd be great  if I could excise all X- prefixed headers from the recording.  

Either by straight prefix, or so '*' using scheme, or regex :)

See https://github.com/jbehave/jbehave-servirtium-climate-tck-demo/blob/ed42afffe3a5ee401683e6c46abaff92f353ef7f/src/main/java/dev/servirtium/jbehave/climate/ClimateInteractionOptions.java#L25

**Comment by daviddenton** [comment]
This can be easily done with a couple of extension functions in the core.

We also need things like "removeAllHeaders()".

**Comment by paul-hammant** [comment]
Gotta love terse elegance. Even more so when there's equal lines of test to prod and it's still elegant.
