### ISSUE TITLE
AWS Lambda - No option to disable base64 encoding on responses

### ISSUE THREAD

**Issue by tcreeds** [http4k/http4k#591]
In the current version of http4k's ApiGatewayV1LambdaFunction (and V2), the response is base64 encoded. While that is a pattern that can work for API Gateway, it is not the pattern that we were using in prior versions, and not the pattern we want to go forward with.

I assume there were reasons for adding the encoding in the first place, but unless it's considered an anti-pattern, I would love to be able to turn it off.

**Comment by daviddenton-zuhlke** [comment]
hmm - that crept in as a part of the change to using a Map - you;re right - it is probably very annoying. We'll see if there's a sensibly simple way to turn it off, or make it detect the right thing. For the moment, you can write a custom wrapper and adapter.

**Comment by daviddenton** [comment]
Just a thought for my understanding - what exact reasons do you have for wanting to turn off the encoding.in the first place?

From an http4k perspective, we wouldn't expect that it was something the user would actually care about, as inspection of the actual body message would be done in the http4k layers before the adapter.

**Comment by tcreeds** [comment]
This is for the response, so this happens after we've created a response object and returned it to HttpHandler. The API Gateway adapter base64 encodes it, and so the client is receiving a base64-encoded string instead of a json string. API Gateway can be set up to decode response bodies, but that pattern is intended for binary media types, and we'd rather not have to enable that for our json responses.

There might be something going on that I'm not aware of, but this is the line that I suspect I want changed/optioned, because we weren't getting base64-encoded responses with 3.220.0.
https://github.com/http4k/http4k/blob/master/http4k-serverless/lambda/src/main/kotlin/org/http4k/serverless/ApiGatewayV1LambdaFunction.kt#L39

I think I will write a custom adapter anyway. I ran into some issues trying to do so, and assumed that it wasn't a supported pattern (trying to override internal functions and such), but I guess I gave up too quickly!

**Comment by daviddenton** [comment]
but that pattern is intended for binary media types, and we'd rather not have to enable that for our json responses. 

YMmV, but there any reason that you couldn't just turn it on for everything? Seems like the apigateway will do the right thing anyway based on the flag. Interested to know the motivation/reasoning here that were missing (happy to be shot down!) 🙃

For us, we're trying to walk the line between simple API and configuration ability. The problem is that it isn't easy to determine if a response is supposed to be binary based on the object model or the headers. so then it was easier to just to always use base64.

Everything in http4k is designed to be customiseable, even by copying small amounts of code for your use case. If there is anything internal that makes sense to open up to minimise that further then just please flag it and we'll see what we can do.

**Comment by paulmiddelkoop** [comment]
For me it also make sense to influence if base64 encoding is used or not. It took me a while to understand why all my responses were encoded. It was not something I expected for JSON and plain text responses.
I was looking which web framework and language I want to use for a next project and others tools I used were not doing the base64 encoding. I tried Kotless/Ktor and Serverless on Rust.

**Comment by s4nchez** [comment]
@tcreeds @paulmiddelkoop yes, we should make the base64 encoding configurable. Those are [configured per media Type when you're using _REST_ Api Gateways](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html#api-gateway-payload-encodings-proxy) (most of our use cases so far have been with _HTTP_ Apis which don't seem to care about this).

My proposal is to switch the default in ApiGatewayV1LambdaFunction.kt to *not* base64 encode the responses by default but allow users to pass a list of content types that require encoding.

**Comment by paulmiddelkoop** [comment]
Sounds good @s4nchez. Same applies to `ApiGatewayV2LambdaFunction.kt ` I think. Although I could not get my code running on version 2 last time I tried.

**Comment by s4nchez** [comment]
Again, it all depends on whether you have REST or HTTP APIs in API Gateway. I'm planning to extend our integration tests to cover the different types, as well as the treatment of binaries as soon as I can.

**Comment by s4nchez** [comment]
@paulmiddelkoop @tcreeds what type of API Gateway are you using (REST or HTTP)? The base64 encoding seems to be a problem only for REST APIs, and for those, I've introduced a `ApiGatewayRestLambdaFunction` which doesn't encode the response.

Unless you are having issues with an HTTP API (newer version), I'll just release this new kind of function integration for people using REST.

**Comment by paulmiddelkoop** [comment]
@s4nchez I'm using REST, so `ApiGatewayRestLambdaFunction` sounds good to me. Thanks for picking it up so fast!

**Comment by s4nchez** [comment]
@paulmiddelkoop Excellent. That's now available in version 4.4.1.0. 

Let us know if you hit any other issues 😃

**Comment by paulmiddelkoop** [comment]
@s4nchez Tested the new version and it works like a charm. Thanks!
