### ISSUE TITLE
AWS Lambda example from documentation throws compilation error

### ISSUE THREAD

**Issue by suyash192** [http4k/http4k#601]
The AWS Lambda example given here does not seem to work:
https://www.http4k.org/guide/modules/serverless/#code

Getting the following compilation error:

```
Unresolved reference: proxy
```

It seems the import for proxy cannot be found:

``` java
import org.http4k.util.proxy
```

These are the dependencies I'm using. Is there anything missing here?

``` groovy
dependencies {
    implementation "org.http4k:http4k-core:${http4kVersion}"
    implementation "org.http4k:http4k-format-kotlinx-serialization:${http4kVersion}"
    implementation "org.http4k:http4k-serverless-lambda:${http4kVersion}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}"
    testImplementation "org.http4k:http4k-testing-approval:${http4kVersion}"
    testImplementation "org.http4k:http4k-testing-hamkrest:${http4kVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.7.0"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:5.7.0"
}
```

**Http4k Version:** 4.5.0.1
**Kotlin Version:** 1.4.31

**Comment by s4nchez** [comment]
Hi @suyash192 ,

That's because `proxy()` exists only in the http4k-core's test sources. I suggest you simply copy the function definition to make it work for you:

```kotlin
inline fun <reified T> proxy(): T = Proxy.newProxyInstance(T::class.java.classLoader, arrayOf(T::class.java)) { _, _, _ -> TODO("not implemented") } as T
```

Let me know if that works.

**Comment by suyash192** [comment]
Thanks @s4nchez! That seems to solve it. 

Shouldn't this function be included in the docs then?

**Comment by daviddenton** [comment]
Right you are @suyash192 . Fixed :)

**Comment by suyash192** [comment]
Awesome! Appreciate the quick responses! :)
