### ISSUE TITLE
Incorrect use of URLDecoder in UriTemplate

### ISSUE THREAD

**Issue by vojtechtoman** [http4k/http4k#602]
The use of `URLDecoder` in: https://github.com/http4k/http4k/blob/791907b1662b78b1812e4ec21e7bfc823808c1e1/http4k-core/src/main/kotlin/org/http4k/core/UriTemplate.kt#L38 leads to incorrect results because we are in the 'path' URI component where different escaping rules apply compared to the 'query' URI component. For instance, the '+' character should be treated literally in a URI path, but `URLDecoder` replaces it with a space.

**Comment by s4nchez** [comment]
@vojtechtoman, thank you for reporting this. 

Can you please provide a test showing how the problem manifests and some reference (maybe from the RFC?) on how the correct behaviour should be? That'd speed up any potential fix as that code is from the early days of the project, and I need to re-familiarize myself with that part of the domain.

**Comment by vojtechtoman** [comment]
The relevant part of [RFC 3986](https://tools.ietf.org/html/rfc3986) are the `segment` and `pchar` [productions](https://tools.ietf.org/html/rfc3986#appendix-A):
```
segment       = *pchar
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
pct-encoded   = "%" HEXDIG HEXDIG
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
              / "*" / "+" / "," / ";" / "="
```
The characters ":", "@", `unreserved`, and `sub-delims` have no special meaning in a path segment and should not be interpreted.

As for a reproducer:
```
val routes = routes(
    "/test/{param}" bind GET to {
        println(it.path("param"))
        Response(Status.OK)
    }
)
routes(Request(GET, "/test/a+b")) // outputs "a b" instead of "a+b"
```

**Comment by mrtom808** [comment]
The path encoder also looks incorrect as it encodes " " to "+" instead of "%20". URLDecoder/URLEncoder are for working with form data encoded after a ? in a URL so their use in UriTemplate for paths should be avoided. Unfortunately the jdk libs hide anything useful that could be used.

**UriTemplateTest**:
```java
    @Test
    fun supportsPlusCharactersInUriPath() {
        val template = from("properties/{name}")
        val parameters = template.extract("properties/A%20+%20B")
        assertThat(parameters.getValue("name"), equalTo("A + B"))
        assertThat(template.generate(pathParameters(pair("name", "A + B"))), equalTo("properties/A%20+%20B"))
    }
```

In the second assert, either "+" or "%2B" would be valid in the output.

**Comment by jenarros** [comment]
In https://github.com/http4k/http4k/pull/690, I have extended the tests to capture the full spec, see https://github.com/http4k/http4k/pull/690/files#diff-52b6d392bb64ba7ecde795a3ab86f799da01e48f49b976904fb24b05254470c0R88.

This seems like an important change to the current behaviour though.
