### ISSUE TITLE
How to use Directory ?( # android # static # server )

### ISSUE THREAD

**Issue by Marksteinsong** [http4k/http4k#604]
What path should i fill the Directory() function, if i want to serve "index.html" ?

webServer.kt
![image](https://user-images.githubusercontent.com/26346161/112741609-e6de9280-8fb9-11eb-83ee-a9dea1f7ae77.png)

![image](https://user-images.githubusercontent.com/26346161/112741627-0970ab80-8fba-11eb-87c1-b424101a4f9f.png)

**Comment by daviddenton** [comment]
`Directory(baseDir)` serves a direct path, so under the covers it is just serving from `File(baseDir)`. It is used mostly for Hot Reload scenarios.

I suspect that you really want to load from the classpath here, so use `Classpath()` instead.

For reference - for questions like this, it's more efficient to hit us up on th3 #http4jk channel on the KotlinLang slack instance. 😄

**Comment by Marksteinsong** [comment]
For those who use http4k as a server on android platform, the code below might help:

You can not directly serve the file in folder assets because it is packaged in the apk.

So you have to copy files to a directory like "/data/data/0/com.packageName.appName/files",
and the you can serve you web site  directly from "/data/data/0/com.packageName.appName/files".

![图片](https://user-images.githubusercontent.com/26346161/113117538-223ec280-9241-11eb-8e7c-4b805120e6e2.png)


![图片](https://user-images.githubusercontent.com/26346161/113117591-2f5bb180-9241-11eb-8d6f-672b743d2d68.png)
