### ISSUE TITLE
I'm receving an error method is invalid

### ISSUE THREAD

**Issue by kiquetal** [http4k/http4k#619]
I was studying the aws-lambda-example from the guide, but I found the following exception when I was testing using the AWS APIGateway console.

Request:
 Endpoint request body after transformations: {"resource":"/{proxy+}","path":"/","httpMethod":"POST","headers":null,"multiValueHeaders":null,"queryStringParameters":null,"multiValueQueryStringParameters":null,"pathParameters":null,"stageVariables":null,"requestContext":{"resourceId":"4x0fo0","resourcePath":"/{proxy+}","**httpMethod**":"POST","extendedRequestId":"fW7cSGyJIAMFz7g=","requestTime":"15/May/2021:07:05:24 +0000","path":"/{proxy+}","accountId":

Response:  

` Endpoint response body before transformations: {"errorMessage":"**method is invalid**","errorType":"java.lang.IllegalStateException","stackTrace":["org.http4k.serverless.ApiGatewayV2AwsHttpAdapter.toHttp4kRequest(ApiGatewayV2.kt:37)","org.http4k.serverless.ApiGatewayV2AwsHttpAdapter.invoke(ApiGatewayV2.kt:53)","org.http4k.serverless.ApiGatewayV2AwsHttpAdapter.invoke(ApiGatewayV2.kt:34)","org.http4k.serverless.ApiGatewayFnLoader$invoke$1.invoke(ApiGatewayFnLoader.kt:21)","org.http4k.serverless.ApiGatewayFnLoader$invoke$1.invoke(ApiGatewayFnLoader.kt:12)","org.http4k.serverless.AwsLambdaEventFunction.handleRequest(AwsLambdaEventFunction.kt:15)"]}`

Looking at this file:

https://github.com/http4k/http4k/blob/fd0a19baeb60df5c7f799599324d30591e604579/http4k-serverless/lambda/src/main/kotlin/org/http4k/serverless/ApiGatewayV2.kt#L36

I think the problem occurs when the code receives "httpMethod":"POST", 
and the code is expecting the lowercase 'm'

I apologize for my broken english.
Best Regards.

**Comment by daviddenton** [comment]
The aws console uses an API gateway version 1 request from the drop down. If you change your example from V2 to V1 it should  work.

**Comment by daviddenton** [comment]
We should change the example to use v1.. 😁

**Comment by kiquetal** [comment]
Sorry, I didn't use the exact example from the documentation, instead, I created it from https://toolbox.http4k.org/

I found the following documentation: 
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

So http4k uses type http api and no the type rest api ?
[image](https://drive.google.com/file/d/1t5UNyW9NHlHj2AKetvcXWc-fr-ANp3jA/view?usp=sharing)
Best Regards

**Comment by daviddenton** [comment]
We support all of them - just pick which class you want to extend from - they are all in the same package 🙃. 

And btw Rest is only available on V1 - it's frustrating that the API gateway console only has the v1 message.

**Comment by kiquetal** [comment]
Thank you @daviddenton!I'll look at it
Best Regards.
