### ISSUE TITLE
When Spring on CP: OkHttpKt.requestBody java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by dkandalov** [http4k/http4k#627]
This is not really a bug but rather an experience report working on a project using ~EJB 2.0~ springframework and http4k.
I'm posting it here so that if someone comes across this problem they have a chance of finding the description here.

I noticed that as soon as I switched to from `apache` to `okhttp` client, simple tests like this one
```kotlin
@Test fun `do a post request`() {
    OkHttp()(Request(POST, "http://localhost:8080"))
}
```
started failing with the following stacktrace
```
java.lang.NoSuchFieldError: Companion
at org.http4k.client.OkHttpKt.requestBody(OkHttp.kt:75)
at org.http4k.client.OkHttpKt.asOkHttp(OkHttp.kt:68)
at org.http4k.client.OkHttpKt.access$asOkHttp(OkHttp.kt:1)
at org.http4k.client.OkHttp$invoke$1.invoke(OkHttp.kt:38)
at org.http4k.client.OkHttp$invoke$1.invoke(OkHttp.kt:35)
at Tests.do a post request(Foo.kt:12)
...
at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

Which looked very much like a problem with http4k but it's not.

Skipping the long story, the problem was with `okhttp` library being downgraded to a version which is not compatible with `http4k-client-okhttp`. E.g. output from `gradle dependencies`:
```
+--- org.http4k:http4k-client-okhttp -> 4.9.8.0
|    +--- org.http4k:http4k-core:4.9.8.0 (*)
|    +--- com.squareup.okhttp3:okhttp:4.9.1 -> 3.14.9
```
And the reason for the downgrade was springframework gradle plugins:
```
plugins {
    java
    kotlin("jvm") version "1.5.20"
    id("org.springframework.boot") version "2.5.2"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
}
```
You can probably stop spring from doing the downgrade with gradle dependency locks, but I was able to just stop using these gradle plugins.

And of course the ultimate fix is to migrate all code to http4k ;)

**Comment by razvn** [comment]
Had the same problem (talk about it on the slack channel), I forced the okhttp lib version to a newest version in SprinBoot app and is all fine. But is kinda dumb as I'm not using okhttp in that project but just in a http4k lib...

**Comment by daviddenton** [comment]
I'm going to close this as not really a bug for us, but will leave it here for future victims to ponder over.
