### ISSUE TITLE
http4k-Contract - Customize 400 bad_request on lens failure

### ISSUE THREAD

**Issue by BubbaJoe** [http4k/http4k#633]
I am currently using contracts in my application and I was wondering if it was possible to customize the defaulted BAD_REQUEST. I tried using the ServerFilter.CatchLensFailure, but ContractRoute is using it too, so it doesn't work. 

```json
    "message": "Missing/invalid parameters",
    "params": [
        {
            "name": "body",
            "type": "body",
            "datatype": "object",
            "required": true,
            "reason": "Invalid"
        }
    ]
}
```

**Comment by daviddenton** [comment]
You can do this by manually constructing the OpenApi3 class and overriding the `errorResponseRenderer` field:
