### ISSUE TITLE
Is there a build-in way to do something after the response truly return to the requestor?

### ISSUE THREAD

**Issue by IThinkIGottaGo** [http4k/http4k#634]
I check the ResponseFilters.kt but it seems do modify or call something before the response actually return to the client.

SO is there any build-in mechanism to do this callback? or I actually mislead that It's actually called after return to the client.

If there is already a method could do that can give me some hints or references?

Thanks, I am trying familiar with KT, so much bracket nested looks a bit of headache for me now 😂

**Comment by daviddenton** [comment]
http4k applications are built on the premise of composing standard functions together, and hence there is no built-in mechanism for any type of background processing.

The library is entirely compatible with whatever mechanism you want to put into place (threads/coroutines etc) - but bear in mind that generally http4k HTTP messages are immutable, so modifying them after return (with the possible exception of Stream bodies) will not have any effect.

**Comment by IThinkIGottaGo** [comment]
@daviddenton 
I get it, thanks for your answer. 🙂

**Comment by razvn** [comment]
Is nothing build in as the library does not have asynchronous support, but it's easy to launch an async task before returning the response. In one project we use coroutines to do that, in another Java's CompletableFuture.
