### ISSUE TITLE
Lazy init contract without path params: Type mismatch. Required: Response Found: HttpHandle

### ISSUE THREAD

**Issue by dbacinski** [http4k/http4k#644]
I want a handler that is lazily initialized so that in the test I wouldn't have to init all dependencies.

`"/payment_method/cc" bindContract Method.GET to { di.creditCardHandler.handleListCards() }`
something like this fails with
`Type mismatch. Required: Response Found: HttpHandle`

I think it is caused by how ContractRouteSpec0.Binder.to is defined:

<img width="564" alt="Screenshot 2021-08-04 at 11 49 28" src="https://user-images.githubusercontent.com/454414/128160923-ec8893b4-22c1-43aa-ad19-d7a53ff6bb80.png">

workaround is to use  fake 1 param contract but it is not optimal:

`"/payment_method" / Path.fixed("cc") bindContract  Method.GET to { di.creditCardHandler.handleListCards() }, // compiles`

Example:
```   
  contract {
                renderer = OpenApi3(
                    ApiInfo("KK API", "v1.0", "KK API"),
                    Jackson,
                    emptyList(),
                    ApiRenderer.Auto(Jackson, AutoJsonToJsonSchema(Jackson)),
                    SecurityRenderer(AuthTokenFilter.AuthTokenSecurity.renderer),
                )
                descriptionPath = "/openapi.json" //XXX it is public but "secured" with random
               routes += listOf(
  "/payment_method/cc" bindContract
                    "/payment_method/cc" bindContract
                            Method.GET to { di.creditCardHandler.handleListCards() }, // does not compile     
                    "/payment_method/cc" meta PaymentMethodCreditCardGet bindContract
                            Method.GET to di.creditCardHandler.handleListCards(),  // compiles, but eagerly loaded   
                    "/payment_method" / Path.fixed("cc") bindContract
                            Method.GET to { di.creditCardHandler.handleListCards() }, // compiles
                )
}
```

**Comment by dbacinski** [comment]
Another example of inconsistent contract definition with the same root cause.

0 and 1 param handlers with method references:

```
    "/cart" bindContract Method.POST to cartHandler::handleCreateCart, //0 params, does not compile with method reference
     "/cart" bindContract Method.POST to cartHandler.handleCreateCart(), //0 params, compiles, but inconssistient
     "/cart" / Path.of("cart_id") bindContract Method.GET to cartHandler::handleGetCart, //1 params, compiles with method reference
```

**Comment by daviddenton** [comment]
Have fixed this and will be in 4.11.0.0 (building soon). It is a breaking change, but I think it's a worthwhile one to get consistency across the API.

Thanks for the thorough investigation. @dbacinski ! 😄

**Comment by dbacinski** [comment]
Method references are now working for zero arg handler.

There is one glitch when trying to lazy init zero args handler:

<img width="843" alt="Screenshot 2021-08-11 at 12 01 39" src="https://user-images.githubusercontent.com/454414/129010837-f303e776-0bfa-4b77-9234-e235d658a791.png">

as there are 2 `to` functions:

<img width="574" alt="Screenshot 2021-08-11 at 12 02 04" src="https://user-images.githubusercontent.com/454414/129010582-f10af936-6479-48f3-9bef-37ba6abaf80e.png">

You could consider removing old to function.

**Comment by daviddenton** [comment]
That's not a glitch - that was intentional (as per the changelog). We're definitely not removing the old method `to()` as the new lazy initialisation version is the exception rather than the rule. 😄
