### ISSUE TITLE
Boolean field can escape lens check without throwing MissingKotlinParameterException

### ISSUE THREAD

**Issue by tootoohu** [http4k/http4k#646]
I have a question here. Not sure if it defined as it is. http4k version is 3.112.2

I defined a new http request interface, the request body is receiving a Boolean type. If I tried to rename the input Boolean property name, then I still get the default false value from the lens request.

Here is the example code that can describe the case ->

```  
data class TestRequest(
    val frozen: Boolean,
    val name: String
)

fun main() {

   val requestLens =  Body.auto<TestRequest>().toLens()
  
//request with frozen property is wrong
   val request1 =  Request(Method.PATCH, "/status").body("{\n" +
           "    \"frozenwrong\": true,\n" +                                                       
           "    \"name\": \"test\"\n" +
           "}")


    val frozen = requestLens(request1).frozen   // frozen is false, get the default value, no lens failure exception is thrown here
    val name = requestLens(request1).name

    println("frozen + $frozen")
    println("name + $name")

//request with name property is wrong
    val request2 = Request(Method.PATCH, "/status").body("{\n" +
            "    \"frozen\": true,\n" +
            "    \"namewrong\": \"test\"\n" +
            "}")

    val name2 = requestLens(request2).name  // get LensFailure exception Caused by: //com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException
    val frozen2 = requestLens(request2).frozen

}

```

Not sure here if it's expected. while, I don't want the lens operation tolerate the exception when the type is Boolean.  It would be better if it can throw the same exception just as String field.

How can I add some lens check on Boolean field?

**Comment by daviddenton** [comment]
This is a Jackson misconfiguration. We need to add ```    .configure(FAIL_ON_NULL_FOR_PRIMITIVES, true)``` to  cover it.

**Comment by tootoohu** [comment]
Thank you @daviddenton so much~

any way we can inject FAIL_ON_NULL_FOR_PRIMITIVES to be true in our program to fix this issue?
