### ISSUE TITLE
Prometheus Monitoring

### ISSUE THREAD

**Issue by tobad357** [http4k/http4k#65]
Is there any plans to develop a Prometheus module
that would expose relevant statistics automatically?

**Comment by daviddenton** [comment]
Adding monitoring modules (Prometheus and/or Dropwizard) is on the roadmap, but I can't say when it'll be done. If you let us know which metrics are important to you then we can take that into consideration when we do it.

 In the meantime, we provide Filters to report latency and which will allow you to plug in whatever you want. You can put these filters around either a Server or a Client HttpHandler:

```
   // this provides the exact request/response so you can identify your metric as you wish
    val standard = ResponseFilters.ReportLatency { req, resp, duration ->
        println("${req.uri} returned ${resp.status} and took $duration")
    }
    
   // this will provide an anonymised metric name, which is in the format similar to this: GET._path_dir_someFile_html.2xx.200 - this allow effective bucketing for statistics in the end stats system.
    val identified = ResponseFilters.ReportRouteLatency(Clock.systemUTC()) { identity, duration ->
        println("$identity and took $duration")
    }
```

**Comment by daviddenton** [comment]
@tobad357 FYI - we now provide prometheus support through the new micrometer module - which is an abstraction layer over various metric systems. It'll be appearing in Bintray and Maven in due course (requests have been raised!), but for the moment you can get it through the custom http4k repo: https://dl.bintray.com/http4k/maven and the dependency: 

```
<dependency>
  <groupId>org.http4k</groupId>
  <artifactId>http4k-metrics-micrometer</artifactId>
  <version>3.11.1</version>
  <type>pom</type>
</dependency>```

Hence I'm going to close this issue until something comes up that falls outside of the micrometer feature set.
