### ISSUE TITLE
Using Graalvm with Jackson mapping causing error in Lambda `No serializer found for class`

### ISSUE THREAD

**Issue by Johnathan-Aretos** [http4k/http4k#653]
Http4k is a great product, I had been using it with no issues, running a serverless configuration. I wanted to switch over to Graalvm to improve performance on cold starts but am experiencing some issues. 

This is my current code setup.

```Kotlin
data class PingRes(
    val name: String,
    val message: String
)

val pingLens = Body.auto<PingRes>().toLens()

object Ping {

    private val spec = "/pingg" meta {
        summary = "Pingg"
        returning(OK, pingLens to PingRes("name", "message"))
    } bindContract GET

    private val ping: HttpHandler = { _: Request ->
        Response(OK).with(pingLens of PingRes(name = "Hello", message = "Bye"))
    }

    operator fun invoke(): ContractRoute = spec to ping
}
```

Once I compile this and upload to AWS Lambda, I get this error below. It seems to be something with the configuration of Jackson. 

`
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class routes.PingRes and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
`

Has anyone experienced this before? Or can anyone point me in the right direction.

**Comment by daviddenton** [comment]
This isn't an Http4k thing - it's to do with the use of reflection in Jackson with Graal. Reflection (such as auto marshalling) has to be explicitly configured when building your image - this is tricky and annoying at best.

We don't use Jackson with Graal for exactly this reason. The easiest workaround is to use Moshi instead and add a custom Moshi type factory which is auto generated at compile time using Kotshi and Kapt. Http4k-conmect does this if you want an example

**Comment by Johnathan-Aretos** [comment]
Awesome, thanks! Will give it a go, does Moshi Support Contract routing?, it seems like Jackson is still needed for that.

**Comment by daviddenton** [comment]
Ah - no it doesn't - sorry. OpenApi is still Jackson only at the moment.
