### ISSUE TITLE
OAuth Security Client Filter for offline access

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#654]
I had a use-case for OAuth offline access, where you have a `refresh_token`, `client_id`, and optional `client_secret`, and you must use them to obtain an `access_token` for your requests to the resource server.

I couldn't find anything in the existing OAuth filters to accomplish that, so I made my own.  Was I not searching hard enough?  or would you be interested in me contributing my solution?

**Comment by daviddenton** [comment]
We're really happy to get any PRs(or even examples) of how to improve the functionality that might be useful to everyone. thanks 😄
