### ISSUE TITLE
Request.uri doesn't have full context

### ISSUE THREAD

**Issue by moredip** [http4k/http4k#66]
Hi! 

I'm a total newbie with both Kotlin and http4k, but loving how it looks. Kudos! 

I was poking around at the TodoBackend implementation, and noticed that [you're hard-coding the base url](https://github.com/http4k/http4k-contract-todo-backend/blob/master/src/main/kotlin/org/http4k/todo/TodoBackendApp.kt#L27) for the hypermedia links in the generated API. Digging in, it looks like that's necessary because `Request.uri` doesn't have things like `host` and `port` populated, at least when running against the Servlet backend. Am I right that this is the motivation for the hard coding?

I *think* the root cause for this missing context in the request is because the conversion from a Servlet request to an internal http4k request [is using `getRequestUri`](https://github.com/http4k/http4k/blob/857e78e930be310d32873136d729237d426b269f/http4k-core/src/main/kotlin/org/http4k/servlet/servlet.kt#L30), and per the servlet API docs that will not include the full URL. They say "To reconstruct an URL with a scheme and host, use HttpUtils#getRequestURL". 

Would you be interested in a PR to fix this? And am I on the right track for solving it, or is there a nicer way?

**Comment by s4nchez** [comment]
Hi @moredip . Glad to hear you're enjoying it :)

You're correct about the hardcoded value in todo-backend. We don't populate scheme/host/port at the moment. The reason behind this decision is that those tend to become unreliable if your app is running behind a proxy, which means scheme and host are not necessarily what is visible to real users.

In any case, we would be interested in a PR to add this information but would like to keep all server backends (SunHttp/Jetty/Netty/Undertow) consistent. So if you're able to investigate and add this new behaviour to `org.http4k.server.ServerContract` we'd be happy to incorporate the change.
