### ISSUE TITLE
Contract samples do not respect jackson XML annotations

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#681]
When using Jackson XML annotations to format the output of an XML element, the actual response is formatted correctly, but the samples in the openapi spec are not.  Presumably this is because the openapi renderer uses a standard Jackson mapper, thus ignores the xml annotations.

Is there any way to get this to work as expected?

### Workarounds

You can get around some of these issues by modifying your DTOs to have the precise names and casing you want for your xml, but this does not work for more complicated structures -- like wrapped lists -- which require annotations to be formatted correctly.  This also interferes with apps that want to share the same DTOs for xml and json bodies.

### To Reproduce

Consider this sample app which defines a xml response body -- `PersonDto` -- in a contract.  This model has a `JacksonXmlRootElement` annotation which defines the name of the root element.

```kotlin
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement
import org.http4k.contract.contract
import org.http4k.contract.meta
import org.http4k.contract.openapi.ApiInfo
import org.http4k.contract.openapi.v3.OpenApi3
import org.http4k.core.*
import org.http4k.format.JacksonXml.auto

@JacksonXmlRootElement(localName = "Person")
data class PersonDto(
    val name: String
)

val personSample = PersonDto(name = "John")
val personLens = Body.auto<PersonDto>().toLens()

val contract = "/" meta {
    returning(Status.OK, personLens to personSample)
} bindContract Method.GET

val handler: HttpHandler = { Response(Status.OK).with(personLens of personSample)}

val http = contract {
    renderer = OpenApi3(
        ApiInfo(
            title = "XML Service",
            version = "v1.0"
        )
    )
    this.descriptionPath = "/openapi.json"
    routes += contract to handler
}

fun main() {
    println(http(Request(Method.GET, "/openapi.json")))

    println(http(Request(Method.GET, "/")))
}
```

```
{"info":{"title":"XML Service","version":"v1.0"},"tags":[],"servers":[{"url":"/"}],"paths":{"":{"get":{"summary":"<unknown>","tags":[""],"parameters":[],"responses":{"200":{"description":"OK","content":{"application/xml":{"schema":{"$ref":"#/components/schemas/PersonDto"}}}}},"security":[],"operationId":"get","deprecated":false}}},"components":{"schemas":{"PersonDto":{"properties":{"name":{"example":"John","type":"string"}},"example":{"name":"John"},"type":"object","required":["name"]}},"securitySchemes":{}},"openapi":"3.0.0"}
<Person><name>John</name></Person>
```

### Expected Output

I would expect both the sample and actual responses to return the body
```xml
<Person><name>John</name></Person>
```

### Actual Output

If you were to invoke `GET /`, you would get the correctly formatted xml response body:
```xml
<Person><name>John</name></Person>
```

However, the spec -- when viewed by an appropriate OpenApi UI-- displays a response sample of

```xml
<PersonDto>
	<name>John</name>
</PersonDto>
```

`@JacksonXmlRootElement` should have changed the root element name to `Person`, but it did not.

![Capture](https://user-images.githubusercontent.com/894152/146687695-b71e0752-9046-4e15-b2f5-34e5441f3278.PNG)

**Comment by daviddenton** [comment]
Sorry it's taken so long to get to this. You can actually workaround it by providing your own `SchemaModelNamer` which can look at the annotations and then pass it into the constructor of AutoJsonToJsonSchema. It will have to be custom to support the XML annotation, but it's doable. 😄 

```kotlin
class AutoJsonToJsonSchema<NODE : Any>(
    private val json: AutoMarshallingJson<NODE>,
    private val fieldRetrieval: FieldRetrieval = FieldRetrieval.compose(SimpleLookup()),
    private val modelNamer: SchemaModelNamer = SchemaModelNamer.Simple,
    private val refPrefix: String = "components/schemas"
)
```

If you wanted to PR the implementation back then we can add it as an optional inclusion for if people have JacksonXML on the classpath.

**Comment by oharaandrew314** [comment]
Hmm, that could work for naming the fields.  But it wouldn't help with more advanced annotations, like wrapped lists.

e.g.

```
data class Person(
  @JacksonXmlElementWrapper(localName = "Addresses")
  @JacksonXmlProperty(localName = "Address")
  val addressed: List<Address>
)
```

would get rendered as

```
<Person>
  <Address>...</Address>
  <Address>...</Address>
</Person>
```

instead of 

```
<Person>
  <Addresses>
    <Address>...</Address>
    <Address>...</Address>
  </Addresses>
</Person>
```

**Comment by daviddenton** [comment]
Hmm it's tricky because you're fundamentally changing the structure of the data and we don't operate on the XML version of the data.

**Comment by oharaandrew314** [comment]
@daviddenton, yeah I feel like the only real option is to use the body lens to serialize the sample, but I know the OpenApi spec just doesn't work like that.  Regardless of the output format, the sample is still represented as json, and only gets converted to XML by the UI.

I suppose you could go from sample object to xml, parse the raw xml, and then serialize back to json... but that seems ridiculous.  I wonder if and how other frameworks deal with this.  I came from Javalin, but it only supports json, so it won't be of any help.

**Comment by daviddenton** [comment]
Yep - we fallback to JSON generally, which is why this is so hard - and that the default behaviour is in a class called `AutoJsonToJsonSchema`!

However, you could implement (as AJTJS does), `JsonSchemaCreator<Any, NODE>` and have it support XML quite easily.

**Comment by oharaandrew314** [comment]
Ah yes, that looks like it will work.  Perhaps there could even be a wrapper that delegates to the XML or JSON implementation depending on the content type of the body lens.  In my use case, XML and JSON were both valid content types.

This limitation hasn't been a huge problem for me, but I'm sure it would be useful for anyone else that wants to offer callers their choice of content type.  I might work on something to do this eventually 🤷 .
