### ISSUE TITLE
Body not sent in delete for Apache client

### ISSUE THREAD

**Issue by thiagocavalcanti** [http4k/http4k#686]
The body is not sent for DELETE, when using ApacheClient. Using OkHttp works fine

Version: 4.17.7.0

Basic code to reproduce:
`        val response = ApacheClient()(Request(
            Method.DELETE,
            "https://myurl.com",
        ).body(body))`
This works fine: `val response = OkHttp()(Request(
            Method.DELETE,
            "https://myurl.com",
        ).body(body))`        

The error that I'm getting is from the server, because the body is mandatory.

**Comment by daviddenton** [comment]
I'm afraid there isn't anything we can do about this AFAIK. The various clients act in different ways under the hood and there are variations based upon their implementation details - we are using the official APIs that Apache publish without modification.

Attempting to work around these variations is something that (as with http servers) we don't want to start doing. We suggest picking a client and server based on your needs.

A body in an HTTP delete seems to be a contentious subject. See https://stackoverflow.com/questions/3773338/httpdelete-with-body

Closing this as won't fix. But thanks for pointing it out.! 🙃
