### ISSUE TITLE
Out-of-date opentelemetry dependencies causing conflicts when http4k used with opentelemetry itself

### ISSUE THREAD

**Issue by sigma-libra** [http4k/http4k#697]
We've been having[ issues](https://github.com/open-telemetry/opentelemetry-java/issues/4159) with opentelemetry since they upgraded to version 1.10.0 in December. They finally helped us trace those issues back to the [http4k-opentelemetry](https://mvnrepository.com/artifact/org.http4k/http4k-opentelemetry/4.19.1.0) library which still uses v1.6 of several of their metrics libraries.

Any chance we can get these dependencies updated to a newer version? Thanks!

**Comment by daviddenton** [comment]
The reason that we stopped actively upgrading the open telemetry dependencies is that the project continually broke their own APIs on minor version upgrades. As such I am disappointed but unsurprised that the runtime characteristics are also broken.

If you upgrade the libraries and the couple of filters that rely on them to work with whatever changes have been introduced, we will gladly accept and merge the PR. 😄

**Comment by jshiell** [comment]
I'll try have a look at this on Friday, work permitting, as we need this as well at some point.

Honestly, though, whoever thought distributing their `alpha` metrics libs with the telemetry stuff deserves a nasty fate.

**Comment by sigma-libra** [comment]
Thanks for the info, David. I have some time this week-end, until then we'll just make do with the last versions that worked together 😊

For anyone else with bizarre versioning issues, we found that opentelemetry v1.9.1 still works with http4k v4.19.1.0.

**Comment by jenarros** [comment]
I just pushed a PR to upgrade http4k to OpenTelemetry 1.11.0. There were a few OpenTelemetry breaking API changes but hopefully going forwards the metrics api will be more stable.

**Comment by daviddenton** [comment]
Tysm for the PR. We'll get it released asap 🙃

**Comment by jenarros** [comment]
> I'll try have a look at this on Friday, work permitting, as we need this as well at some point.
> 
> Honestly, though, whoever thought distributing their `alpha` metrics libs with the telemetry stuff deserves a nasty fate.

Indeed! Given their current cadence, I will set myself a monthly reminder to keep the versions up to date until the library stops being in "alpha" state.

**Comment by daviddenton** [comment]
Releasing in 4.19.3.0
