### ISSUE TITLE
Case insensitivity for enum lenses

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#708]
There are time I would like an enum lens be case-insensitive.  Are there any objections to adding this as an option?

e.g.
```
val queryLens = Query.enum<MyType>(caseSensitive=false).required("type")
val pathLens = Path.enum<MyType>(caseSensitive=false).of("type")
```

I wouldn't mind contributing this feature.

**Comment by daviddenton** [comment]
Sure - if it's easy 🙃
