### ISSUE TITLE
CSV Body Lens

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#718]
I'd like to propose adding support for a CSV body lens.  Naturally, it would only support collections of data.

I'll be working on this feature independently anyway, so I'm happy to contribute an outbounds lens if accepted.  Jackson already has a csv dataformat, so I can delegate directly to it.

**Comment by daviddenton** [comment]
This works as long as we can avoid dragging in a new dependency to core, Maybe we could start an http4k-format-csv module which would be nicely decoupled. And if we could have some type of `AutoMarshalling` then that would fit in neatly to the lense system - not sure how it would look but happy to have a look! :)

**Comment by oharaandrew314** [comment]
Agreed; both of those are near necessities.

**Comment by oharaandrew314** [comment]
I have the `Lens` integration working nicely, I'm not certain I can nicely implement `AutoMarshalling`, because CSV implies marshalling of lists.  Technically, you could marshal a single element, but then switching between single-element and list mode would be weird.  Unfortunately, it's not quite as simple as letting Jackson's `ObjectMapper` handle the heavy-lifting, because you have to create readers and writers with schemas first, and they require you to know whether you are working with single elements or lists.

**Comment by oharaandrew314** [comment]
@daviddenton PR submitted #719

**Comment by daviddenton** [comment]
Cool. Let's start with this and see how we go. Thanks!  🙃
