### ISSUE TITLE
Additional Standard Mappings

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#720]
I'd like to propose additional standard mappings to `AutoMappingConfiguration`.

- java.util.Locale
- java.time.ZoneId
- java.time.ZoneOffset

I can follow up with a PR if accepted.  Thoughts?

**Comment by daviddenton** [comment]
Yep - very happy for these to be added. Can you please add them to the lens mappings (and StringBiMappings as well) so they are inherited everywhere?
