### ISSUE TITLE
Static content serving using `static` does not support JavaScript source maps

### ISSUE THREAD

**Issue by andrewmcnamara** [http4k/http4k#732]
JavaScript source maps are generally of the format `application.js.map`.  

With a static routing configuration as below

```Kotlin
   static(Directory("src/main/resources/public"))
```    

When the browser requests this file from the `http4k` server, the server responds with a `404`.

Tracing through the `ResourceLoadingHandler`  at
https://github.com/http4k/http4k/blob/1f0cd24d8ab74ea1503fa78313f356c18ae4b543/http4k-core/src/main/kotlin/org/http4k/routing/static.kt#L54-L60

Because the file has 2 extensions - it will use the last extension `map` - which doesn't have a supported mime type.
https://github.com/http4k/http4k/blob/1f0cd24d8ab74ea1503fa78313f356c18ae4b543/http4k-core/src/main/kotlin/org/http4k/core/MimeTypes.kt#L9-L12

I have managed to workaround this by passing `Pair("map", ContentType.APPLICATION_JSON)` as a `extraFileExtensionToContentTypes` on the static method.

Is this the expected behaviour?

**Comment by daviddenton** [comment]
Yep - it's pretty much working as expected. There is a mime.types file which contains the standard mappings - we could add the file in there, but I'm not sure that it's unique to js map files so investigation would need to be done.

Closing this off for now :)
