### ISSUE TITLE
RoutedRequest - uri host and scheme are empty

### ISSUE THREAD

**Issue by andrewmcnamara** [http4k/http4k#734]
I am working with a library that needs the host and scheme for generating redirects. Debugging the request object shows its a `RoutedRequest` 

https://github.com/http4k/http4k/blob/d56978c1d05ca9a28b90e617b9e5163a7f166284/http4k-core/src/main/kotlin/org/http4k/routing/messages.kt#L20

This has a `uri` method - unfortunately this does not include  `host` nor the `scheme` that is needed. 

```
result = {Uri@10649} /some-url
 userInfo = ""
 host = ""
 port = null
 path = "/some-url"
 query = ""
 fragment = ""
 authority = ""
 ```
 
Should these be set ? If not what is the best way to get these values.

Thanks

**Comment by daviddenton** [comment]
there is no **guaranteed** way of getting this information - for a start the host and protocol are not generally provided from the incoming request by the various server libs. 

It's possible you could get the data from the incoming request via headers but that depends on the various proxies inbetween the user and your app and where it's deployed etc. "Origin", "X-forwarded-host" are options as a starting point, as well as any infra specific ones that might get added.

If you're using the location header, you might be able to get away with just a path (check the spec), but the simplest thing really is to configure this information in the deployment of your app as you presumably know it at deploy time?

**Comment by s4nchez** [comment]
That was a conscious decision early on, as it's common that servers live behind proxies/gateways, which modify those request attributes and are prone to introducing bugs in your application. Proxies usually introduce `Host`, `X-Forwarded-Host/Port/Proto` headers too, and it's up to the application to interpret those.

There's the added security concern for redirects and how [redirect data coming from the client should be validated](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html). 

So, in general, redirect info is provided by the client as a query parameter or a value stored in the server to avoid being caught by network configuration and make it easy for the server to validate those.

Please let us know if you have a special use case though, as I'd be curious to learn about it. Also, bear in mind that we'll only consider adding this if it's something available consistently across most server implementations (jetty/undertow/apache/etc)

**Comment by s4nchez** [comment]
Seems like @daviddenton beat me to this one! 😆

**Comment by andrewmcnamara** [comment]
@s4nchez  @daviddenton 
Thanks for the detailed response/explanation about the current implementation. Totally makes sense to me.

To give you a little more background around why I asked the question, I am adding support for SAML to our http4k application.  From my initial investigation it looks like there are only a handful of Java libraries that provide support. The best library for saml (most active/used ) is  [java-saml](https://github.com/onelogin/java-saml) from One Login.  This library provides a nice interface for an implementation the SAML login flow, with one caveat :
> java-saml-core uses HttpRequest class, a framework-agnostic representation of an HTTP request.
>
> java-saml depends on javax.servlet:servlet-api, and the classes Auth and ServletUtils use HttpServletRequest and HttpServletResponse objects.
>
> If you want to use anything different than javax.servlet.http, you will need to reimplement Auth and ServletUtils based on that new representation of the HTTP request/responses.

Which is the case with `http4k`. It would be nice if the api took an agnostic interface but it from this [issue](https://github.com/onelogin/java-saml/issues/113) it looks like the above statement is the preferred way.  To avoid rewriting these classes or using Bytecode manipulation, I cheated by writing class that implemented the  `javax.servlet.http.HttpServletRequest` interface using the `RoutedResponse` hence the question of the `host`.  This did work - but it felt terrible. So I am now back to rewriting those classes.

To your point about 
>but the simplest thing really is to configure this information in the deployment of your app as you presumably know it at deploy time?

We do this for other redirects, so I will just reuse this value  for SAML redirects.

**Comment by daviddenton** [comment]
Am going to close this off as seems to be done. Feel free to reopen if required. 😄
