### ISSUE TITLE
Etag filter is broken: prevents content from being sent from the server

### ISSUE THREAD

**Issue by stevebakh** [http4k/http4k#738]
The Etag filter was previously broken, using the response from `toString` to generate the hash.

An attempt to fix this was pushed in commit: 4f1491f5ad2cdd09b1e7a8d94ab97d3f581966bf

A subsequent commit simplified the code (but left it still in a broken state): 5a8d989859bfa4e863b4adc534dbea967474387d - reading the byte array in this way moves the pointer and results in the HTTP response containing a valid Etag, but a 0 length payload!

**Comment by daviddenton** [comment]
Whoop! Thanks for letting us know. We'll fix it

**Comment by stevebakh** [comment]
I don't think the proposed change fixes the issue. The problem is that the input stream is being read and the pointer not reset (and looking at the code, these input streams don't support reset).

I'm guessing there are no automated tests around this functionality, as the code will return a 0-length payload in the HTTP response (with a correct Etag at least)?

**Comment by daviddenton** [comment]
We could read the entire content into memory and then write it back out again in the filter chain response?

**Comment by stevebakh** [comment]
If it helps, this is the cheap workaround I've put in place to test something, and it works as expected, but I'm not sure how performant this solution is:

```
val payload = response.body.payload.array()
val hashedBody = md5().digest(payload).joinToString("") { "%02x".format(it) }
response.header("Etag", hashedBody).body(ByteArrayInputStream(payload))
```

Note the need to set the response body again at the end. :(

**Comment by daviddenton** [comment]
With a stream there isn't much option really - we need the entire thing in memory so that we can calculate the tag

If you've got time to PR it then we'll happily merge :)

**Comment by jshiell** [comment]
Please, don't inspect streams. This is _hugely_ risky for any large stream, as it'll force it into memory - and that's **bad** for some of our streams.

I don't believe there's any generic way to generate an eTag for streamed content - it'll need to be done by the application in a context specific manner (e.g. getting it from an upstream, or storing the etag somewhere for retrieval at delivery time).

**Comment by daviddenton** [comment]
so what is our preferred option for a stream? We either 1. do nothing - which seems weird, 2. throw up, 3. JFDI and assume people know not to add the filter to streams 😄 

I'm not sure there is a good solution really.

**Comment by jshiell** [comment]
I think (1) is correct, as you want the filter to be applied to in-memory bodies, and you don't want it to break streams. Log a warning if you must. 

Throwing up seems daft as you now need separate stacks for in-memory and streaming. Ditto three, you've now broken streams with _very_ nasty side-effects.

**Comment by daviddenton** [comment]
Am happy to go with that - once again - I'll happily merge it if someone has the time to PR it now

**Comment by jshiell** [comment]
Hmm. Why do we have both [ETagSupport](https://github.com/http4k/http4k/blob/55a88492f10b01a18d8ed0a1d7a97f2e5b86b192/http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt#L139) and [AddETag](https://github.com/http4k/http4k/blob/4a63ffacc0318dbbd59289329ec06156659e181c/http4k-core/src/main/kotlin/org/http4k/filter/CachingFilters.kt#L102)?

`ETagSupport` seems to support this already, along with preset etags, and also handles a matching ETag.

**Comment by stevebakh** [comment]
James, are you suggesting that the framework shouldn't provide Etag support at all, and leave it down to applications to implement their own filter for this?

The `Body` type is just an interface with a bunch of different implementations. I haven't traced through the code, so I'm not sure which implementation (stream or otherwise) is being used for returning file assets such as images, CSS files, JS files, etc. Maybe we don't need to generate a hash of the whole payload for the ETag. Could we favour a mix of file length and other attributes? Perhaps return a "weak etag"?

**Comment by jshiell** [comment]
@stevebakh nope, I'm suggesting that the framework should never break a stream, even if that means it cannot add etags. Given we don't know the context, I'd be _very_ wary of adding even a weak tag to a stream - I think this is a case that needs to be addressed by the app dev.

But we should certainly add them for in-memory responses, and handle 304s where we match. 

I think we should delete `AddETag` in favour of `ETagSupport`. Looking at the history, it looks like some handsome fellow contributed `EtagSupport` as a fuller implementation of handling, but `AddETag` was never deleted. Probably because Dave has it in for me 😁

**Comment by stevebakh** [comment]
Ah haha! Yes, agreed on Streams (as a general rule). I can see that ETagSupport checks the implementation and skips applying it to streams.

The downside in our specific case is that the asset files we want to generate etags for (css, js, images, etc) are returned as stream bodies.

**Comment by jshiell** [comment]
My only suggestion there is to pre-generate them and store them with the files, e.g. as part of the build process. Then you can just read them when generating the response.

Or you could break the streams, compute them, and then store them in memory for re-use, but depends on the size of your resources as to practicality I fear.

**Comment by stevebakh** [comment]
For sure - pre-generating is an option (one approach being investigated right now is using node to generate the hashes at build time and applying them to the URLs to avoid needing ETags altogether - an approach I'm not particularly keen on for a few reasons). I will see if there are any other useful attributes I can make use of to generate a "weak" ETag. File length obviously won't be available for the stream bodies, but maybe there's something else. 

In any case, I agree - seems strange to have both AddEtag and ETagSupport. I would vote for deleting AddEtag.

**Comment by aSemy** [comment]
Oops, my bad, sorry for breaking it! I did add some tests to check that the body was still usable, but apparently they didn't work.

Can `DigestInputStream()` be used to add an ETag for a streaming body? https://stackoverflow.com/a/52160340/4161471

**Comment by daviddenton** [comment]
The problem with this is that we wouldn't know the overall digest until the entire stream had been read - which would mean that we need to put the eTag in an HTTP trailer (like a header but comes after the body).  Which we don't support :)

**Comment by daviddenton** [comment]
I've deprecated the eTag filter in favour of eTagSupport, so I think we're done here as far as http4k is concerned?
