### ISSUE TITLE
JacksonFieldMetadataRetrievalStrategy is incompatible with kotlinx.serialization @Serializable classes

### ISSUE THREAD

**Issue by krissrex** [http4k/http4k#750]
Introduced in: #467 #687 

The implementation uses the first constructor found:
https://github.com/http4k/http4k/blob/115d4cb0ff3643bd1e2fec41ecac3806431b0d80/http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/jacksonExt.kt#L82

However, a class annotated with `@Serializable` gets an extra constructor, and the code picks this one first.

```kotlin
@kotlinx.serialization.Serializable
data class ExampleDto(
    // This annotation DOES NOT WORK if you use kotlinx.serialization @Serializable on this class.
    @JsonPropertyDescription("The unique id for this entity")
    val id: String
)
```

REPL output:
```kotlin
 val size = ExampleDto::class.constructors.size
 val metadata = JacksonFieldMetadataRetrievalStrategy.invoke(ExampleDto("1"), "id")
 println("There are $size constructors and the metadata is ${metadata.extra}")
```

`There are 2 constructors and the metadata is {}`

If I remove only the `@Serializable` annotation and run the same code, I get this output:
`There are 1 constructors and the metadata is {description=The unique id for this entity}`

**Comment by daviddenton** [comment]
Interesting. As an aside, you can manually create the open API renderer instance and omitting the offending class from the list.
