### ISSUE TITLE
GraphQL explorer for http4k-graphql

### ISSUE THREAD

**Issue by arnabkd** [http4k/http4k#753]
**GraphQL explorer endpoint**

It would be nice to have a graphical IDE for developers to try out there code and explore the graphql endpoint one creates. [ktor-graphql](https://github.com/excitement-engineer/ktor-graphql) has this functionality, which can be used like so:

```
val server = embeddedServer(Netty, port = 8080) {
    routing {
        graphQL("/graphql", schema) { request ->
            Config(showExplorer = true)
        }
    }
}
...
```

I get that http4k is simplistic and minimalist at it's very core, and I respect that. If this feature contradicts that, feel free to close. I do feel that this will provide some very handy functionality :)

**Comment by razvn** [comment]
We just add a static endpoint with [GraphQL-playground](https://github.com/graphql/graphql-playground) html page. 
Not sure it needs to be packed by the library.

**Comment by daviddenton** [comment]
It would be trivial to make a reusable route module which serves a static HTML file from the resources folder and contains the playground content. It won't even add more dependencies so we can just ship it with the existing graphql module

**Comment by arnabkd** [comment]
> We just add a static endpoint with [GraphQL-playground](https://github.com/graphql/graphql-playground) html page. Not sure it needs to be packed by the library.

Not really a question of "need" per se, as this can always be resolved by putting the playground in the frontend or even by using a standalone graphql ide. It's more a question of convenience.

**Comment by daviddenton** [comment]
If someone wants to PR this into the graphql module with no additional.dependencies then we can ship it 🙃

**Comment by arnabkd** [comment]
@daviddenton : Added a PR now. This is my first time contributing to http4k, so I am unsure what the expectations are :)

**Comment by daviddenton** [comment]
Fixed for next release.
