### ISSUE TITLE
Would love a Java example

### ISSUE THREAD

**Issue by fzakaria** [http4k/http4k#77]
I think the docs or the code would benefit greatly from a pure java (JDK8+) example.
I like the framework a lot but curious to see how it _feels_ in a pure java codebase.

**Comment by s4nchez** [comment]
Hi @fzakaria,

I can't recommend using http4k from Java yet as we have focused solely on Kotlin and haven't added all necessary JVM annotations and helper classes to make its API more friendly to be used in this context.

Having said that, we do have a branch (called `java`) with some experiments in that area, and here's the best starting point: https://github.com/http4k/http4k/blob/e0f390bada0c9feb93f222ee6a703787c43a9eed/src/test/java/org/http4k/java/Http4kJavaCompatibilityTest.java

I'd love if you could provide some feedback on that code, as it shows how it'd _feel_ to use http4k from Java and would help us consider supporting it in the future. 

Unfortunately, although the Java interop with Kotlin is great, it still doesn't come for free as we'd have to make sure all existing and new features would work well in Java codebases...

**Comment by fzakaria** [comment]
I started a _soft fork_ with the ideas of having a Java first library -- which I've committed here: 
https://github.com/fzakaria/http4j as a means of experimenting with similar functional interfaces for Java codebases

http4k codebase is a great inspiration btw.
