### ISSUE TITLE
Body Properties lens

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#781]
It's common for the iot devices I work with to use a body format compatible with java properties file.  I've made my own lens to support this, but I wonder if there's any interest in adding it to `http4k-core`.  Something like

```fun Body.Companion.javaProperties(quoteChar: Char? = null): BiDiBodyLensSpec<Map<String, String>>```
or
```fun Body.Companion.javaProperties(quoteChar: Char? = null): BiDiBodyLensSpec<Properties>```

**Comment by daviddenton** [comment]
Yep. If it's useful! 🙃

**Comment by oharaandrew314** [comment]
Well, utility is in the eye of the beholder, and I think I'd rather not help propagate lazy API design.  I'm going to close this and keep my custom lens in the dungeon, where it belongs.
