### ISSUE TITLE
Allow setting of restricted HTTP request headers through a known configurable property established in Java 12

### ISSUE THREAD

**Issue by gilgaxiola** [http4k/http4k#782]
Hello,
It seems http4k's implementation of [JavaHttpClient](https://github.com/http4k/http4k/blame/master/http4k-core/src/main/kotlin/org/http4k/client/JavaHttpClient.kt#L70) doesn't allow a set of restricted [HTTP request headers](https://github.com/http4k/http4k/blame/master/http4k-core/src/main/kotlin/org/http4k/client/JavaHttpClient.kt#L94) to be allowed via a configurable networking or system environment property

Since Java12, there is a known property to allow restricted headers: **jdk.httpclient.allowRestrictedHeaders**
Sources
https://stackoverflow.com/questions/52315472/how-to-customise-host-header-in-java-http-client
https://bugs.openjdk.org/browse/JDK-8213696

**Comment by gilgaxiola** [comment]
[Current implementation in OpenJDK](https://cs.github.com/AdoptOpenJDK/openjdk-jdk/blob/9d8ad2ed62325bd8d813974d5aa1e031ed8bf8da/src/java.net.http/share/classes/jdk/internal/net/http/common/Utils.java#L138)

**Comment by s4nchez** [comment]
@gilgaxiola do you have a specific use case where this is a problem? 

We could make this behaviour configurable. However, we're mindful of adding features that only work in specific JDK versions as we don't run the build on every version available.

**Comment by gilgaxiola** [comment]
The typical use case for Host Header injection is cloud hosting (similar to Apache's HTTP Client and their virtual host)


Use this if you have multiple domains tied to a service and want them all served by the same origin,
If http4k needs to be compatible with different LTS versions of the JDK, then we can find a way around it.
Just mentioning the fact that for JDKs 12+ (17 being the latest LTS), there is a developer property that allows us to test calls on behalf of the
