### ISSUE TITLE
AccessTokenDetails is not serializable anymore

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#787]
With this commit:

https://github.com/http4k/http4k/commit/a9af26cd8a748364c3e9a4861615b1b2ec94455e

AccessToken became essentially not serializable - before, the `AccessTokenDetails` could be serialized and deserialized with jackson. Now it fails with:

> Cannot construct instance of `org.http4k.security.AccessToken` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information

Is there a reason why this was changed?

**Comment by daviddenton** [comment]
Yes - it was deliberately changed in order to be able to vary the implementation of AccessToken across different implementations (the AccessToken interface represents the bare minimum of the JSON payload).

AccessTokenDetails was never designed to be serialised - it's an intermediate object only,.
