### ISSUE TITLE
AWS calls result in invalid signature

### ISSUE THREAD

**Issue by digitalsanctum** [http4k/http4k#79]
I tried http4k for the first time by following the AWS guide here: https://www.http4k.org/guide/modules/aws/

Using known good credentials I got an invalid signature error.

**Comment by daviddenton** [comment]
Thanks for the report. Will check it out - can you confirm that you literally used the example code in the aws example, just replacing the keys?

**Comment by daviddenton** [comment]
@digitalsanctum I've worked out that the example was incorrect - the name of the service for S3 was incorrectly capitalised, so it should read:
```
   val service = "s3"
```

That works with my S3 credentials. Can you retry it with that fix in place and confirm that it's working for you? (I've updated the example and it's building the new site now)

**Comment by digitalsanctum** [comment]
Confirmed. Thanks for the quick turnaround
