### ISSUE TITLE
Structuring events

### ISSUE THREAD

**Issue by ChA0S-f4me** [http4k/http4k#794]
I need event struct like
```json
{
  "type": "join"
  "data": {
    "val1": "text"
    "val2": 12
  }
}
```

But `data` data should depend on `type` value. How to realize it? (I using moshi)

**Comment by daviddenton** [comment]
This is a question for the Moshi folks, as http4k just uses it directlyunder the hood. You will need to register a custom adapter when constructing your Moshi instance.

Here is an example of annadapter you can use to provide this behaviour

https://github.com/square/moshi/blob/484d525db44f7d7b1c5a6f6f30008b12f405e1e4/moshi-adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java

Good luck!
