### ISSUE TITLE
WebSocket sending Binary package with every message

### ISSUE THREAD

**Issue by ChA0S-f4me** [http4k/http4k#795]
![image](https://user-images.githubusercontent.com/36239195/194712395-c7f71ff0-c4ae-4715-869a-6c142748fe72.png)
What the *`Binary`* message?

**Comment by daviddenton** [comment]
I'm.afraid we are going to need more information or context to be able to help. Can you put together a Gist showing us the problem?

**Comment by ChA0S-f4me** [comment]
> I'm.afraid we are going to need more information or context to be able to help. Can you put together a Gist showing us the problem?

https://gist.github.com/baf36cbc8cb96b79a9acace76c1b97fc

**Comment by oharaandrew314** [comment]
I'm not sure what exactly your screenshot is showing, but every WebSocket frame starts with a control byte to describe the type of frame.  Could that be what you're seeing?

Does the problem persist if you use a different server backend, like netty?

**Comment by ChA0S-f4me** [comment]
> I'm not sure what exactly your screenshot is showing, but every WebSocket frame starts with a [control byte](https://www.openmymind.net/WebSocket-Framing-Masking-Fragmentation-and-More/#:~:text=A%20WebSocket%20frame%20can%20be,not%20it's%20a%20fin%20frame.) to describe the type of frame. Could that be what you're seeing? Maybe your viewer is showing more than just messages, and is also showing control frames, like `ping`.
> 
> Does the problem persist if you use a different server backend, like netty?

Oh, it worked when I changed backend to Netty, thanks

**Comment by oharaandrew314** [comment]
Ok, I'm glad that fixed it for you.  We might want to open a related issue to fix whatever jetty-specific issue there was.

**Comment by tamj0rd2** [comment]
Switching to Undertow resolved this issue for me
