### ISSUE TITLE
CircuitBreaker counts error twice, once as an error and once as a success

### ISSUE THREAD

**Issue by andrewmclelland** [http4k/http4k#804]
I'm using http4k-resilience4j at version 4.32.2.0 and noticed that the circuit breaker was opening before the minimum number of calls and that it was impossible to achieve a failure rate of over 50%. I believe the issue is in [line 37 of the ResilienceFilters object](https://github.com/http4k/http4k/blob/master/http4k-resilience4j/src/main/kotlin/org/http4k/filter/ResilienceFilters.kt#L37) where onResult runs even if onError has already ran. This results in the error being recorded twice - once as an error and then again as a success.

My CircuitBreakerConfig is the same as in the [example](https://www.http4k.org/guide/reference/resilience4j/) and with the below config I am seeing the breaker open after just two bad requests instead of waiting for at least 4 total requests.

```
private fun defaultTestingCircuitBreakerConfig() = CircuitBreakerConfig.custom()
        .slidingWindow(10, 4, CircuitBreakerConfig.SlidingWindowType.COUNT_BASED)
        .permittedNumberOfCallsInHalfOpenState(2)
        .waitDurationInOpenState(Duration.ofSeconds(1))
        .build()
```

**Comment by daviddenton** [comment]
Thanks for the report. I think it might just be a case of changing line 37 to:

```kotlin
                        if (isError(this)) cb.onError(0, MILLISECONDS, CircuitError)
                        else cb.onSuccess(cb.currentTimestamp - start, cb.timestampUnit)
```

WDYT - this passes our modified test - can you check it against your assumptions?

**Comment by andrewmclelland** [comment]
Yeah that looks good, thanks
