### ISSUE TITLE
How to make nested route in contract?

### ISSUE THREAD

**Issue by ChA0S-f4me** [http4k/http4k#806]
I have `/api/v1` route that binded to `contract`, in contract I need `/auth/register` and `/auth/login` paths. How to nest it in the `contract`? I didn't find this (nested route in contract) in docs

**Comment by daviddenton** [comment]
You can nest a contract inside a routes block, but you cannot nest contract routes within a contract. So this works:
```kotlin
        routes(
            "/api/vi" bind contract {
                routes += "/auth" bindContract Method.GET to { Response(OK) }
            }
        )
```

**Comment by daviddenton** [comment]
May I suggest that you join the [Kotlin Slack](kotlinlang.slack.com) #http4k channel to engage with the community directly? They are all very friendly 😄

**Comment by ChA0S-f4me** [comment]
> You can nest a contract inside a routes block, but you cannot nest contract routes within a contract. So this works:
> 
> ```kotlin
>         routes(
>             "/api/vi" bind contract {
>                 routes += "/auth" bindContract Method.GET to { Response(OK) }
>             }
>         )
> ```

But I need more than one path (they'll with different methods also) after `/auth`

**Comment by daviddenton** [comment]
Yes - `but you cannot nest contract routes within a contract.` - there is only one level and they have to be specified individually.

```
routes(
            "/api/vi" bind contract {
                routes += "/auth1" bindContract Method.GET to { Response(OK) }
                routes += "/auth2" bindContract Method.POST to { Response(OK) }
            }
        )
```

**Comment by ChA0S-f4me** [comment]
Do you planning add support for this feature?

**Comment by daviddenton** [comment]
No 🙃

**Comment by ChA0S-f4me** [comment]
> No 🙃

Why? This will very helpful feature

**Comment by ChA0S-f4me** [comment]
eg for making backend API routes (like in my case)

**Comment by s4nchez** [comment]
> Why no? This will very helpful feature

@ChA0S-f4me we don’t doubt that. However, this is an open source project and we favour implementing things that we or our paying clients need.

We’re always open to contributions though. They can be in the form of pull requests or sponsorship. Both help us increase our ability to add more community-requested features such as the one above.
