### ISSUE TITLE
How to implement snapstart with http4k

### ISSUE THREAD

**Issue by AndreVelde** [http4k/http4k#826]
Currently I am using graalvm and wanted to test out the new snapstart feature from AWS.
Only problem is that I can't use the environment variables like I used to do with:
`S3Bucket.Http(bucketName = BUCKET_NAME, bucketRegion = REGION, http = OkHttp())`

Since in the `Http` method the credentialsProvider gets the AWS credentials from the environment: `credentialsProvider: CredentialsProvider = CredentialsProvider.Environment(env)`. But this is not possible for snapStart.
So was wondering if I am overlooking a way to do this or if this still needs to be implemented?

**Comment by s4nchez** [comment]
Hi @AndreVelde. 

We haven't added explicit support or examples for snapstart in http4k.

 If you have suggestions (or even better, a PR!) for how to best support this, please let us know.

**Comment by daviddenton** [comment]
A couple of things that would be great to clarify:

1. Why can't you use Environment properties (sorry - I'm not familiar with any new restrictions that snapstart brings). Is there a new way of resolving properties in lambdas? Aren't they just passed to the lambda in the same map when you create it?
1. Assuming 2 is "a thing", you can provide a different implementation of the CredentialsProvider interface to all of the http4k-connect adapters. The environment one is just the default.

**Comment by AndreVelde** [comment]
You can't use IAM with snapstart so AWS won't provide those credentials. This is probably because they won't be up-to-date later on. A colleague from me has got it working with the default AWS library and he had to remove the explicit credentials provider in it to get it working.

**Comment by daviddenton** [comment]
In the SDK there are various ways which AWS "fallback to" in order to provide seamless auth (although personally we think this is a terrible idea which is why we haven't done it in connect. 

The currently favoured way of authing is using STS and a rotating web identity file on disk (basically a JWT which is then swapped for a bunch of AWS credentials). Have a look in the [connect STS](https://github.com/http4k/http4k-connect/tree/master/amazon/sts/client/src/main/kotlin/org/http4k/connect/amazon/sts) module for the CredentialsProviders in there and see if there is anything that looks familar. 

Unless they have introduced a new way of authing in the SDK that we're not aware of then I suspect this won't be too hard to get working - we just need to find out what the magic is!

**Comment by daviddenton** [comment]
What would be really handy @AndreVelde is if you could ask your colleague what the value was of the the environment property AWS_CONTAINER_CREDENTIALS_FULL_URI  (which is passed in). For the "old" container credentials, they used to just pass in AWS_CONTAINER_CREDENTIALS_RELATIVE_URI which was then suffixed to the URI `http://169.254.170.2` (random but true!).

**Comment by harmen1994** [comment]
Hello @daviddenton,

Thank you so much for looking in to this and explaining what the current implementation is. 

Yesterday I did `echo $AWS_CONTAINER_CREDENTIALS_FULL_URI` in CloudShell I get the following value: http://localhost:1338/latest/meta-data/container/security-credentials.

Today I also wanted to test this in the SnapStart Lambda as this environment is what we're debugging. There we had the following response.
`AWS_CONTAINER_CREDENTIALS_FULL_URI=http://127.0.0.1:9001/2021-04-23/credentials`

Together with the _AWS_CONTAINER_AUTHORIZATION_TOKEN_ variable as Authorization header I expect the Lambda being able to get STS credentials. If you want I could test that as well.

**Comment by daviddenton** [comment]
One question is about the value of AWS_CONTAINER_AUTHORIZATION_TOKEN... is it used as the entire Auth header value or should it be prefixed with "Basic"?

We're going to change the http4k-connect container credentials module to support this new method, but the answer to the above question would be great...

**Comment by harmen1994** [comment]
This code results in a successful response.
```
        var request = Request(Method.GET, System.getenv("AWS_CONTAINER_CREDENTIALS_FULL_URI"))
            .header("Authorization", System.getenv("AWS_CONTAINER_AUTHORIZATION_TOKEN"))
            .use(OkHttp()).body.payload.asString()
```
Response:
```
{"AccessKeyId":"KEYID","SecretAccessKey":"RANDOMSECRETKEY","Token":TOKEN","Expiration":"2022-12-08T22:50:04.161Z"}
```

**Comment by s4nchez** [comment]
The new version of `http4k-connect` (3.25.5.0) now supports Container Credentials which can be used within Lambdas with Snapstart. Here's an example:

```kotlin
    val environment = Environment.ENV
    val bucketName = EnvironmentKey.string().map(BucketName.Companion::of).required("BUCKET")(environment)
    val region = EnvironmentKey.string().map(Region.Companion::of).required("AWS_REGION")(environment)
    val credentialsUri = EnvironmentKey.uri().required("AWS_CONTAINER_CREDENTIALS_FULL_URI")(environment)
    val token = EnvironmentKey.required("AWS_CONTAINER_AUTHORIZATION_TOKEN")(environment)
    
    val credentials = ContainerCredentials.Http(token = ContainerCredentialsAuthToken(token))
        .getCredentials(credentialsUri)
        .onFailure { error("Could not get credentials ${it.reason}") }
        .asHttp4k()

    val bucket = S3Bucket.Http(bucketName, region, { credentials })
```

We've checked it in AWS, and it works, so we're closing this issue. 

Thank you all for reporting this issue and contributing to its solution 😄

**Comment by harmen1994** [comment]
Wow that is really great, thank you so much! Will test it after the weekend and report back with the cold start improvement metrics 😃.
