### ISSUE TITLE
How to access the AWS API Gateway properties besides the body parameter? 

### ISSUE THREAD

**Issue by drissamri** [http4k/http4k#832]
Working with AWS API Gateway and Lambda you normally two objects when the Lambda is invoked the event/request and a Context object. Here is an example of the request object format: https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-example-event 

How can you access all properties of the request object like `event.requestContext. ...`? 
When using an Authorizer you can add extra context properties under the `event.requestContext.authorizer.<KEY>` like user email, name, ... and others. 

Is this already supported in the framework or is this currently not exposed?

**Comment by daviddenton** [comment]
The request context is attached to the request using a RequestContext. You can get it using this code: 

```kotlin
class TestFunction : ApiGatewayV2LambdaFunction(
    AppLoaderWithContexts { env: Map<String, String>, contexts: Store<RequestContext> ->
        val key = RequestContextKey.required<Context>(contexts)

        (
            { req: Request ->
                val context: Context = key(req)
                Response(OK).body(context.awsRequestId)
            }
        )
    }
)
```

Closing this, but reopen if required.

**Comment by drissamri** [comment]
Thanks for your fast response @daviddenton, this covers the Context object but not the full request object I guess? Since there's other info in the request object that's not in the context object

**Comment by daviddenton** [comment]
Sorry - it wasn't quite right. But we do actually store both in the request. I've fixed the code above - it's a bit unclean (with the !!), but it will work.

Of course, the problem here is that it becomes more difficult to test locally.
