### ISSUE TITLE
Status.UNKNOWN_HOST and Status.CONNECTION_REFUSED compare equal

### ISSUE THREAD

**Issue by mikaelstaldal** [http4k/http4k#845]
Try this:
```
import org.http4k.core.Status
fun main() {
    println(Status.SERVICE_UNAVAILABLE == Status.UNKNOWN_HOST)   // correct
    println(Status.UNKNOWN_HOST == Status.CONNECTION_REFUSED)    // wrong 
}
```
Gives:
```
false
true
```
The reason is that they have the same `code` (503) and both are `clientGenerated`.

**Comment by daviddenton** [comment]
This behaviour is as designed. 😄 

The idea was to encapsulate and communicate different reasons for client side 503s - which are our invention to avoid throwing exceptions out of our HTTP clients - this happens inconsistently across the various HTTP clients we support. 

From a client perspective, there isn't much difference between a standard 503, an unknown host and a connection refused - they both can be transient (for different reasons OFC) and any fallback behaviour would be the same in the vast majority of cases.

If you really need an explicit equality check which includes the description, if should be trivial to add where required, or we could consider to PR it in (if we can come up with a decent name 😉 )
