### ISSUE TITLE
Swagger UI Webjar Helper

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#859]
Http4k supports two ways of rendering a Swagger UI:

**Method 1: swaggerUI function from http4k-contract**

The `swaggerUi` function built into `http4k-contract` generates an HTML document, and loads all the static assets from the public Swagger UI CDN.  This is simple, and excellent for lambdas.  However, it has some issues:

- Sometimes the CDN has degraded performance, which can significantly delay loading the UI
- In order for OAuth redirects to work, a large portion of swagger-ui code had to be copied; this can easily get out of date

**Method 2: Webjar**

Http4k has support for webjars, which allows you to bundle the swagger UI assets into your application, breaking the necessity for public internet access in the browser, and ignoring the public CDN stability issue.

However, Swagger UI has disabled the `url` query parameter, which is required to render the spec of your local application.  There is apparently a config option to [enable query parameters](https://github.com/swagger-api/swagger-ui/issues/5275#issuecomment-1128067295), but I'm not sure if this is possible when served by webjar.  I would be happy to be proven wrong with a recipe.  The only workaround I know of is to write your own HTML document that references the static assets from the local server.

**Proposal**

As a workaround, I propose a new hybrid approach.  Http4k would need a new `http4k-contract-swaggerUi` module that provides the swagger-ui webjar, and provides a `swaggerUi` function that serves the same HTML document as method 1, but pointing to the local 
server's webjar assets, rather than the public CDN.

Unfortunately, this would require a completely new module for something that could feasibly be accomplished with a new recipe in the docs.  It would however, eliminate a peeve of mine: which is having to coordinate the version of the webjar dependency with the path to the static assets.

Could this be worth adding a new module for?

**Comment by s4nchez** [comment]
Hi @oharaandrew314 

We believe having a `http4k-contract-swagger-ui` module for the use case you described makes sense. We could expand this pattern for other ways to expose API-related documentation/tools, such as [redoc](https://github.com/Redocly/redoc).

**Comment by s4nchez** [comment]
We're probably not working on that area in the near future, so feel free to propose a PR for the new module if you need it immediately.

**Comment by oharaandrew314** [comment]
Yeah, I can make the modules myself.

How should the new modules be structured?  Does http4k-contract need to be
moved into a core module and have the new modules be siblings of it?  Or
will they be child modules: nested inside the contract module?

**Comment by oharaandrew314** [comment]
I of course want to make the original `http4k-contract` module to have the same artifact name, while conforming to the nested architecture of modules like `http4k-security` and `http4k-format`.

**Comment by s4nchez** [comment]
I believe for now the simplest path would be adding `http4k-contract-swagger-ui` at the root level next to `http4k-contract`. 

I wouldn't create the nested structure for it yet as we have the convention of module name == artifact name and rather not have to create workarounds to keep compatibility. We can potentially change that and make an incompatible change for http4k v5 instead.

@daviddenton what do you think?

**Comment by daviddenton** [comment]
Sorry - this dropped off my radar. Let's keep it at the top level. I also want to get a redoc version in as well as the latest Swagger UI still doesn't support the latest version of the OpenApi spec.

**Comment by jhult** [comment]
Related PR: https://github.com/http4k/http4k/pull/864
