### ISSUE TITLE
Question: Is it possible to allow a body in the HTTP delete method?

### ISSUE THREAD

**Issue by averri** [http4k/http4k#860]
I have noticed that the library is not sending the body when I attach one to the HTTP delete methods.

I also know that it's not common to send an HTTP delete with the body, but that should be possible.

How to enable the body in the HTTP delete methods?

**Comment by daviddenton** [comment]
This won't be the library - we make no distinction based on method. It will be the http client underneath. Which one are you using, and maybe try switching to another?

**Comment by averri** [comment]
Hi @daviddenton, the client underneath is the `org.apache.hc.client5.http.impl.classic.CloseableHttpClient`.

Here is how I'm initializing it:

```kotlin
import org.apache.hc.client5.http.config.RequestConfig
import org.apache.hc.client5.http.cookie.StandardCookieSpec
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient
import org.apache.hc.client5.http.impl.classic.HttpClients

val defaultHttpClient: CloseableHttpClient = HttpClients.custom()
    .setDefaultRequestConfig(
        RequestConfig.custom()
            .setRedirectsEnabled(true)
            .setCookieSpec(StandardCookieSpec.RELAXED)
            .build()
    ).build()


val defaultHttpHandler: HttpHandler by lazy {
    ApacheClient(defaultHttpClient)
}
```

Do you have a suggestion for another client that accepts a body in the delete method?

**Comment by averri** [comment]
I have tested http4k using OkHttp and the library accepts delete methods with the body. :)
