### ISSUE TITLE
Replace `meta { }` block with `RouteMeta` object?

### ISSUE THREAD

**Issue by bartkummel** [http4k/http4k#861]
Hi,

I'm evaluating http4k for a project. It's an API with lots of different endpoints. I will need OpenAPI docs, so using the contract module. However, I like to keep each endpoint in it's own class, along with all configuration. Something like this:
```kotlin
interface Endpoint {
    fun path(): String
    fun method(): Method
    fun handler(): HttpHandler
}

object HealthEndpoint : Endpoint {
    override fun path(): String = "/health"

    override fun method(): Method = GET

    override fun docs(): RouteMeta = RouteMeta(
        summary = "Health endpoint for ECS.",
        tags = setOf(healthTag),
    )

    override fun handler(): HttpHandler = {
        Response(Status.OK)
    }
}
```
Then for tying everything together, I would do something like this:
```kotlin
    fun createApi(port: Int, endpoints: List<Endpoint>): Http4kServer {

        val handlers = endpoints.map {
            it.path() bind it.method() to it.handler()
        }
        return routes(list = handlers.toTypedArray()).asServer(Undertow(port))
    }
```
I'll call this function from my `main` like this:
```kotlin
createApi(9000, listOf(HealthEndpoint, <other endpoints here>))
```

This seems to work. However, when I add OpenAPI to the mix, things get complicated. I tried to create a contract, but got stuck with the meta thing:
```kotlin
    fun createApi(port: Int, endpoints: List<Endpoint>): Http4kServer {
        val openApiContract = contract {
            renderer = openApiRenderer
            descriptionPath = "spec"
            endpoints.forEach { endpoint ->
                routes += endpoint.path() meta { } bindContract endpoint.method() to endpoint.handler()
            }        
        }
        val handler = routes(
            BASE_PATH bind filter.then(openApiContract),
            "/" bind openApiContract,
        )
        return handler.asServer(Undertow(port))
```
This compiles and runs, but obviously the metadata is missing. I could not find any way to replace the `meta { }` DSL part with something I could put in my `Endpoint` interface. If I add a member of type `RouteMeta` to my interface, how could I pass that to the contract in above code?

**Comment by daviddenton** [comment]
The meta function can take a reference to a Kotlin function, so this is very easy to do - either your endpoint interface can implement that signature, or it can supply a function that returns it:

```kotlin
   val function: RouteMetaDsl.() -> Unit = {
        //whatever here
    }
    "/whatever" / Path.string().of("id") meta(function) bindContract GET to { id: String ->
```

Closing this off for now as it's possible without modification to the lib. 😄

**Comment by bartkummel** [comment]
Cool, thanks for the very quick reply! 👍🏻 

One suggestion: it's hard to come up with this using autocompletion or reading the code. Would be very helpful to add some documentation or an example.
