### ISSUE TITLE
OpenTelemetry tracing uses bad default span naming

### ISSUE THREAD

**Issue by krissrex** [http4k/http4k#867]
https://github.com/http4k/http4k/blob/1a7972532798deb9d5c4c9c260f133179c9d0663/http4k-opentelemetry/src/main/kotlin/org/http4k/filter/tracingFiltersOpenTelemetryExtensions.kt#L24

A quote directly from https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#name :
> Instrumentation MUST NOT default to using URI path as span name

If you are curious why, it's because a tracing GUI like AWS X-Ray will look like this:
![image](https://user-images.githubusercontent.com/7364831/226051317-7549675c-dba4-4570-8995-74f3da5f2bd7.png)

---

The default namer does not even include the method (GET/POST) when naming
> HTTP client spans have no http.route attribute since client-side instrumentation is not generally aware of the “route”, and therefore HTTP client spans SHOULD use `{http.method}`.

Naming a span _only_ `method` seems a bit too broad, however. See recommendations at https://opentelemetry.io/docs/reference/specification/trace/api/#span .

Here is the most recent discussion on span naming for HTTP: https://github.com/open-telemetry/opentelemetry-specification/issues/2998#issuecomment-1409574597 .

---

Also, the status code is not used in the trace:

> For HTTP status codes in the 4xx range span status [...] MUST be set to Error in case of SpanKind.CLIENT.
> For HTTP status codes in the 5xx range, as well as any other code the client failed to interpret, span status MUST be set to Error.

But that is probably a separate issue.

---

I propose that the default namer is changed to use `request.method`, or not be optional.
The current default is "harmful".

**Comment by krissrex** [comment]
I'm uncertain if the current implementation also leaks credentials in the uri
as noted in
https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#http-client :
> [1]: http.url MUST NOT contain credentials passed via URL in form of https://username:password@www.example.com/. In such case the attribute’s value should be https://www.example.com/.

**Comment by krissrex** [comment]
A temporary workaround is to override the defaults like this:

```kotlint
    ClientFilters.OpenTelemetryTracing(
        spanNamer = { it.method.name },
        spanCompletionMutator = { span, req, res ->
          span.setAttribute(SemanticAttributes.NET_PEER_NAME, req.uri.host)
          req.uri.port?.let {
            if (it != 80 && it != 443) {
              span.setAttribute(SemanticAttributes.NET_PEER_PORT, it)
            }
          }
          res.body.length?.let {
            span.setAttribute(SemanticAttributes.HTTP_RESPONSE_CONTENT_LENGTH, it)
          }
          req.body.length?.let {
            span.setAttribute(SemanticAttributes.HTTP_REQUEST_CONTENT_LENGTH, it)
          }

          if (res.status.code >= 400) {
            span.setStatus(StatusCode.ERROR)
          }
        })
```

Note my attribute contstants are from:

```xml
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-semconv</artifactId>
      <version>1.24.0-alpha</version>
    </dependency>
```

**Comment by krissrex** [comment]
Here's the naming from otel auto instrumentation:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f5f83fdeb8a09d0a5635dae8e0712c655888dbb5/instrumentation-api-semconv/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpSpanNameExtractor.java#L35-L50

**Comment by daviddenton** [comment]
Thanks for the comprehensive report @krissrex ! 😄  

I agree that we should be doing better here - the user-info especially needs to be removed for sure, and the rest makes a lot of sense. We're going to canvas opinions from some teams currently using OT in prod in anger to see what their settings are - but will definitely look to make some improvements soon. Feel free to PR your changes as a starting point.

**Comment by daviddenton** [comment]
Have fixed this (or at least first pass). It copies the standard pattern for naming the trace (in both client and server - since we can actually route client requests as well 😄 ).  I've also picked up the fixes for the StatusCodes and added your changes from the semconv.

**Comment by krissrex** [comment]
Awesome!

> We're going to canvas opinions from some teams currently using OT in prod in anger to see what their settings are

Did you get some opinions? Curious to hear from others.

**Comment by daviddenton** [comment]
There were no dissenting voices. 😉  Hopefully we're in a better place when this goes out. Expect a release in the next couple of days 😄

**Comment by daviddenton** [comment]
and thanks again for raising it!
