### ISSUE TITLE
Make http4k available via SDKMAN! again

### ISSUE THREAD

**Issue by christianhujer** [http4k/http4k#873]
http4k used to be available through SDKMAN!.
The last version for which this seems to be the case is 4.0.0.0.
It would be great if http4k became available through SDKMAN! again.

**Comment by daviddenton** [comment]
This actually shouldn't be required at all. The entity that is available through SDKman and brew is actually just the CLI client which talks to the http4k toolbox API. We released it as the same time as http4k v4. If we released it again. If you use the CLI tool to generate projects, you will automatically get the most recent version of the code that is distributed by the toolbox (which is v4.40.1.0)

We will admit that the naming is confusing though. :)

There should be complete compatibility between. Please let us know if it doesn't work for you. 😄 

(closing this off but please reopen if you have problems 😄 )

**Comment by christianhujer** [comment]
Ok, understood. In that case, shouldn't http4k be entirely removed from _SDKMAN!_?
