### ISSUE TITLE
Add HTTP/2 support to Jetty

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#879]
Jetty seems to support http2, but short of passing in a custom `Server` instance, there's no easy option to enable it on the http4k `PolyServerConfig`.  We should add an `enableHttp2` property, like Undertow has.

**Comment by daviddenton** [comment]
Hmm - we've always been slightly worried about the explosion of options. Does the example in `JettyHttp2Test` not solve this at all?

**Comment by oharaandrew314** [comment]
Hmm, I guess it does.

**Comment by oharaandrew314** [comment]
It seems like Jetty requires TLS for http2, which is detrimental when my LB terminates it.  🤷

**Comment by oharaandrew314** [comment]
Seems like we are missing docs, but I didn't even think to look, since the `Jetty` class was missing the obvious `enableHttp2` flag that `Undertow` had.

Might be worth adding a recipe somewhere, since the solution only seems obvious to me in hindsight.
