### ISSUE TITLE
Support for naming models in Swagger

### ISSUE THREAD

**Issue by danschultz** [http4k/http4k#88]
I'm using the contracts library to generate Swagger definitions for my API, and then using `swagger-code-gen` to generate client libraries in different languages. Currently, the Swagger model definitions from Http4k look like:

```json
"definitions" : {
  "object-1918755743" : {
    "type" : "object",
    "properties" : {
      "reason" : {
        "type" : "string"
      }
    }
   },
  "object1265469862" : {
    "type" : "object",
    "properties" : {
      "id" : {
        "type" : "integer"
      },
      "title" : {
        "type" : "string"
      }
    }
  }
}
```

Instead, I'd like to give these models a name, so they're named correctly in our generated Python library as well in our Swagger UI docs.

**Comment by daviddenton** [comment]
Is this mitigated by the operationId PR? If so, can we close it? 😀

**Comment by danschultz** [comment]
@daviddenton `operationId` only helps customize the naming of endpoints. This feature is to customize the naming of model types (request and response types). Would be great if naming was inferred by the class name, with a way to override it if needed.

**Comment by daviddenton** [comment]
We definitely can't use the classname, because the API only takes requests and response objects and I think we'd like to keep that simplicity. Underneath, we could possibly use a custom header that was set in the HTTP message to set the value if required. Would that work?

**Comment by danschultz** [comment]
What do you think of having some wrapper or metadata type to define additional info about the response objects. We could have a helper to create a “metadata” object from a Response instance.

**Comment by daviddenton** [comment]
I'm not against the idea - we can provide it as an option which is invisible to the user. The main complexity that I can see is with the JsonSchema class. The generation of the "definitionId" is embedded within the recursive call to the JSON schema generation. Need to work out the best way to embed.

Note that either approach would only end up with you being able to name the "top level objects" - ie. the main request and response bodies. The sub objects would still be automatically named based on the hashcode of the JSON object.

**Comment by danschultz** [comment]
> Note that either approach would only end up with you being able to name the "top level objects" - ie. the main request and response bodies. The sub objects would still be automatically named based on the hashcode of the JSON object.

Missed that, thanks for pointing that out. I think from a DX perspective, folks would expect the model types get automatically named down the object graph.

**Comment by daviddenton** [comment]
@danschultz I've put a fix in for this using a meta object as you suggested. Take a look at https://github.com/http4k/http4k/blob/master/http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt and let me know if that API would work out for you?

**Comment by daviddenton** [comment]
Will be released in 3.14.0

**Comment by danschultz** [comment]
Works for me! Thanks @daviddenton!

**Comment by daviddenton** [comment]
Excellent. Closing to release.

**Comment by mindscratch** [comment]
@danschultz where is the name for the items in "definitions" being set?

**Comment by mindscratch** [comment]
@danschultz where is the name for the items in "definitions" being set? For "receiving" I see I can set a `definitionId`, but is there a way to do that for the `returning`? For example I have something like this currently:
```
returning(
   "submitted successfully" to Response(CREATED).with(Body.auto<MyResponse>().toLens() of MyResponse("success!")))
```

**Comment by mindscratch** [comment]
Oh I see...
```
returning(
   ResponseMeta("submitted successfully", Response(CREATED).with(Body.auto<MyResponse>().toLens() of MyResponse("success!")), "my-response")
)
```
