### ISSUE TITLE
Testing section is not shown on https://www.http4k.org/guide/reference/

### ISSUE THREAD

**Issue by dzappold** [http4k/http4k#889]
Hey, 

I'm still struggling to fix the missing `testing` section in `reference` section. This issue appeared since `Fault Tolerance` section was introduced, see attached screencast.
https://user-images.githubusercontent.com/10990718/233854823-4c99a7de-d19b-4acb-89e8-10609cd1a1bd.mov

I tried some stuff with `src/docs/theme/partials/nav-item.html` and inside of `mkdocs.yml` locally, but wasn't successful so far.
Any hints where I could continue?

**Comment by daviddenton** [comment]
Are we hitting the max-depth problem? The theme breaks when you get beyond a certain number of levels.. we've encountered this before

**Comment by dzappold** [comment]
I thought about that, but wasn't sure.

**Comment by daviddenton** [comment]
For the moment, I've flattened out the FaultTolerance section. We're not going to solve the mkdocs material problem I think - it's here for reference. https://github.com/mkdocs/mkdocs/issues/1140

I think I'm going to close this unless we find a way to work around it.

**Comment by dzappold** [comment]
Sure! As long new http4k users have full access to the documentation :-)
