### ISSUE TITLE
Can OauthCallback handle error parameters in the callback from Oauth2 providers ?

### ISSUE THREAD

**Issue by andrewmcnamara** [http4k/http4k#895]
When using  [hydra](https://github.com/ory/hydra) as an Oauth2 provider. It will can return an error in the callback url

e.g. `http://some.host/users/auth/callback?error=invalid_scope&error_description=The+requested+scope+is+invalid,+unknown,+or+malformed.+The+OAuth+2.0+Client+is+not+allowed+to+request+scope+'openissd'`

The callback code doesn't  seem to handle these parameters 
https://github.com/http4k/http4k/blob/503289c55e15dd12b9e06b20bf6e1fa573dca427/http4k-security/oauth/src/main/kotlin/org/http4k/security/OAuthCallback.kt#L24-L37

Is there any way these errors can be surfaced from this callback class ?

**Comment by s4nchez** [comment]
@andrewmcnamara, you should be able to customise that error handling by overriding the [`authFailureResponse` method in `OAuthPersistence`](https://github.com/http4k/http4k/blob/503289c55e15dd12b9e06b20bf6e1fa573dca427/http4k-security/oauth/src/main/kotlin/org/http4k/security/OAuthPersistence.kt#L70).

Please let us know if that does what you need.

**Comment by daviddenton** [comment]
The issue here is that I think you will just end up with a OAuthCallbackError.AuthorizationCodeMissing error, which is generated by:

```
    private fun Request.authorizationCode() = queryOrFragmentParameter("code")?.let(::AuthorizationCode)
        ?.let(::Success) ?: Failure(OAuthCallbackError.AuthorizationCodeMissing)
```

... which does lose the context of exactly what went wrong. We could add the callback URI to the constructor of AuthorizationCodeMissing and that would allow the response behaviour to be customised: 
 
```    object AuthorizationCodeMissing : OAuthCallbackError()```

BTW - Hydra seems to be a private github repo  - is it a proprietary product?

**Comment by andrewmcnamara** [comment]
Apologies for the incorrect link - updated. 

@daviddenton 

`OAuthCallbackError.AuthorizationCodeMissing` does indeed lose the context of what went wrong. In the case above the error returned from `Hydra`  was due to a misconfiguration, with the result being that no authorization code was returned.   

If the original  callback URI to `AuthCallbackError`  was added  as you suggested that  would definitely allow us to get the original error code/description from the URI.

**Comment by andrewmcnamara** [comment]
Thank you, that's awesome. And I really appreciate the fast response to my issue.
