### ISSUE TITLE
How can I bind POST to a sse consumer

### ISSUE THREAD

**Issue by ljj038** [http4k/http4k#907]
in the guide `https://www.http4k.org/guide/howto/serve_sse/`
there is only the default GET method to bind a sse consumer

is there any way to bind a POST method to a sse consumer?

**Comment by daviddenton** [comment]
Technically it's possible, but it's apparently not in the spec and probably unsupported by many JS clients. The http4k handlers are bound to GET requests (see JettyEventStreamHandler) only, but you could write a custom one to bind to anything.

https://stackoverflow.com/questions/34261928/can-server-sent-events-sse-with-eventsource-pass-parameter-by-post

https://github.com/http4k/http4k/blob/5ccdbcfcc952db73579a50a4f3384cf77875353e/http4k-server/jetty/src/main/kotlin/org/http4k/server/JettyEventStreamHandler.kt#L54
