### ISSUE TITLE
Allow RouteMetaDsl to be marked as hidden

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#910]
The `RouteMetaDsl.markAsDeprecated` method is useful, but sometimes I'd like to go the extra mile and actually exclude it from the OpenApi spec.  This can be done by converting the `ContractRoute` to a regular non-contract `HttpHandler`, but it would be nice to be able to perform a deprecation with minimal effort, and still take advantage of the path routing.

I propose adding a `RouteMetaDsl.markAsHidden` method that will prevent it from being included in the OpenApi spec.  Thoughts?

**Comment by daviddenton** [comment]
Interesting idea. Sounds doable and I'm not against it. But I wouldn't call it "markAsHidden". Maybe "excludeFromContract" or similar? Wdyt?

**Comment by oharaandrew314** [comment]
I can't really think of anything perfect.

- `markAsHidden`: implies we're simply adding a flag to the operation for the UI to interpret
- `excludeFromContract`: makes me thing of http4k-contract, which implies the operation cannot be routed to
- `render = false` could work
- `markAsDeprecated(hidden=true)` just adds on to the uncertainty of what `hidden` means by implying this is an extension to OpenApi's support for deprecated operations

**Comment by daviddenton** [comment]
I think hidden and depreciation are 2 different concerns, so we should not mix them.

How about "describeRoute = false"?

**Comment by oharaandrew314** [comment]
`describeRoute = false` makes sense to me.

Actually here's a new idea; so far, it seems impossible for a feature flag to control whether an operation is visible, or routable.  What if we combine the two into something like this?

```kotlin
enum class LifecycleRule {
  Standard, // visible and routable
  Deprecated, // mark as deprecated
  EndOfLife, // not visible but still routable
  Terminated // not visible or routable
}
fun lifecycleStrategy(fn: (Request) -> LifecycleRule)
```
