### ISSUE TITLE
docs: tracerbullet/incubator dependencies confusion

### ISSUE THREAD

**Issue by corlaez** [http4k/http4k#924]
What is the difference between the dependencies used by 

```kotlin
// https://www.http4k.org/guide/reference/tracerbullet/
dependencies {
    implementation(platform("org.http4k:http4k-bom:4.41.4.0"))
    implementation("org.http4k:http4k-testing-tracerbullet")
}

// and the dependencies used by
// https://www.http4k.org/guide/howto/self_document_systems_with_tests/
dependencies {
    implementation(platform("org.http4k:http4k-bom:4.47.2.0"))
    implementation("org.http4k:http4k-incubator")
}
```

The code samples on those pages seems very similar, what is the recommended way to implement this?

**Comment by daviddenton** [comment]
You've caught us in the middle of a migration. They are the same thing. 🙃

The tracerbullet module is being promoted to it's own level module in v5 (which is about to be released). The docs have been updated but the code not released yet.

For v4, you need the incubator module and not the tracerbullet module. From v5 it will be the testing/tracerbullet.

But the APIs are the same anyway. The docs will be being improved soon. There is a repo with a demo on how this all looks in a proper projectx: https://http4k.org/hyperpyramid

**Comment by corlaez** [comment]
Thanks, I will close this as it seems to be already in the works. I am very interested in your flavor of Hexagonal Architecture and working on a example app myself (with a more hypermedia focus).
