### ISSUE TITLE
values4kExtensions lacks support for Float and Double

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#925]
If you create a values4k `FloatValue`, then registering it to a marshaller with `values4kExtensions.kt:value` results in the value being serialized to a string.  This is because there is no built-in `value` function for a `FloatValue`, and it instead uses the `stringMapper` variant.

Judging by the existence of a `bigDecimal` variant, I wonder if this was intentional, to minimize the possible loss of precision from floating point numbers?  Or was this just an oversight?

**Comment by daviddenton** [comment]
I think floats are fair game to be transmitted as a standard number. PR appreciated if you've got time, or we can stick it on the pile :)

**Comment by oharaandrew314** [comment]
So double is actually supported; I think that's good enough.

Adding explicit support for `float` would require to either:
- Add an `AutoMappingConfiguration.float` method
- Have the values4kExtension map to a double internally

I don't think either option is very valuable.

**Comment by daviddenton** [comment]
Yep - I'm tended to agree that it's not worth having both, but serialising as a definite number is probably still fair game for a change if needed
