### ISSUE TITLE
http4k-security-oauth requires reflection

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#929]
http4k-security-oauth relies on kotlin-reflect to be present on the classpath to (de)serialize token requests and responses.  This isn't ideal on serverless environments, where kotlin-reflect is avoided.

I propose we eliminate `kotlin-reflect` from `http4k-security-oauth`, and replace it with hand-crafted Moshi serializers like in `http4k-serverless-lambda:AwsLambdaMoshi`, or with kotshi serializers as is done in http4k-connect.

**Comment by s4nchez** [comment]
I'm in favour of using the same approach as `http4k-serverless-lambda:AwsLambdaMoshi`, for now, to keep things consistent.

**Comment by daviddenton** [comment]
Yes - we should hand craft the adapters and get rid of the dependency. Fancy taking a run at it @oharaandrew314 ? :)

**Comment by oharaandrew314** [comment]
Yes, I can do it.
