### ISSUE TITLE
Setting headers for SSE-response

### ISSUE THREAD

**Issue by staklau** [http4k/http4k#931]
I'm trying to figure out how to set custom headers for the response when using SSE.
My browser is complaining that `No 'Access-Control-Allow-Origin' header is present on the requested resource` and I can't figure out how to set the headers for the response like you can do for the `Response` object in a "regular" HTTP request:
```
  val sse = org.http4k.routing.sse(
    "/hello" bind org.http4k.routing.sse(
      "/{name}" bind { sse: Sse ->
        val name = sse.connectRequest.path("name")!!
        
        sse.send(SseMessage.Event("event1", "hello $name", "123"))
        sse.send(SseMessage.Event("event2", "again $name\nHi!", "456"))
        sse.send(SseMessage.Data("goodbye $name".byteInputStream()))
      }
    )
  )
```

My initial thought was that it should exist a CORS-filter like it does for regular HTTP requests:
```
    .then(
      ServerFilters.Cors(corsPolicy),
    )
```
Any suggestions would be appreciated.

**Comment by daviddenton** [comment]
So this currently isn't possible without digging down into the guts and changing the definition of SSE. Looking at it, I think it is probably required to make this work..

**Comment by daviddenton** [comment]
Well, assuming you are using Jetty, it would involve creating your own version of the server-backend and explicitly: `JettyEventStreamHandler`. This is pretty horrid TBH and would only work if you really want to set a standard set of headers for every SSE request

**Comment by daviddenton** [comment]
We think we have an idea of the type of change that might be required - we'll keep you posted

**Comment by staklau** [comment]
@daviddenton Then I'll stay put for now :)

**Comment by daviddenton** [comment]
We've managed to fix this and are releasing the changes as a part of 5.1.0.0 :)

**Comment by staklau** [comment]
@daviddenton Great, thanks! :)

**Comment by staklau** [comment]
@daviddenton Hi! I thought this was solved but when I'm trying to create a CORS-filter with the `SseFilter` I'm not allowed to set any headers for the response, ref:
```
  val corsFilter = SseFilter { next ->
    { request ->
      val response = next(request)
      response.header("Access-Control-Allow-Origin", "*") <-- the .header method does not exist
      response
    }
  }
```

Let me know If I'm missing something.

**Comment by staklau** [comment]
@daviddenton Ah nevermind I forgot about the `copy` method, ref: 
`      response.copy(headers = listOf("Access-Control-Allow-Origin" to "*"))`
