### ISSUE TITLE
AWS SQS deserialization issue when md5OfMessageAttributes is null

### ISSUE THREAD

**Issue by ashcor** [http4k/http4k#933]
Unfortunately, the `md5OfMessageAttributes` field of the `SQSEvent` can be set to `null`.
![image](https://github.com/http4k/http4k/assets/94228/64173e24-170b-4437-b18c-65c56fa31c5d)

Seems to happen when the batch window is increased and there is more than one record in the event.
![image](https://github.com/http4k/http4k/assets/94228/075dca8c-f3d8-4c64-b9ad-7bb757ca5608)

That causes an exception in the `SQSEventAdapter`.

Can be reproduced with the below test.
```kt
    @Test
    fun `SQS event with null md5OfMessageAttributes`() {
        val json = """
            {
              "Records": [
                {
                  "messageId": "messageId",
                  "receiptHandle": "receiptHandle",
                  "body": "body",
                  "md5OfBody": "md5OfBody",
                  "md5OfMessageAttributes": null,
                  "eventSourceArn": "eventSourceArn",
                  "eventSource": "eventSource",
                  "awsRegion": "awsRegion",
                  "attributes": {
                    "attr": "attrvalue"
                  },
                  "messageAttributes": { }
                }
              ]
            }
        """.trimIndent()
        val evt = asA<SQSEvent>(json)
        assertNull(evt.records[0].md5OfMessageAttributes)
    }
```

 A fix would be to read the attribute as `"md5OfMessageAttributes" -> md5OfMessageAttributes = readJsonValue() as String?` but not sure that is the best way to go.

**Comment by daviddenton** [comment]
Thanks for the report! We'll take a look 😄

**Comment by daviddenton** [comment]
Yep - that's the best fix. 5.1.1.1 is on it's way to Maven. Thanks for the report! 🙃

**Comment by daviddenton** [comment]
It should be there now to update to :)

**Comment by ashcor** [comment]
Thanks for the fast fix 🚀
