### ISSUE TITLE
AWS signature converts headers incorrectly to canonical headers

### ISSUE THREAD

**Issue by krissrex** [http4k/http4k#947]
Related to #656 .

Two bugs: spaces are not deduplicated, and duplicate header values are not joined.

I have a fix for both coming up, for headers. 
Not a fix for the object key thing, in #656.

The spaces are not deduplicated because the `"\\s+"` regex was passed as a literal string pattern.

**Comment by s4nchez** [comment]
That's been fixed in 5.4.0.0. Thank you for the PR, @krissrex.
