### ISSUE TITLE
Support activej?

### ISSUE THREAD

**Issue by jhult** [http4k/http4k#957]
I don't personally need it, but it seems like [activej](https://activej.io/overview) may be an interesting framework to support (whether for [serialization](https://activej.io/serializer) or [HTTP client/server](https://activej.io/http)). I originally came across it on [web benchmarks](https://web-frameworks-benchmark.netlify.app/result).

**Comment by daviddenton** [comment]
I don't think this is a good match - purely because the APIs are so different. ActiveJ seems to be built entirely on callbacks, and we are working with an sync-style in the project, and falling back on Loom implementations to give us async behaviours (ie. in the JVM and not in the core codebase ) 😄
