### ISSUE TITLE
RouterBasedHttpHandler is internal

### ISSUE THREAD

**Issue by geertmulders** [http4k/http4k#958]
Normally I add a list of routers by using the `routes(vararg list: RoutingHttpHandler)` function. Now I wanted a custom error handler is the route could not be found; luckily behind `routes` there is the `RouterBasedHttpHandler` class, that can do just that!

Less luckily this class is internal, so I cannot use it.

Adding the following would really help:

```
    private fun routes(
        vararg list: RoutingHttpHandler,
        notFoundHandler: HttpHandler = routeNotFoundHandler,
        methodNotAllowedHandler: HttpHandler = routeMethodNotAllowedHandler,
    ): RoutingHttpHandler =
        routes(list.toList(), notFoundHandler, methodNotAllowedHandler)

    private fun routes(
        list: List<RoutingHttpHandler>,
        notFoundHandler: HttpHandler = routeNotFoundHandler,
        methodNotAllowedHandler: HttpHandler = routeMethodNotAllowedHandler,
    ): RoutingHttpHandler =
        RouterBasedHttpHandler(OrRouter.from(list), notFoundHandler, methodNotAllowedHandler)
```

I can make a PR if you like.

**Comment by daviddenton** [comment]
You can actually already do this without needing to expose any more complexity into the routing: 

```kotlin
val myApp = routes(
    "/bob" bind GET to { _: Request -> Response(OK) },
    Router.orElse bind { _: Request -> Response(NOT_FOUND) },
)
```

**Comment by daviddenton** [comment]
Closing this off now as don't think it's required 😄
