### ISSUE TITLE
WebDriver .submit() fails when form field is empty

### ISSUE THREAD

**Issue by jmerkle** [http4k/http4k#962]
In the latest version of http4k (5.6.4.0), our tests utilising the .submit() method of http4k webdriver fail when form fields are left blank. 
The error is 
`Exception in thread "main" org.http4k.lens.LensFailure: formData 'field_name' is required`

Can be reproduced with this:

```
package http4kbug

import org.http4k.core.Method.GET
import org.http4k.core.Response
import org.http4k.core.Status.Companion.OK
import org.http4k.routing.bind
import org.http4k.routing.routes
import org.http4k.webdriver.Http4kWebDriver
import org.openqa.selenium.By

fun main() {
    val html = """
        <html>
        <body>
        <form method="post" action="/">
            <input type="text" name="field_name" value=""><br><br>
            <input class="submit" type="submit" value="Submit">
        </form>
        </body>
        </html>
    """.trimIndent()


    val app = routes(
        "/hello" bind GET to {
            Response(OK).body(html)
        }
    )

    val driver = Http4kWebDriver(app)

    driver.navigate().to("http://localhost:10000/hello")

    driver.findElement(By.className("submit"))?.submit()
}
```

this is likely due to https://github.com/http4k/http4k/issues/956, as it is working fine with 5.5.0.0

**Comment by daviddenton** [comment]
Yes - this was part of the breaking change introduced with 5.6.0.0, and you will have to change your lenses to optional of to default to an empty string if they are not there. 😄 


https://github.com/http4k/http4k/releases/tag/5.6.0.0

**Comment by jmerkle** [comment]
there are no lenses in the code above, this is an issue with the http4k webdriver implementation. But i see this is also being discussed here https://github.com/http4k/http4k/issues/963
