### ISSUE TITLE
Submitting empty textarea form element in the webdriver causes a validation error

### ISSUE THREAD

**Issue by gypsydave5** [http4k/http4k#963]
adding this test to [`Http4kWebDriverTest.kt`](https://github.com/http4k/http4k/blob/b9ff74ddb7ec61f903174284a6f7f0ad3ee81503/http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverTest.kt)

```kotlin
    @Test
    fun `POST form with an empty text box`() {
        driver.get("https://example.com/bob")
        driver.findElement(By.tagName("textarea"))!!.sendKeys("")
        driver.findElement(By.id("button"))!!.submit()
        driver.assertOnPage("https://example.com/form")
        assertThat(driver.findElement(By.tagName("thebody"))!!.text, equalTo("text1=textValue&checkbox1=checkbox&textarea1=textarea&select1=option1&select1=option2&button=yes"))
        assertThat(driver.findElement(By.tagName("themethod"))!!.text, equalTo("POST"))
    }
```

gives the following error:

```shell
formData 'textarea1' is required
org.http4k.lens.LensFailure: formData 'textarea1' is required
```

it blows up on `submit()`

**Comment by daviddenton** [comment]
This is an areifact of the test setup - the fields in the test are mapped to   `FormField.multi.required(it.key)`. This means that it blows up because as per the change in 5.6.0.0, fields with empty values are now filtered out.

What are you seeing expecially?

**Comment by gypsydave5** [comment]
Yeah, I see that in the `submit` method body it's got `FormField.multi.required(it.key)` when it maps. But I can't see a way to override this mapping. Does this mean that it's not possible for the default webdriver to submit empty fields? Or should we be mapping to optional/required based on the presence of a `required`

**Comment by daviddenton** [comment]
@gypsydave5 shouldn't your test be: 

```kotlin

    @Test
    fun `POST form with an empty text box`() {
        driver.get("https://example.com/bob")
        driver.findElement(By.tagName("textarea"))!!.sendKeys("")
        driver.findElement(By.id("button"))!!.submit()
        driver.assertOnPage("https://example.com/form")
        assertThat(driver.findElement(By.tagName("thebody"))!!.text, equalTo("text1=textValue&checkbox1=checkbox&textarea1=&select1=option1&select1=option2&button=yes"))
        assertThat(driver.findElement(By.tagName("themethod"))!!.text, equalTo("POST"))
    }

```

**Comment by jmerkle** [comment]
jumping over into this ticket.

i made the existing tests in [JSoupWebElementTest.kt ](https://github.com/http4k/http4k/blob/master/http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/JSoupWebElementTest.kt) fail by adding name to the input field created in the form method. Maybe that's a bit easier to understand than the example @gypsydave5 gave

`<input id="text" type="text" name="text"/>` in this [line](https://github.com/http4k/http4k/blob/cb86d4018e7b4e9007765aad9333342a598b26b1/http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/JSoupWebElementTest.kt#L39)

**Comment by gypsydave5** [comment]
Apologies @daviddenton for the less than obvious example - the assertion isn't where it fails, it blows up on validation in the `submit` method. 

This also fails:

```kotlin
    fun `POST form with an empty text box`() {
        driver.get("https://example.com/bob")
        driver.findElement(By.tagName("textarea"))!!.sendKeys("")
        driver.findElement(By.id("button"))!!.submit()
    }
```

@jmerkle example is good too!

**Comment by gypsydave5** [comment]
I think the fix here would be to reduce the level of validation in the lens on the form elements here:

https://github.com/http4k/http4k/blob/e6e6011cafdd93c219e61fa237b5fb5737151952/http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt#L76C1-L79

either by reducing the validator to a `Validator.Ignore`, or by using a `FormField.multi.optional(it.key)` in the map.

The luxury version would look at the `required` attribute on the element and map to `FormField.multi.required(it.key)` when it was set.

**Comment by gypsydave5** [comment]
looks good to me - I've got code for the "required if `required`" version on my machine, but I think it might be over-cooking it.

:shipit:
