### ISSUE TITLE
ContractRoute - inconsistent behavior on route matching

### ISSUE THREAD

**Issue by potfur** [http4k/http4k#964]
It seems that there is some inconsistency how `ContractRoute` matches requests to route.

When route starts with path lens, the leading slash is optional, and this case is covered [here](https://github.com/http4k/http4k/blob/master/http4k-contract/openapi/src/test/kotlin/org/http4k/contract/ContractRouteTest.kt#L111-L116)

```kotlin
val route = Path.int().of("value") meta {} bindContract GET to { { Response(OK) } }
assertThat(route(Request(GET, "/1")), hasStatus(OK))
assertThat(route(Request(GET, "1")), hasStatus(OK))
```

As soon as there is something in front of path lens, things fall apart

```kotlin
val route = "something" / Path.int().of("value") meta {} bindContract GET to { { Response(OK) } }
assertThat(route(Request(GET, "/something/1")), hasStatus(OK))
assertThat(route(Request(GET, "something/1")), hasStatus(OK)) // fails
```

This inconsistency prohibits usage of `UriTemplate`, as it strips leading and trailing slashes from the template.

After some digging, I managed to localise the source of the problem - it is in the [Request#without](https://github.com/http4k/http4k/blob/master/http4k-contract/openapi/src/main/kotlin/org/http4k/contract/PathSegments.kt#L43-L44) method, that is used in `ContractRoute` for route [matching](https://github.com/http4k/http4k/blob/master/http4k-contract/openapi/src/main/kotlin/org/http4k/contract/ContractRoute.kt#L49).

As far as I could understand, the `Request#without` method is executed agains original uri that is missing the leading slash, but all the `PathSegments` are already got adjusted and expect leading slash thus returning full path, and not just the segment for path lens.

**Comment by daviddenton** [comment]
Thanks for the investigation @potfur .. made it a very easy fix. Will release in 5.7.1.0 soon
