### ISSUE TITLE
Can't define the file download spec in OpenAPI

### ISSUE THREAD

**Issue by zaqs114** [http4k/http4k#991]
When looking at the `Response That Returns a File` section in [OpenAPI docs](https://swagger.io/docs/specification/describing-responses/) they say that endpoint content should be defined as type: string with format: binary, and that's what I'm aiming for.
```
  "content" : {
    "image/png" : {
      "schema" : {
        "type" : "string",
        "format" : "byte"
      }
    }
  }
```

I'm using this contract route as my playground (you can plug it into [AutoContractRendererContract.kt](https://github.com/http4k/http4k/blob/master/http4k-contract/openapi/src/test/kotlin/org/http4k/contract/AutoContractRendererContract.kt)):
```kotlin
routes += "/downloadable_image" meta {
    returning(
        ResponseMeta(
            description = "",
            response = Response(OK).with(
                Body.binary(ContentType("image/png")).toLens() of "fooBar".byteInputStream()
            ),
            example = "fooBar".byteInputStream(),
        )
    )
} bindContract GET to { _ -> Response(OK) }
```

If Ill leave it like that, I'm getting 
`java.lang.IllegalArgumentException: No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)` 

If Ill adjust the Jackson configuraiton with `.configure(FAIL_ON_EMPTY_BEANS, false)` spec is generated with InputStream defined as object: 

```
  "content": {
    "image/png": {
      "schema": {
        "$ref": "#/components/schemas/ByteArrayInputStream"
      }
    }
  }
  (...)
"ByteArrayInputStream": {
"properties": {
},
"example": {
},
"type": "object"
}

```

If Ill update the example to use `example = "fooBar".toByteArray()` (which is I guess what I want), Im getting `java.lang.IllegalArgumentException: Don't know how to translate "Zm9vQmFy"`. 

I assume that to make it work, JsonType.Binary and generating proper schema for binary types would have to be added.

I did a small test and managed to adjust the code to fix that problem, but I'm not sure how does it fit into the grand schema of things

Unless Im doing it wrong and there is a way to do it properly?

**Comment by daviddenton** [comment]
I think you want to use this: 
```kotlin
        returning("XLS" to Response(OK).with(CONTENT_TYPE of OCTET_STREAM))
        returning("JSON" to Response(OK).with(CONTENT_TYPE of APPLICATION_JSON))
```
Which generates in the output:

```json
 "responses": {
          "200": {
            "description": "JSON,XLS",
            "content": {
              "application/json": {
                "schema": {
                }
              },
              "application/octet-stream": {
                "schema": {
                }
              }
            }
          }
        }
```

I think this should work, so closing. Please reopen if you need to :)

**Comment by zaqs114** [comment]
Well, not exactly. For 
```kotlin
returning("PDF" to Response(OK).with(CONTENT_TYPE of APPLICATION_PDF))
```
we'll have 
```yaml
        "responses": {
          "200": {
            "description": "PDF",
            "content": {
              "application/pdf": {
                "schema": {
                }
              }
            }
          }
        },
```

and we're missing the schema bit that is described in OpenAPI docs. Even in your examples your octet-stream lacks the `schema: type: string format: binary` bit.

**Comment by zaqs114** [comment]
And I cannot reopen the issue, don't have the button anywhere @daviddenton
